label ch4_main:
    stop music fadeout 2.0
    scene bg residential_day
    with dissolve_scene_full

    play music t6

    "It's already Sunday."
    if ch4_scene == "natsuki":
        "I've been getting increasingly anxious about Natsuki's upcoming visit."
        "I keep telling myself there's no reason to be nervous, but it doesn't help much."
        "I wonder if she'll act any different when it's just the two of us?"
        "Meanwhile, she's been texting me a lot."
        "We sent each other one after exchanging numbers to double-check, but it turned into conversation."
        "She's almost a different personality on the phone, using tons of emoji and cute language."
        "She also really likes complaining about things, but I kind of saw that one coming."
        "But putting Natsuki aside..."
    else:
        "I've been getting increasingly anxious about Yuri's upcoming visit."
        "I keep telling myself there's no reason to be nervous, but it doesn't help much."
        "Yuri is clearly an introvert and also an intimate person in general."
        "There's no doubt that she'll open up a little bit when it's just the two of us."
        "Meanwhile, we've even been texting occasionally."
        "She was extremely apprehensive at first, but it wasn't long before I was already learning more about her."
        "But putting Yuri aside..."
    "I haven't heard a thing from Sayori since she left club early the other day."
    "It's not like we text each other all the time or anything..."
    "But I've been worried about her in the back of my mind."
    "Between what Sayori said, and what Monika said..."
    "Is it really okay for me to put Sayori's feelings aside when she might need me?"

    stop music fadeout 2.0
    scene bg house
    with wipeleft_scene
    "I decide to visit Sayori before [ch4_name] comes over."
    "Rather than asking, I simply tell her \"I'm coming over\", much like we've done in the past."
    "Once I reach Sayori's house, I knock on the door before entering it myself."
    "Again, we used to play so often that we've made it a habit of simply entering each other's houses like we were family."
    scene black with wipeleft
    "The house is quiet."
    "Sayori isn't anywhere on the first floor, so I assume she's up in her room."
    "It's already strange of her not to run down and greet me."
    "I head up to her bedroom, where I finally find her."
    scene bg sayori_bedroom with wipeleft
    mc "Sayori?"
    play music t10
    show sayori 1ba zorder 2 at t11
    s "Hi [player]~"
    show sayori 1by
    "I sit down in her room."
    "Sayori forces a smile, but it's easy to tell that she's different."
    "There's a minute of silence between us."
    s "You haven't come over like this in a long time, have you?"
    mc "Ah... I guess you're right."
    mc "It has been a long time."
    mc "Not much has really changed, has it?"
    "Sayori's room is as messy as it's always been."
    "I also recognize the same stuffed animals and wall decorations that she's had for years now."
    s 2bl "Ehehe~"
    s "If you came over more often, it wouldn't be such a mess."
    mc "That's because I end up cleaning it for you..."
    s 1bb "How come you suddenly wanted to come over today?"
    s "Aren't you supposed to see [ch4_name] today?"
    mc "Yeah, but..."
    mc "...Wait, how did you know that?"
    "Sayori had already left by the time we decided that last meeting."
    s 1ba "Monika told me."
    s "It's only natural for her to keep me informed about the festival preparations, right?"
    mc "Ah, that's true..."
    mc "But what about you?"
    mc "Aren't you going to be helping Monika today?"
    s 4bb "Of course!"
    s "But I'm just helping her online."
    s "We didn't plan to meet up or anything."
    mc "Ah, so it's just me and [ch4_name], then..."
    s 1ba "Yep~"
    "There's more silence between us."
    show sayori 1bk
    "Sayori stares in a random direction."
    "Everything about her behavior is really uncharacteristic."
    "I finally get to the point."
    mc "I just...wanted to see how you were doing."
    mc "After you left on Friday."
    mc "When something's wrong, you can't hide it from me!"
    mc "I know you too well."
    mc "So..."
    "Sayori smiles, shaking her head."
    s 1bd "That's no good, [player]."
    mc "Eh?"
    s "Why can't it just be like it's always been?"
    s 1by "This is all my fault."
    s "If I didn't get so weak and accidentally express my feelings..."
    s 1bk "If I didn't make that stupid mistake..."
    s "Then you wouldn't have been worried about me at all."
    s "You wouldn't have come here."
    s 1bd "You wouldn't have even been thinking about me right now."
    s "But this...is just my punishment, isn't it?"
    s "I'm getting punished for being so selfish."
    s "I think that's why the world decided to have you come over today."
    s "It just wants to torture me."
    s 4bq "Ehehe~"
    mc "Sayori!"
    show sayori 4bb
    "I grab Sayori by the shoulders."
    mc "What on Earth are you saying?!"
    mc "Are you listening to yourself right now?"
    mc "I know something happened to you."
    mc "There's no other explanation for you to be like this."
    mc "So tell me, already...!"
    mc "Until I know, I won't be able to stop thinking about it!"
    s 4bl "Ah..."
    s "Ahaha..."
    "Sayori gives me an empty smile."
    s 4by "You really put me in a trap, [player]."
    s "But..."
    s 1ba "You're wrong."
    s "Nothing happened to me."
    s "I've always been like this."
    s "You're just seeing it for the first time."
    mc "Seeing what?"
    mc "What are you talking about, Sayori?"
    s 1bq "Ehehe~"
    s 1ba "You're really just going to make me say it, aren't you, [player]?"
    s "I guess I have no choice this time."
    s 1bc "The thing is..."
    s "I've had really bad depression my whole life."
    s 1bb "Did you know that?"
    s "Why do you think I'm late to school every day?"
    s "Because most days, I can't even find a reason to get out of bed."
    s 1by "What reason is there to do anything when I fully know how worthless I am?"
    s "Why go to school?"
    s "Why eat?"
    s "Why make friends?"
    s "Why make other people put their energy and caring to waste by having them spend it on me?"
    s "That's what it feels like."
    s "And that's why I just want to make everyone happy..."
    s "Without anyone worrying about me."
    mc "..."
    "I'm in shock."
    "I can't even figure out how to respond."
    "How is it possible that Sayori kept this from me the entire time that I've known her?"
    "Did she really want so badly for me to just not think about her?"
    mc "...Why, Sayori?"
    s 1bg "Eh...?"
    mc "Why is it that you've never told me about this?"
    mc "It almost feels like I've been betrayed as your close friend."
    mc "Because if I knew, I would have done everything I could to support you!"
    mc "Even if there's only so much that I could do..."
    mc "I would have tried a little bit harder to make every day a little better for you."
    mc "That's why I'm your friend!"
    mc "All you had to do was tell me!"
    s 1bk "You don't understand at all, [player]."
    s "Why do you think I didn't tell you?"
    s 1bd "Because if I told you, then you would have to waste effort caring about me instead of doing important things."
    s "I don't want to be cared about."
    s "It's bittersweet, when people try to care about me."
    s 1ba "It feels nice sometimes."
    s "But it also feels like a bat being swung against my head."
    s 4bq "Ahaha~"
    s 4ba "That's why I wanted so badly for you to make friends with everyone else..."
    s "Helping everyone be happy together is the best thing for me."
    s 1bb "But then, I discovered something else, too."
    s "Seeing you make friends and get closer with everyone in the club..."
    s 1bk "It feels like a spear going through my heart."
    s "So, that's why."
    s "That's why I decided the world just wants to torture me."
    s 1by "Every path leads to nothing but hurt."
    s "Ahaha~"
    mc "You're right that I don't understand..."
    mc "I don't understand your feelings at all, Sayori."
    mc "But I don't need to understand."
    mc "Whatever it takes for me to help you stop hurting..."
    mc "That's what I'll do."
    s 1bd "No, [player]."
    s "There's nothing."
    s "Nothing at all."
    s "The only thing that could have helped is if everything could be like it always was."
    s 1bk "But I was selfish."
    s "I finally showed you what a horrible person I am."
    "Tears streak down Sayori's face."
    s 1bv "I made you join the literature club because I was selfish."
    s "And I was punished by my heart hurting in a way that I couldn't understand."
    s "And now you came here and I made you hurt, too."
    s 1bt "I'm just weak and selfish."
    s "That's all I am."
    s "And that's why I'm going to accept these punishments."
    s 1bv "Because I deserve every last one...!"
    "Without thinking, I once again grab Sayori's shoulders."
    "This time, I pull her into a tight embrace."
    scene black with dissolve_cg
    s "A-Ah--"
    s "[player]..."
    mc "Sayori."
    mc "I don't care if you feel selfish."
    mc "I'm really happy that you convinced me to join the club."
    mc "Seeing you every day makes it worthwhile enough."
    mc "If I make friends with everyone else, then that's just a bonus."
    mc "But please never underestimate how much I care about you."
    mc "I wouldn't have it any other way."
    s "[player]..."
    "Sayori isn't hugging me back."
    "Despite my arms being wrapped around her, Sayori's arms remain at her sides."
    "She starts sobbing next to my ear."
    s "No..."
    s "Don't do this...to me..."
    s "Please don't do this..."
    s "[player]..."
    s "I..."
    "Sayori barely manages to speak between her sobs."
    "I don't know if I'm doing the right thing."
    "But all I want is for her to know that I care."
    mc "If you have it in you to call yourself selfish, then you have to let me be selfish too."
    mc "No matter what it takes, I'll figure out what needs to change."
    mc "I'll make these feelings go away."
    mc "And if there's anything that you need me to do..."
    mc "Then you'd better tell me."
    mc "I'll get mad if you don't."
    s "..."
    s "I...don't know..."
    s "I don't know..."
    s "I don't know."
    "Gently, Sayori finally puts her arms around me in return."
    s "I don't know anything."
    s "It's all really scary..."
    s "I don't understand any of my feelings, [player]..."
    s "The only time I'm not feeling nothing is when I'm feeling pain."
    s "But..."
    s "Your hugs are so warm..."
    s "...And that's really scary, too."
    scene bg sayori_bedroom
    show sayori 1bv zorder 2 at i11
    with dissolve_cg
    "Sayori lets me go."
    "As she does so, I let her go as well."
    mc "The festival is tomorrow."
    s 1bk "Yeah..."
    mc "It's going to be fun, right?"
    s "Yeah."
    mc "How would you like for me to spend it all with you?"
    s 1bh "U-Um..."
    s "Ah--"
    mc "It's what I want."
    mc "I promise."
    s 1bk "I..."
    s "I think that would be nice, then..."
    mc "Yeah."
    "Sayori wipes her eyes."
    "If I could spend the whole day here, I would."
    mc "Of all days, this has to be the one where I have other plans..."
    mc "Maybe I should cancel--"
    s 1bh "No, don't--!"
    s 1bg "Please don't..."
    s "If you did that...then I really wouldn't forgive you."
    mc "But..."
    mc "It's almost time for [ch4_name] to meet me at my house..."
    mc "At the very least, do you want to come along and help out?"
    mc "It would be fun."
    "To my surprise, Sayori shakes her head."
    s 1bd "I'm sorry."
    s "I don't know if that would be very good for me today."
    s "You understand, right?"
    mc "Ah..."
    mc "It's...kind of hard for me to fully understand."
    mc "But I'm trying my hardest."
    s "It's okay."
    s "Don't worry too much about it."
    s 4ba "I'll see you tomorrow, okay?"
    mc "...Alright."
    mc "I look forward to it."
    scene bg residential_day with wipeleft_scene
    "I say goodbye to Sayori and exit her house."
    "On the way home, I find myself still feeling uneasy."
    "But it's hard for me to keep thinking about it when [ch4_name] is about to come over, too..."
    "I think Sayori is right."
    "I shouldn't be worrying too much, and we're definitely going to have a great time tomorrow."
    "I should just focus on what's ahead of me!"
    call expression "ch4_exclusive_" + ch4_scene
    call ch4_end

    return


label ch4_exclusive_natsuki:
    play music t6 fadeout 2.0
    scene bg house with wipeleft_scene
    "I spend only a few minutes back at home anxiously awaiting Natsuki's arrival."
    "Before I know it, she texts me to let me know she's outside the front door."
    "Without delay, I open the front door to let her in."
    show natsuki 2bj zorder 2 at t11
    mc "..."
    n "'Sup?"
    mc "...Hey."
    "I don't know what I was expecting, but seeing Natsuki in something other than her school uniform totally threw me off."
    "Seeing her in such cute clothes makes the uniform seem totally unfitting in comparison."
    n 4bc "Jeez, don't make it feel so awkward already!"
    n "It's gonna be a long afternoon, so don't be weird just because you're not used to seeing me outside of school."
    n "Anyway, I'm coming in."
    scene bg kitchen
    show natsuki 1bj zorder 2 at t11
    with wipeleft
    mc "I see you brought a lot of stuff..."
    "Natsuki is carrying a large bag that is probably full of baking supplies."
    n 2bj "Well, I didn't want to come all this way to find out that your kitchen isn't equipped for the job."
    n "You bought everything I asked you to, right?"
    mc "Yeah, I did."
    "Yesterday, Natsuki asked me to buy a bunch of ingredients if I didn't already have them at home."
    n 2bl "Good!"
    n "Glad I could count on you to do your part."
    mc "Well...of course."
    "I'm surprised to hear Natsuki suddenly say that, rather than something snarky like she usually does."
    "Could it be that she is a little different outside of school after all?"
    mc "Anyway, let's go to the kitchen..."
    n 2by "What, you're not even gonna offer to take this heavy bag from me?"
    n "Where's your hospitality, [player]?"
    mc "Come on..."
    mc "Since when did I need to be a gentleman?"
    "I grab the bag Natsuki holds out to me."
    mc "Ghk--"
    mc "This is ridiculously heavy--!"
    n 4bz "Ahaha!"
    n "I carried that all the way here."
    n 4bl "Are you impressed?"
    mc "I see now..."
    mc "Yeah, I am impressed, Natsuki."
    mc "It seems like I always underestimate you."
    n 4by "Ehehe~"
    n "It's because I'm so small, isn't it?"
    n 4ba "You jerk."
    "Natsuki hits a fist into my chest."
    mc "Hey, hey."
    mc "Your size has nothing to do with it."
    mc "Do you really hate being small that much?"
    n 1bk "Eh?"
    n "Um..."
    n 1bc "It's not like I hate it..."
    n "I mean, sometimes I like proving people wrong when they only think I'm worth my size."
    n 1ba "It's fun when I get to be small and also better than other people."
    n "But..."
    n 5bw "...Jeez, never mind!"
    n "What are you making me say?"
    n 5bq "Don't think you can make me talk about weird things just because we're not at school!"
    n "Are we getting started, or what? There's a lot of stuff I gotta teach you."
    mc "Ahaha."
    n 5bn "What??"
    mc "That's a little bit more like you."
    mc "You're more fun when you just speak your mind like that."
    n 1bm "H-Hey!"
    n "Now you {i}are{/i} treating me like a kid!"
    n "I was just trying to be a little nicer to you, you know."
    n 1br "And just because I don't have a mature and sexy figure like Yuri doesn't mean you should treat me like--"
    n 1bo "A-Ah--"
    "Natsuki catches her words, and her face turns red."
    mc "Natsuki..."
    n 1bp "Forget it!"
    n "I didn't say anything!"
    mc "I should apologize."
    n 1bh "Eh?"
    mc "I appreciate that you were trying to be nicer."
    mc "I should have been a little more considerate, too."
    mc "But also..."
    mc "If that's what you're thinking, then you should know that there are tons of guys who are into body types like yours."
    n 1bq "Ah..."
    n "How would...you know that, anyway?"
    mc "Just trust me on this one."
    n "..."
    n 5bx "...Gross."
    mc "Hey!"
    mc "Was that to me?"
    n 5bw "Who else?"
    mc "Man..."
    mc "Let's just get started already."
    n 2bl "Ahaha!"
    n "You get all sour when a girl calls you gross."
    n 2bd "I finally found your weakness, [player]."
    "Natsuki smiles deviously."
    mc "Please spare me..."
    "Well, if Natsuki decides to dish out more insults like that, there's no way I'm not fighting back."
    "But she's satisfied enough for now, finally starting to pull things out of her bag so we can get started."

    scene bg kitchen
    with wipeleft_scene
    "Before long, the whole kitchen is a mess."
    "Spoons, dirty bowls, flour, spilled fluid, and plastic bags are strewn about every countertop."
    "The mixer isn't big enough to make all the batter at once, so we've had to do it several times."
    "Meanwhile, Natsuki is babysitting all of my movements to make sure I don't mess up her precious baking."
    show natsuki 2bk zorder 2 at t11
    n "[player], where did you put the food coloring?"
    n "The batter's going in the oven soon, so I need to fill the trays."
    mc "I think it's still in the bag next to the table."
    mc "What are you using it for?"
    n 4bl "To color the batter, of course!"
    n 4bj "I'm making each tray a different color."
    n "That way, even if the flavors aren't different, everyone can still pick their favorite."
    mc "Ah, that's a cute idea."
    mc "Are we doing anything like that with the icing?"
    n 4bk "Do you want to?"
    mc "Ah..."
    mc "You're asking me?"
    mc "I don't really have a preference, so..."
    n 1bm "Come on..."
    n "You're not putting any heart into this at all!"
    n "Can't you at least try to have fun?"
    mc "I'm having fun..."
    "I'm not really sure what Natsuki is trying to get out of me."
    "Meanwhile, I see her separate the batter into smaller bowls and put a few drops of food coloring into each."
    mc "Ah, that does look pretty cool."
    n 2bj "See?"
    n "It's not like baking is just about following instructions."
    n "The presentation is where you get to be creative and have the most fun."
    n "It's a million times more worth it in the end if just looking at it makes everyone's eyes lighten up."
    mc "Like the ones you made on my first day, huh?"
    "I recall Natsuki proudly presenting her cat-shaped cupcakes, and Sayori and Monika's delighted expressions."
    "I wonder if I can make Natsuki proud like that, too."
    mc "Yeah..."
    mc "Maybe I will use the food coloring, then."
    n "Sounds like you're starting to understand."
    n "Just make sure you completely finish mixing the icing before you mess with the food coloring."
    mc "Yeah, it's getting there."
    "We were using the electric mixer for the batter, so I got stuck with a whisk and a huge bowl for the icing."
    n 4bc "Eh?"
    n "The icing's still all lumpy!"
    n "Are you even trying?"
    mc "Well, yeah..."
    mc "It'll just take a little longer."
    n 4bg "Jeez, I'll be here all night if you do it like that."
    n "Here, look."
    "Natsuki grabs the whisk from me and uses her other hand to tilt the bowl back."
    n 4be "You really need to...beat...the crap out of it!"
    "After a few seconds, the consistency of the icing has already improved."
    n 4ba "See?"
    "As if to emphasize, Natsuki sticks a finger in the icing and pops it in her mouth."
    "I reluctantly start to do the same."
    n 1bh "Hey!"
    "Natsuki suddenly grabs my wrist."
    n 4bh "I don't want {i}your{/i} gross fingers in my icing."
    mc "Your icing, eh?"
    mc "Are you forgetting who did all the work?"
    "I start to fight back, trying to inch my finger toward the bowl."
    n 4by "Don't make me beat the crap out of you next!"
    mc "I'd like to see you try!"
    "I push harder, just enough for my finger to reach the icing."
    "I triumphantly scoop some with my finger just as Natsuki tugs with all her might."
    mc "Ah--!"
    "The force of Natsuki pulling me causes me to stumble, making her stumble in turn."
    n 1bx "Gross!"
    n "You got it on my face!"
    mc "Whose fault is that?!"
    "There's a big glob of icing on Natsuki's cheek."
    n 1bw "Nnn--"
    "She tries to reach it with her tongue, but it's too far away."
    n 1br "Jeez..."
    n "You know what?"
    n 4bd "Take this!"
    "Natsuki instead wipes it off with her finger before shoving her finger toward my own face."
    mc "You wish--!"
    "I'm faster."
    "I grab her wrist with my hand before it reaches my face."
    "Natsuki tries to use her other hand to fight back, but I grab that one as well."
    $ persistent.clear[4] = True
    $ renpy.save_persistent()
    scene n_cg3_base
    show n_cg3_exp1
    show n_cg3_cake
    with dissolve_cg
    n "Ahahaha! Stop!"
    mc "Not until you apologize for calling me gross!"
    n "Fine, fine!"
    n "I'm sorry for calling you gross."
    n "You know I don't mean it."
    n "It's just fun seeing you react to it."
    n "...You do that to me all the time, you know!"
    n "Saying dumb things just to get a reaction out of me."
    n "You really shouldn't tease girls like that."
    mc "Is that so?"
    mc "In that case, I probably shouldn't do this, either..."
    show n_cg3_cake at cgfade
    hide n_cg3_cake
    "I take Natsuki's finger and put it in my mouth, licking off the icing."
    show n_cg3_exp1 at cgfade
    show n_cg3_exp2 at cgfade
    hide n_cg3_exp1
    n "W-W-What--?"
    n "D-Did you seriously just--"
    n "A-Ah--"
    "Natsuki is so surprised that she can't even figure out how to get mad at me."
    "Her face is entirely red."
    hide n_cg3_exp2
    n "[player]..."
    n "You really shouldn't do that kind of thing to girls...unless you really like them..."
    n "You know that...right?"
    mc "..."
    "What kind of question is she asking me, just like that?"
    "How did the mood turn to this so quickly?"
    mc "I..."
    "Natsuki gazes at me in silence."
    "I notice her shallow breaths."
    "Why am I starting to feel dizzy...?"
    n "Eh?!"
    scene bg kitchen with dissolve_cg
    "Out of nowhere, the fire alarm starts going off."
    "Natsuki rushes over to the oven."
    mc "Is something burning?"
    mc "I thought you didn't put the cupcakes in yet."
    show natsuki 1bw zorder 2 at t11
    n "{i}*Cough*{/i}"
    n "No wonder..."
    n 1bb "You left a dirty tray in here, dummy!"
    n "How could you make a mistake like that?"
    mc "You should have checked before turning the oven on!"
    n 1bs "Don't blame me for your mistakes!"
    n "Jeez..."
    "Natsuki uses an oven mitt to grab the blackened tray out of the oven."
    "She sets it on top of the stove."
    "In another moment, the fire alarm stops."
    n 1bq "Anyway..."
    n "I'm...putting them in the oven now."
    mc "Yeah..."
    "The tension from the moment before still lingers over our heads."
    "But the moment has already been lost."
    "I watch as Natsuki slides the cupcake trays into the oven."
    "Then, I reluctantly pick up the whisk and continue with the icing, like nothing ever happened."

    scene bg kitchen
    show natsuki 4bz zorder 2 at t11
    with wipeleft_scene
    n "Ahh, that smells so good!"
    "The cupcakes are ready to be pulled out of the oven."
    "As soon as Natsuki opens the oven door, a blast of sweet-smelling warm air fills the room."
    n 4bl "Look at how cute they all look!"
    "She proudly shows off the different-colored cupcakes in each of the trays."
    mc "They'll look even better once we add the icing."
    n 2ba "Not like you need to tell {i}me{/i} that!"
    n "I brought decorating stuff, so I hope you can get creative."
    n "Here, scoop the icing into these bags."
    "Natsuki hands me some plastic bags."
    n 2bj "I have these nozzles that will make it look nice and fluffy."
    n "This one can even make flowers!"
    n "We probably won't be using it this time, though."
    mc "What's this one for?"
    "I pick up one of the nozzles that has a much thinner tip than the others."
    n 4bk "That one's really thin, so you can use it to make stripes or other patterns."
    n "But you can also use it to write stuff on a cake."
    n "Like, 'happy birthday!' or whatever."
    mc "Huh, I see..."
    mc "That gives me an idea, actually."
    n "Eh?"
    mc "Well, it's a literature event, right?"
    mc "We could make it more literature-themed by writing a different word on each of the cupcakes."
    mc "It would be fun to see people choose their cupcake based on a word they like."
    n 1bq "Uu..."
    mc "Hm?"
    n "I was kind of expecting you to say something really stupid..."
    n 1bs "But that's actually...a really cute idea, so..."
    mc "Ahaha."
    mc "Maybe I'm getting it from you."
    n 5bh "W-What's that supposed to mean?"
    n "I'm not cute!"
    mc "Come on..."
    mc "We're not at school, nobody's judging."
    mc "You can't dress and act like this and not expect me to think you're cute."
    n 5bs "W-Well..."
    "Natsuki's voice trails off."
    n "Same with you..."
    mc "Eh?"
    mc "Did you say something?"
    n 1bw "N-No, nothing!"
    n "Let's just do the icing!"
    "Natsuki picks up the pace and fastens a nozzle onto each of the bags."
    n 1bh "There's a lot to do, so we shouldn't be wasting time!"
    n "Here, I'll show you how to do it."
    "Without giving me a chance to think about before, Natsuki quickly moves on."
    "She shows me how to apply the icing, and then we each get to work."

    scene bg kitchen with wipeleft_scene
    "When we're finally finished, Natsuki puts them all side by side to admire our work."
    show natsuki 4bl zorder 2 at t11
    n "Look at how pretty they are together!"
    mc "Yeah, they are, aren't they?"
    n 1bm "Uu... I wish I could have one now!"
    mc "Well, there's no reason you can't, right?"
    mc "I don't see any harm in that."
    n 1bc "Well, yeah, but..."
    n "My dad's making dinner tonight, so I really need to save my appetite."
    mc "Ahaha."
    mc "Sayori's the exact opposite in that regard."
    mc "If she was here, we'd probably be down ten cupcakes already."
    mc "And she would still eat dinner."
    n 4bg "Come on, that's just unhealthy!"
    n 4bs "Besides, when my dad cooks, I need to eat as much of it as I can..."
    n 4bq "...Well, anyway!"
    n 4bc "I was hoping we would have time for manga, but I need to be home for dinner..."
    mc "Ah, already?"
    mc "That's a shame."
    n 1bg "It's your fault for working so slowly!"
    n "You should have thought about that."
    n "It's not like you'll always have this chance."
    mc "Man..."
    "As usual, Natsuki places the blame on me."
    n 2bk "You can bring the cupcakes tomorrow, right?"
    n "If you and Sayori each carry some, then you can probably do it in one trip."
    mc "Yeah, I can do that."
    mc "And don't worry, I won't let her eat any."
    n 2ba "Ahaha."
    n "I wish she would listen to me the way she listens to you."
    mc "Ah..."
    mc "Yeah."
    show natsuki zorder 1 at thide
    hide natsuki
    "I again think back to the conversation I had with Sayori earlier today."
    "I felt so helpless."
    "Sayori always does listen to me, but at that point it felt like she couldn't listen to me at all."
    show natsuki 4bl zorder 2 at t11
    n "Okay, I'm all packed up."
    n "Good work today!"
    mc "You too."
    mc "I'll walk you out...I guess."

    scene bg house with wipeleft_scene
    "Just like that, Natsuki is already about to leave."
    "It feels like the afternoon went by in a flash."
    "More than that..."
    "Did I even take the opportunity to get closer to her, like I wanted?"
    show natsuki 1bh zorder 2 at t11
    n "Well..."
    n "I guess I'll be off, then..."
    n 1bq "Thanks for all the help and everything..."
    n "I'll see you tomorrow."
    mc "Wait, Natsuki."
    n 1bh "Eh?"
    mc "What you said before...about not always having this chance."
    mc "It doesn't have to be that way at all!"
    mc "I had fun today."
    mc "You showed me how fun baking can be, like you wanted."
    mc "But aside from that..."
    mc "You can come over anytime, okay?"
    mc "I think that if possible, I'd like to spend more time like this."
    mc "If you want to read manga, or go out somewhere--"
    n 1bm "Um--"
    n "Do you...really mean that?"
    "Natsuki looks at me tensely, like she's trying to hide her expression."
    mc "Yeah."
    mc "I want to spend more time with you."
    n 1bq "[player]..."
    n "I thought you only cared about getting this done..."
    n 1br "Uu..."
    n 1bn "I'm sorry I had to leave so early today."
    n "I really didn't want to!"
    n "I would really...stay here longer if I could."
    n "I feel the same way as you, so..."
    stop music fadeout 2.0
    show natsuki 1bi at face with dissolve
    "Natsuki suddenly gets closer to me."
    mc "Wait, Natsuki--"
    "Standing inches from me, Natsuki looks up at me."
    "I feel her fingers gently clutch at the sides of my shirt, as if holding onto me."
    "Her rose-colored cheeks and matching eyes fill my vision, along with her slightly-parted lips."
    "What is happening...?"
    "My head starts to go dizzy as I feel her soft breaths against me."
    n 1bh "I've felt it..."
    n "For a while now..."
    n 1bo "--!!"
    show natsuki zorder 2 at t11
    "Natsuki suddenly jumps back."
    n "S-Sayori?!"
    mc "Eh?!"
    show natsuki zorder 2 at t22
    show sayori 1bl zorder 3 at f21
    s "Ah..."
    s "H-Hi, [player]..."
    mc "Sayori--!"
    mc "Just now, we weren't--"
    s 1bq "Ehehe~"
    s "It's okay, [player]."
    s 1ba "I just stopped by to say hi~"
    show sayori zorder 2 at t21
    show natsuki zorder 3 at f22
    n 5bq "A-Ah..."
    n "Well..."
    n 5bw "Y-You should have come a little earlier!"
    n "I'm already on my way out, so..."
    show natsuki zorder 2 at t22
    show sayori zorder 3 at f21
    s 1bh "Aw, really?"
    s "That's too bad..."
    show sayori zorder 2 at t21
    show natsuki zorder 3 at f22
    n 2bq "Yeah, well..."
    n "I'll still see you at the festival tomorrow, so it's fine."
    n 2bb "Just don't eat any cupcakes before then!"
    n "Anyway, later!"
    show natsuki at lhide
    hide natsuki
    "Clearly flustered, Natsuki hurries off, and Sayori waves goodbye."
    return

label ch4_exclusive_yuri:
    play music t6 fadeout 2.0
    scene bg house with wipeleft_scene
    "As I approach my house, I see something that makes me feel a moment of panic."
    mc "Yuri--?"
    show yuri 2bq zorder 2 at t11
    y "Ah..."
    y "Thank goodness..."
    mc "You're a little early..."
    mc "I'm sorry I wasn't home yet!"
    mc "Were you waiting for a long time?"
    y 1bf "No, I just got here."
    y 1bh "But I started to get really nervous when nobody answered the doorbell..."
    mc "You always could have texted me."
    mc "If I had known, I would have reassured you and hurried more on my way home."
    y 2bv "Ah...I suppose that's true..."
    y "I didn't think of that...for some reason."
    "It should be common sense to do that, but I decide to ignore it."
    mc "Anyway...let's go inside."
    mc "I see you brought a lot of stuff with you."
    y 1ba "That's right."
    y "And did you manage to find everything I asked you to buy as well?"
    mc "Yeah, pretty much."
    mc "At least, I hope I got everything right."
    y "I'm sure it will be fine."
    scene bg bedroom with wipeleft
    "I take Yuri to my room."
    "The first thing she does is glance around curiously, which makes me feel anxious."
    show yuri 2bm zorder 2 at t11
    y "It's so clean..."
    mc "Ahaha..."
    mc "I cleaned it before you came over, so..."
    y 2ba "That's very considerate of you to do."
    mc "Ah, no..."
    mc "I would be really embarrassed for my room to be a mess while you were here."
    y 1ba "Hmm..."
    y "Well, I do enjoy cleaning..."
    y "I would have gladly helped you clean."
    mc "Ah--"
    mc "That would be even more embarrassing!"
    show yuri 1be
    mc "Wait, don't look in there--!"
    "I snatch Yuri's wrist, which was in the process of opening a desk drawer of mine."
    y 3bn "A-Ah..."
    y "I'm sorry...!"
    y 4bb "I wasn't thinking for some reason..."
    y "I was just spacing out!"
    mc "It's fine, it's fine..."
    "I let go of Yuri's wrist."
    show yuri 1bl
    "She puts both of her hands firmly in her lap, as if making sure she's keeping track of them."
    mc "So, um..."
    mc "Should we...get started?"
    y 2bu "Ah..."
    y "Yes..."
    y 2bf "Um, I have a few things planned that you can help with..."
    y "Decorations and other atmospheric enhancements."
    mc "Atmospheric enhancements...?"
    y 1ba "You know..."
    y "Mood lighting, aromatherapy candles..."
    mc "Oh, wow."
    mc "I didn't know you planned on taking it that far."
    y 1bc "Of course."
    y "I want to help take our guests to a faraway place."
    y 1ba "Although many will stop by just out of curiosity..."
    y 1bj "And for...cupcakes, I guess..."
    y 1ba "I'm determined to provide an experience that will leave them wanting more."
    mc "That's great."
    mc "It's easy to forget that you're a pretty intense person."
    y 1bt "Ah--"
    y 2bt "Intense...?"
    mc "I guess that's the best way to put it."
    y "Is that...a bad thing?"
    mc "No, not at all."
    mc "It's something that I like about you, actually."
    y 3bu "I-Is that so...?"
    y "That makes me feel relieved..."
    y "And kind of happy..."
    mc "Yeah, no need to be so anxious."
    mc "You can relax a little."
    y 3bl "Relax..."
    y 1bf "I brought some things for relaxation."
    y "I was going to use them during the poetry event..."
    mc "Oh yeah? Like what?"
    y "Let's see..."
    "Yuri rummages through her bag."
    "She pulls out a few candles and a wooden cylinder-shaped object."
    y "I did some shopping on the way here, so I happen to have these in my bag."
    y "I planned to cover the windows in black paper and use the candles to light the room."
    y 1ba "I think that would be amazing, don't you?"
    mc "Yeah, that would be really neat."
    mc "What's that wooden thing, though?"
    y 1bf "Oh, this?"
    y "It's a diffuser for essential oils."
    y "How familiar are you with aromatherapy?"
    mc "Not familiar at all..."
    y 1ba "Ah, is that so?"
    y "It's one of my favorite contributors to a positive atmosphere."
    y "Depending on the oils or herbs you choose, you can change the mood of the air itself."
    y "You can even feel it permeate through your body."
    y 3bm "Relaxation, positive energy, romance, reflection..."
    y "It's almost like magic."
    show yuri 3ba
    "Yuri takes the cylinder and pushes a switch on the bottom."
    "In just a moment, a thin ray of vapor begins to spout through a small hole on the top."
    mc "Wow, that smells wonderful."
    mc "What kind of mood is that one for?"
    y 1ba "This is a Jasmine essential oil."
    y "It smells a little sweet and flowery, right?"
    mc "Yeah, that's a good way to describe it."
    y 1bb "I chose Jasmine for the event because it provides more than relaxation."
    y "Jasmine enhances your emotions and helps you feel them flow through your body."
    y 1bu "You feel warmer, and your heart pounds more heavily."
    y 1ba "Don't you think that will be perfect for sharing our poems?"
    mc "It does sound suitable..."
    mc "But you seem to know a lot about this, so I'll trust your opinion with anything."
    show yuri 1bc
    "Yuri smiles gently, clearly enjoying herself."
    "She again reaches into her bag and pulls out several spools of thin ribbon."
    show yuri 1ba
    mc "What are those for?"
    y 1bf "Well..."
    y "Did you purchase the origami paper I asked you to get?"
    mc "Yeah, I have it over here..."
    y "We won't be using the paper for folding origami."
    y "What I'd like to do is write a different word on each paper."
    y "We'll need about a hundred of them."
    mc "Oh yeah?"
    mc "What will those be used for?"
    y 2bf "Well, I'm going to cut pieces of ribbon to hang from the doorway of the classroom."
    y "Then, we can fasten the paper onto the ribbons to create a doorway curtain."
    y 2bm "Wouldn't that be beautiful?"
    y "It would also catch the eye of those passing by the room..."
    y 2ba "It may attract some to peek inside."
    mc "That's really creative!"
    mc "I had no idea you'd be so good at this, Yuri."
    y 4ba "Is...that so?"
    y "Well, I suppose I do get a little intense...as you'd put it."
    y 3bu "Uhuhu."
    "Yuri giggles with red cheeks."
    "Is it just me, or is she more relaxed when it's just the two of us?"
    "Or maybe it's the excitement she feels from sharing something that she enjoys."
    y 1ba "Here's a marker, [player]."
    y "You can write any characters you want."
    y "I'll help you once I finish cutting the ribbons."
    mc "Ah, alright."
    "Sitting on the floor together, the two of us get to work."
    "I carefully draw a different character on each paper, doing my best to manage my bad handwriting."
    "Yuri unravels a long strand of red ribbon to her desired length."
    "Then, she reaches into her bag once more and pulls out a pocket knife."
    mc "Eh...?"
    "The knife is strangely beautiful."
    "The silver handle has an intricate pattern of waves etched into it."
    "The blade itself is gently tinted blue."
    mc "That's no ordinary pocket knife..."
    mc "It looks really fancy."
    y 4bb "A-Ah..."
    y "Well..."
    "Embarrassed, Yuri looks away."
    mc "What is it?"
    y "You're going to think it's weird..."
    mc "Yuri, whatever it is, I have no reason to judge."
    mc "To each their own, you know?"
    y "If you promise you won't be weirded out..."
    mc "Yeah, I promise."
    y 2bi "Alright..."
    y "The thing is, I'm kind of into knives..."
    y "They're just...so pretty..."
    y 2bv "I-I can't help it!"
    y "I don't know what it is..."
    y "The combination of craftsmanship and feeling of danger, maybe..."
    y 4bb "Uu, what am I saying...?"
    y "Please don't think I'm weird for this..."
    mc "Ahaha."
    y "You're laughing at me..."
    mc "No, I'm not laughing at you."
    mc "It's just funny how nervous you got about sharing."
    mc "It's...well, it's an interesting thing to be into, I guess."
    mc "But I think it kind of suits you."
    y 2bt "Suits me...?"
    mc "Yeah... It's kind of intense. Ahaha."
    mc "Besides, it's a really cool-looking knife, I can't deny that."
    y 2bu "It is, isn't it...?"
    "Yuri relaxes her expression once again."
    y 1ba "Would you like to hold it?"
    mc "Sure, I'll check it out."
    "Yuri carefully hands me the knife, with the handle facing me."
    "I take it and turn it around in my hands."
    "It feels heavy, and extremely solid."
    "Where do you even get a knife like this...?"
    "Curious of its sharpness, I feel the point of the knife with my index finger."
    mc "Ow--!"
    y 3bn "[player]--!!"
    y "Why did you do that?!"
    mc "I didn't expect it to be that sharp...!"
    mc "I barely touched it at all."
    y "I-It's my fault!"
    y 3bo "I should have warned you..."
    y "This knife is extremely sharp..."
    y "It can cut through skin like it's paper."
    y 2bv "Oh no..."
    "A small drop of blood trickles down the side of my finger."
    "Yuri takes my hand and gives the wound a closer look."
    y 2bt "Ah..."
    "She stares at it and noticeably fidgets."
    mc "If you're squeamish, I'll go wash it off now--"
    mc "A-Ah!"
    "Without warning, Yuri puts my finger in her mouth and licks the wound."
    "I feel her tongue curl around my finger."
    "Startled, I instinctively pull my hand back."
    y "O-Oh..."
    y 3bo "P-Please forgive me!"
    y "I wasn't thinking!"
    y 4bc "I..."
    "Yuri lowers her head, her face burning up."
    mc "Yuri..."
    y "That's the most embarrassing thing I've ever done..."
    y "How could I do something like that??"
    y "I'm sorry, I'm sorry..."
    mc "Ah..."
    "Sure, it was a little weird, and it took me by surprise..."
    "But I guess she was just trying to help, right...?"
    mc "Yuri, I think you're overreacting a little..."
    y "Uuuh..."
    "She doesn't lift her head."
    "What if she doesn't recover from this for the rest of the afternoon?"
    mc "Alright, you know what..."
    "This might be a stupid thing to do, but I do it anyway."
    "I take Yuri's hand and lick her index finger in return."
    show yuri 3bn at h11
    y "[player]--!!"
    y "D-Did you really just do that?"
    mc "N-Now we're even..."
    y 3bv "..."
    "Yuri just looks at me like I did something wrong."
    mc "Ahaha..."
    mc "I knew that would be a bad idea..."
    "If not for the sweet aroma of the Jasmine oil, the air would be extremely heavy right now."
    y 1bu "You're so weird, [player]."
    "Yuri giggles shyly."
    mc "Eh...?"
    "Yuri calling {i}me{/i} weird?"
    "I have no response to that..."
    y 1bf "Where do you keep your bandages?"
    mc "Ah..."
    mc "I don't think I need one, actually."
    mc "It was a tiny cut."
    mc "Look, it already stopped bleeding."
    y 1ba "I see..."
    y "That's relieving."
    "The tension is quickly lifted."
    "We each resume our respective activities."
    "I watch Yuri's knife cut through the ribbon like it's nothing but air."
    "Meanwhile, I continue to make progress on the paper."

    scene bg bedroom with wipeleft_scene
    "After we finish attaching the paper to the ribbons, we lay them all out side by side."
    "It looks better than I expected and will be very effective as a door curtain."
    mc "It looks great."
    mc "Good thinking coming up with this, Yuri."
    show yuri 1bq zorder 2 at t11
    y "Ah, thanks..."
    y "It's just something I saw online, really."
    y 1ba "Are you ready to move onto the next task?"
    mc "Yeah, let's do it."
    mc "What do you have in mind?"
    y "I'd like to create a banner."
    y "That's why I asked you to buy the paint tablets."
    mc "Ah, that's right."
    "One of the items Yuri had asked me to buy was a kit of watercolor paint tablets."
    y 1bf "We'll need about six cups of water to put each of the tablets in."
    y "Do you mind fetching those for us?"
    mc "Of course not."
    mc "Six cups of water..."
    mc "I'll be right back in a minute."
    y 1ba "Thank you very much."
    y 2bf "Oh, and just a little bit of water is okay."
    y "If you fill the cups too much, it will be too diluted."

    scene bg bedroom with wipeleft_scene
    "Taking Yuri's advice, I decide to use small plastic bathroom cups rather than full-sized glasses."
    "I put them on a plate to catch any paint that drips, then bring it back into my room."
    mc "Yuri?"
    show yuri 1bd zorder 2 at t11
    y "Yes?"
    "I come in to see Yuri quickly unrolling her sleeve, pulling it back over her arm."
    mc "Ah, nothing..."
    mc "Your face is a little red."
    mc "Is it too hot in here, or anything?"
    y 3bq "Ah--"
    y "No, not at all!"
    y "There's nothing wrong, so..."
    y "Let's mix the paint."
    "Yuri hurriedly dismisses me and takes it upon herself to unwrap the tablets, dropping them into the cups."
    y 1ba "So..."
    y "I thought we would do something simple that would look very nice."
    y "I'd like to paint a gradient across the banner..."
    y "Starting with the colors for a sunrise, then daytime, then sunset and nighttime."
    y "Once it dries, I'll write an inspirational quote across the banner."
    y "We can hang it on the wall behind the podium at the front of the classroom."
    mc "Ah, neat."
    mc "What are you going to write?"
    y 2bm "Well..."
    y "...It will be more fun to surprise you."
    "Yuri smiles at me."
    mc "If you say so..."
    show yuri zorder 1 at thide
    hide yuri
    "After rolling out the banner, Yuri and I kneel on opposite sides so we don't get in the way of each other."
    "Yuri uses a brush and adds a few dots of different colors across the banner to serve as a color guide when we paint."
    mc "This kind of reminds me of elementary school..."
    "Painting on a banner with watercolors feels a lot like the art class projects we had back then."
    "It's relaxing."
    show yuri 2bt zorder 2 at t11
    y "Ah..."
    y "I'm sorry if this feels too childish...!"
    mc "No, I didn't mean that at all."
    mc "It's kind of fun, you know?"
    y 1bs "...Yeah."
    y "It is fun."
    y "I'm glad you feel that way, too."
    "Yuri stops painting for a moment, thinking to herself."
    y 2bl "For me..."
    y "I don't need to go out and do crazy things to have fun."
    y "In fact, I usually don't even want to."
    y 2bf "I just like when I can spend time with one other person..."
    y "Even if it's something simple, like reading - it doesn't even matter if we don't talk much."
    y 2ba "Just having a friend next to me makes things feel a little bit nicer."
    y "I think that's all it takes for me to be happy."
    mc "Is that so...?"
    "Even if Yuri and I are quite different, I can understand where she's coming from."
    "I feel that way about things like anime and games, where simply sharing the experience with someone can make me happy."
    mc "I think I feel the same way."
    "Yuri smiles gently."
    y 1bm "I knew you'd understand..."
    "Yuri leans over the banner to grab an unused paintbrush."
    "But I move at the same time, causing my head to bump into hers."
    y 3bn "Kya--!"
    mc "S-Sorry!"
    "Yuri reels back, and I quickly lift my hands in surprise."
    mc "Are you hurt?"
    y 2bv "N-No, I'm not hurt."
    y "It just startled me...that's all."
    y "Sorry, I should have asked you to get it for me..."
    mc "It's not your fault."
    mc "Ah, your face..."
    "There are droplets of paint on Yuri's face and neck."
    y 2bt "Is there something on my face?"
    mc "Yeah, I accidentally got paint on you..."
    mc "Sorry, it's totally my fault!"
    mc "I'll get a towel right away."
    show yuri zorder 1 at thide
    hide yuri
    "I rush out and fetch a small towel, then I dampen it with hot water."
    "I return to my room and kneel back down in front of her."
    $ persistent.clear[5] = True
    $ renpy.save_persistent()
    scene y_cg3_base with dissolve_cg
    mc "Here..."
    "I pat down Yuri's face and neck with the towel."
    show y_cg3_exp1 at cgfade
    y "Ah--"
    mc "Is something wrong?"
    y "It's hot...I just didn't expect it."
    mc "Sorry..."
    mc "I didn't want to use cold water."
    "Having finished, I start to retract my hand."
    "But Yuri suddenly holds my wrist."
    hide y_cg3_exp1
    y "Wait--"
    mc "Eh?"
    show y_cg3_exp1 at cgfade
    y "Just...for a little longer."
    y "It feels really nice..."
    mc "Ah..."
    "I keep my hand still against Yuri's neck."
    hide y_cg3_exp1
    "She looks into my eyes."
    "It's an intense expression that I recognize from when she reads her books..."
    "Almost as if she's lost in a daze, enveloped by her own thoughts."
    "She breathes gently, half through slightly-parted lips."
    "What is happening...?"
    "Is it the aroma of the Jasmine oil giving me this dizzy feeling?"
    "Yuri's gentle fingers, wrapped around my wrist, send a tingling sensation through my arm."
    "And suddenly, her face seems to be much closer to mine than it was just a moment ago..."
    y "Ah..."
    "Yuri slowly pulls away."
    y "Sorry..."
    y "I've been feeling a little light-headed today."
    y "I didn't mean to space out..."
    mc "I-It's fine..."
    scene bedroom with dissolve_cg
    "The moment is over as soon as it began."
    "Yuri picks up her brush again."
    "But her movements seem clumsier, like she's unable to focus."
    "I remain silent, forced to ignore the event that just transpired."
    "I hesitantly retrieve my own brush and continue following Yuri's example."

    scene bedroom with wipeleft_scene
    mc "That should do it..."
    "I finish filling the night sky with white dots that look like stars."
    "Looking at the banner as a whole, it's very pretty and natural-looking."
    show yuri 1ba zorder 2 at t11
    y "I think it came out better than I expected."
    y "I'm really happy with the results."
    mc "Yeah, me too."
    mc "Are you going to add the lettering now?"
    y 1bf "Ah, not yet..."
    y "It needs to dry first."
    mc "That's true, but won't that take a while?"
    y 2bh "Well..."
    y "Perhaps it would be best to leave it here, then have you bring it in the morning."
    y 2bf "I can do the lettering in the classroom before our event starts."
    y "Is that okay?"
    mc "That's totally fine."
    y 1ba "Wonderful."
    y "In that case..."
    y "I don't think there's anything more for us to do here."
    mc "Phew."
    y 1bc "Ahaha."
    y "You say that like you're glad it's over."
    y 1ba "Was I wrong to assume that you were at least enjoying yourself a little bit?"
    mc "Ah, no, it's not that."
    mc "I'm just glad that we managed to get everything done."
    y 2ba "I see."
    y "I am, too."
    y "I was a little concerned about time..."
    y "I need to start making dinner soon."
    mc "Ah..."
    mc "So you don't have any time left?"
    "I was secretly hoping we would have extra time after finishing the work..."
    y 2bl "Well..."
    y "..."
    "Yuri thinks to herself."
    y 3bv "I-I think it would be too irresponsible of me to wait much longer..."
    y "I'm sorry!"
    y "I was hoping there would be more time as well..."
    mc "It's probably my fault."
    mc "Sorry for being such a slow worker."
    y 1bt "No, it's not your fault at all."
    y "And...the important thing is that we got everything done, right?"
    mc "Yeah..."
    y 1bu "So..."
    y "I shouldn't be disappointed...or anything."
    "Gathering all her things, Yuri seems to look a little downcast."
    "I understand why."
    "It sounded like she rarely gets the opportunity to spend time with friends in a relaxed environment."
    "But that doesn't mean this is the last time it can happen..."

    scene bg house with wipeleft_scene
    "Once Yuri packs up, I walk her out the front door."
    show yuri 1ba zorder 2 at t11
    y "Thank you very much for having me today."
    mc "No problem, I'm glad I was able to help."
    mc "Just let me know if there's anything else you need me to bring tomorrow."
    y "I will."
    y 1bu "Well, then..."
    "Yuri fidgets."
    y 2bu "I guess...I'll see you tomorrow."
    mc "Wait--"
    show yuri 2bt
    "I kind of say that without thinking."
    mc "About today..."
    mc "It's fine that we didn't have as much time as we wanted."
    mc "Because we can do this again."
    mc "Whenever you want, you can come over, or we can go out somewhere--"
    mc "Ah, I forgot you don't like going out much--"
    show yuri 2bs
    "As I stumble over my words, Yuri simply smiles bashfully."
    mc "Anyway..."
    mc "You know what I'm trying to say, so..."
    y 1bs "You're very thoughtful, [player]."
    "Yuri takes a step closer to me, then briefly squeezes my hand."
    show yuri 2bs at face(y=600) with dissolve
    stop music fadeout 2.0
    y "I kind of like that about you..."
    mc "Well..."
    "How am I supposed to respond to that?"
    "But I don't even get a chance to, as Yuri suddenly pulls back."
    show yuri 3bn zorder 2 at t11
    y "S-Sayori--?"
    mc "Eh?!"
    show sayori 1bl zorder 3 at f21
    show yuri zorder 2 at t22
    s "Ah..."
    s "H-Hi, [player]..."
    mc "Sayori--!"
    mc "Just now, we weren't--"
    s 1bq "Ehehe~"
    s "It's okay, [player]."
    s 1ba "I just stopped by to say hi~"
    show sayori zorder 2 at t21
    show yuri zorder 3 at f22
    y 3bq "U-Um..."
    y "Well, it's nice to see you..."
    y 3bv "I'm sorry, but I'm already on my way to leave!"
    show yuri zorder 2 at t22
    show sayori zorder 3 at f21
    s 1bh "Aw, really?"
    s "That's too bad..."
    show sayori zorder 2 at t21
    show yuri zorder 3 at f22
    y 2bt "I'm sorry..."
    y "But we'll all be together at the festival tomorrow, so..."
    y "So that's fine, right?"
    show yuri zorder 2 at t22
    show sayori zorder 3 at f21
    s 4bq "Of course!"
    "Sayori beams."
    show sayori 4ba
    show sayori zorder 2 at t21
    show yuri zorder 3 at f22
    y 4bc "Y-Yeah, so..."
    y "I'll see you tomorrow!"
    show yuri at lhide
    hide yuri
    "Clearly embarrassed, Yuri hurries off."
    "Sayori waves goodbye after her."
    return



label ch4_end:
    play music t10 fadeout 2.0
    show sayori 1ba zorder 2 at t11
    mc "Sayori--"
    mc "I thought you didn't want to come over today!"
    s 2bl "Ahaha, well..."
    s "I tried staying in my room..."
    s "But my imagination was being really mean to me..."
    s 1by "So I had to come here and see it for myself."
    mc "See what?"
    mc "What are you talking about?"
    s "You know..."
    s "How much fun you were having with [ch4_name]."
    s "And how close you got to her."
    s 1bt "It makes me...really happy..."
    s "That you've made such good friends."
    s "That's all that matters to me."
    "Tears start to fall down Sayori's face."
    s 4bv "That's all that matters to me--!"
    s "Why am I feeling this way, [player]?"
    s "I'm supposed to be happy for you."
    s 4bw "Why does it feel like my heart is splitting in half?"
    s "It hurts so much..."
    s "Everything hurts so much..."
    s "This would be so much better if I could just disappear!"
    mc "Sayori, don't say that!"
    s 1bw "It's true, [player]!"
    s "If I wasn't here, then you wouldn't have to waste your sympathy on me!"
    s "You wouldn't have to put up with me being selfish!"
    s 1bv "Monika was right..."
    s "I should just..."
    mc "Monika...?"
    mc "Monika was right about what?"
    s "..."
    mc "Sayori..."
    mc "What I said before is true."
    mc "I'm not going to let this continue."
    mc "Caring about you like this isn't the burden your mind is making it out to be."
    mc "It's something that makes me happy."
    mc "It's something that I wouldn't trade for anything else."
    mc "So, even if it takes an entire lifetime..."
    mc "I'm going to be by your side until you don't feel any more pain."
    s 1bk "B-But..."
    "Sayori looks away."
    "I put a hand on her shoulder to reassure her."
    s "I'm scared, [player]..."
    s "I'm really scared..."
    mc "What are you scared of, Sayori?"
    s "I'm scared that..."
    s "That I might like you more than you like me..."
    mc "Sayori...?"
    s 1bu "It's true, isn't it?"
    s "I was weak and started to like you too much..."
    s "I did this to myself."
    s "[player]..."
    s 4bw "I like you so much that I want to die!"
    s "That's how I feel!"
    s 2bv "And...and..."
    mc "That's enough, Sayori..."
    mc "I don't want you to hurt anymore."
    "I slide my hand down Sayori's arm and squeeze her hand in my own."
    mc "Do you remember how I said I always know what's best for you?"
    mc "Do you still believe me?"
    "Wordlessly, Sayori nods."
    mc "Even if you don't understand all of your own feelings..."
    mc "I know what you need the most right now."
    mc "And that's what I'm going to give to you."
    show black zorder 4 with dissolve_cg

    menu:
        mc "Sayori..."
        "I love you.":

            $ sayori_confess = True
            hide black with dissolve_cg
            call ch4_end_yes
        "You'll always be my dearest friend.":
            $ sayori_confess = False
            hide black with dissolve_cg
            call ch4_end_no

    return

label ch4_end_yes:
    mc "I love you."
    s 1bv "Eh--?"
    mc "Those are my true feelings."
    mc "So...there's no way you could like me more than I like you."
    mc "I should have realized it sooner."
    mc "But spending time with everyone at the club..."
    mc "Making new friends..."
    mc "And having fun with you every day..."
    mc "It helped me realize that you are truly the most important person to me."
    mc "That's why I'll accept any of your burdens."
    mc "As long as we continue like this every day..."
    mc "With you by my side..."
    mc "Then I know we'll both be happy."
    s "[player]..."
    $ persistent.clear[8] = True
    $ renpy.save_persistent()
    scene s_cg3 with dissolve_cg
    "Suddenly, Sayori wraps her arms tightly around me."
    s "[player]..."
    s "Is this...really okay?"
    mc "Yeah."
    "I hold Sayori in my arms and pull her closer."
    mc "You'll never have to let go of me again."
    s "I love you, [player]..."
    s "I want to be with you forever."
    mc "Me too."
    s "..."
    "I feel Sayori's grip around me weaken a little bit."
    s "What is this...?"
    mc "Sayori...?"
    s "I'm supposed to be happy right now..."
    s "I always thought this would be the happiest moment for me."
    s "But why...?"
    s "Even now..."
    s "Why won't the rainclouds go away?"
    s "They're not going away at all, [player]..."
    mc "It's okay, Sayori..."
    mc "It might take some time for things to get better again."
    mc "But no matter how long it takes, I'll be there every step of the way."
    mc "That's all that matters right now."
    s "O-Okay..."
    s "I...trust you..."
    scene bg house
    show sayori 1bv zorder 2 at i11
    with dissolve_cg
    "Sayori and I slowly release each other."
    mc "So..."
    mc "I guess that makes the festival tomorrow...our first date, huh?"
    s 1by "Ehehe..."
    s "What are you saying?"
    s "I don't want to think about those things, you know?"
    s "I want everything to be the same as it always has been."
    s "Even if we really are...a couple."
    s 1bk "I don't know if I could handle anything more right now..."
    s "It's really new and scary to me."
    mc "I understand."
    mc "We'll go at whatever pace suits you best."
    s 1bd "Hey, [player]..."
    "Sayori gazes at me once again, smiling sadly."
    s 4bd "Even if I get really, really sad..."
    s "This is the best thing for me...right?"
    mc "Eh...?"
    "I don't really understand what Sayori means by that."
    mc "Are you saying that this is making you feel sad, Sayori?"
    s 4bk "I-I don't know..."
    s "I don't understand what I'm feeling."
    s "It felt like a bunch of thorns when you told me you love me..."
    s 4bd "But that's why I want to trust you."
    s "You know what's best for me..."
    mc "...Yeah."
    mc "I do."
    mc "That's my promise."
    show sayori zorder 1 at thide
    hide sayori
    "I say that, but in reality, I've never felt more uncertain when it comes to Sayori."
    "I know that I love her, and she loves me."
    "But I'm having as much trouble understanding Sayori's feelings as she is."
    "Even though I can comfort her..."
    "I keep wondering if I should be doing something more, or something different."
    "I know these thoughts will continue to plague me until things are back to the way they were."
    "Is that what Sayori meant by not wanting anything to change?"
    "I don't know."
    "But I know that I'll give it everything I've got."
    "Sayori is the most important person to me."
    "And I'll do whatever it takes to have a happy future with her."
    return


label ch4_end_no:
    mc "You'll always be my dearest friend."
    mc "What you need most is for things to be like they've always been."
    mc "Monika told me the truth..."
    mc "She told me how much happier you seemed after I joined the club."
    mc "I know you're struggling with some really difficult feelings right now."
    mc "But..."
    mc "Please trust me that I know what's best...and what will make you happy in the end."
    mc "I promise I'll help get things back to the way they were."
    s 1bt "I..."
    s "I...see..."
    "Sayori forces a smile through an incredibly pained expression."
    s "Ahaha..."
    s "Is this what it feels like...to get stabbed in the chest?"
    s "I should write a poem about this..."
    mc "Sayori--"
    s "It's okay."
    s "This is just my punishment...remember?"
    s "For being so selfish..."
    s "So please..."
    s "Please don't worry about these stupid feelings."
    s "I know you're right."
    s "I knew this whole time that there's no happiness down that path."
    s "That's why I came here..."
    s "Just so I could get the answer I needed to hear."
    s "And the other thing..."
    s "You're also right that I just want it to go back to the way it was."
    s "I realize that now."
    s "You really do know me better than anyone, [player]."
    s 4bv "I'll trust you with anything..."
    s "Anything at all..."
    s "So..."
    show sayori zorder 1 at thide
    hide sayori
    "Sayori's smile finally breaks."
    "All of a sudden, she turns around and drops to her knees."
    s "{i}AAAAAaaaaAAAAAAAAHH!!!!{/i}"
    "Clutching her head with both hands, she screams as loudly as she can."
    "I'm so shocked that I don't know how to react."
    show sayori 4bt zorder 2 at t11
    s "..."
    show sayori at lhide
    hide sayori
    "Sayori looks over her shoulder and flashes me one more weak smile before turning around and running off."
    mc "Sayori!"
    "..."
    "I'm left helplessly standing in the front of my house."
    "Why am I feeling so horrible about this?"
    "There's nothing more that I could have done."
    "The most I can do is support Sayori through her feelings and help her on the path that's right."
    "But I'm having as much trouble understanding Sayori's feelings as she is."
    "Even though I can comfort her..."
    "I keep wondering if I should be doing something more, or something different."
    "I know these thoughts will continue to plague me until things are back to the way they were."
    "I'm going to give it everything I've got."
    "Sayori will always be my dearest friend."
    "And I'll do whatever it takes to put a smile on her face every day."

    return
# Decompiled by unrpyc: https://github.com/CensoredUsername/unrpyc
