############################ AUTO-GENERATED ###################################
## DO NOT EDIT THIS FILE                                                     ##
##                                                                           ##
## This was auto-generated by the the spritemaker tool                       ##
###############################################################################

image monika 6hkbsu_static = DynamicDisplayable(
    mas_drawmonika,
    character=monika_chr,
    eyebrows="knit",
    eyes="closedhappy",
    nose="def",
    mouth="smug",
    arms="down",
    blush="shade"
)

image monika 6hksdlb_static = DynamicDisplayable(
    mas_drawmonika,
    character=monika_chr,
    eyebrows="knit",
    eyes="closedhappy",
    nose="def",
    mouth="big",
    arms="down",
    head="l",
    left="1l",
    right="1r",
    sweat="def"
)

image monika 6hua_static = DynamicDisplayable(
    mas_drawmonika,
    character=monika_chr,
    eyebrows="up",
    eyes="closedhappy",
    nose="def",
    mouth="smile",
    arms="down",
    head="j",
    left="1l",
    right="1r"
)

image monika 6hub_static = DynamicDisplayable(
    mas_drawmonika,
    character=monika_chr,
    eyebrows="up",
    eyes="closedhappy",
    nose="def",
    mouth="big",
    arms="down",
    head="k",
    left="1l",
    right="1r"
)

image monika 6hubfa_static = DynamicDisplayable(
    mas_drawmonika,
    character=monika_chr,
    eyebrows="up",
    eyes="closedhappy",
    nose="def",
    mouth="smile",
    arms="down",
    head="j",
    left="1l",
    right="1r",
    blush="full"
)

image monika 6hubfb_static = DynamicDisplayable(
    mas_drawmonika,
    character=monika_chr,
    eyebrows="up",
    eyes="closedhappy",
    nose="def",
    mouth="big",
    arms="down",
    head="k",
    left="1l",
    right="1r",
    blush="full"
)

image monika 6lftsc_static = DynamicDisplayable(
    mas_drawmonika,
    character=monika_chr,
    eyebrows="furrowed",
    eyes="left",
    nose="def",
    mouth="smirk",
    arms="down",
    tears="streaming"
)

image monika 6lkc_static = DynamicDisplayable(
    mas_drawmonika,
    character=monika_chr,
    eyebrows="knit",
    eyes="left",
    nose="def",
    mouth="smirk",
    arms="down",
    head="o",
    left="1l",
    right="1r"
)

image monika 6lktdc_static = DynamicDisplayable(
    mas_drawmonika,
    character=monika_chr,
    eyebrows="knit",
    eyes="left",
    nose="def",
    mouth="smirk",
    arms="down",
    head="o",
    left="1l",
    right="1r",
    tears="dried"
)

image monika 6lktsc_static = DynamicDisplayable(
    mas_drawmonika,
    character=monika_chr,
    eyebrows="knit",
    eyes="left",
    nose="def",
    mouth="smirk",
    arms="down",
    head="o",
    left="1l",
    right="1r",
    tears="streaming"
)

image monika 6rkbfd_static = DynamicDisplayable(
    mas_drawmonika,
    character=monika_chr,
    eyebrows="knit",
    eyes="right",
    nose="def",
    mouth="small",
    arms="down",
    blush="full"
)

image monika 6rkc_static = DynamicDisplayable(
    mas_drawmonika,
    character=monika_chr,
    eyebrows="knit",
    eyes="right",
    nose="def",
    mouth="smirk",
    arms="down"
)

image monika 6rksdla_static = DynamicDisplayable(
    mas_drawmonika,
    character=monika_chr,
    eyebrows="knit",
    eyes="right",
    nose="def",
    mouth="smile",
    arms="down",
    sweat="def"
)

image monika 6rksdlc_static = DynamicDisplayable(
    mas_drawmonika,
    character=monika_chr,
    eyebrows="knit",
    eyes="right",
    nose="def",
    mouth="smirk",
    arms="down",
    sweat="def"
)

image monika 6rktda_static = DynamicDisplayable(
    mas_drawmonika,
    character=monika_chr,
    eyebrows="knit",
    eyes="right",
    nose="def",
    mouth="smile",
    arms="down",
    tears="dried"
)

image monika 6rktdc_static = DynamicDisplayable(
    mas_drawmonika,
    character=monika_chr,
    eyebrows="knit",
    eyes="right",
    nose="def",
    mouth="smirk",
    arms="down",
    tears="dried"
)

image monika 6rktsc_static = DynamicDisplayable(
    mas_drawmonika,
    character=monika_chr,
    eyebrows="knit",
    eyes="right",
    nose="def",
    mouth="smirk",
    arms="down",
    tears="streaming"
)

image monika 6rktuc_static = DynamicDisplayable(
    mas_drawmonika,
    character=monika_chr,
    eyebrows="knit",
    eyes="right",
    nose="def",
    mouth="smirk",
    arms="down",
    tears="up"
)

image monika 6sua_static = DynamicDisplayable(
    mas_drawmonika,
    character=monika_chr,
    eyebrows="up",
    eyes="sparkle",
    nose="def",
    mouth="smile",
    arms="down"
)

image monika 6sub_static = DynamicDisplayable(
    mas_drawmonika,
    character=monika_chr,
    eyebrows="up",
    eyes="sparkle",
    nose="def",
    mouth="big",
    arms="down"
)

image monika 6suu_static = DynamicDisplayable(
    mas_drawmonika,
    character=monika_chr,
    eyebrows="up",
    eyes="sparkle",
    nose="def",
    mouth="smug",
    arms="down"
)

image monika 6tftpc_static = DynamicDisplayable(
    mas_drawmonika,
    character=monika_chr,
    eyebrows="furrowed",
    eyes="smug",
    nose="def",
    mouth="smirk",
    arms="down",
    tears="pooled"
)

image monika 6tkbfu_static = DynamicDisplayable(
    mas_drawmonika,
    character=monika_chr,
    eyebrows="knit",
    eyes="smug",
    nose="def",
    mouth="smug",
    arms="down",
    blush="full"
)

image monika 6tsbfa_static = DynamicDisplayable(
    mas_drawmonika,
    character=monika_chr,
    eyebrows="mid",
    eyes="smug",
    nose="def",
    mouth="smile",
    arms="down",
    blush="full"
)

image monika 6tsbsa_static = DynamicDisplayable(
    mas_drawmonika,
    character=monika_chr,
    eyebrows="mid",
    eyes="smug",
    nose="def",
    mouth="smile",
    arms="down",
    blush="shade"
)

image monika 6tst_static = DynamicDisplayable(
    mas_drawmonika,
    character=monika_chr,
    eyebrows="mid",
    eyes="smug",
    nose="def",
    mouth="triangle",
    arms="down"
)

image monika 6tubfa_static = DynamicDisplayable(
    mas_drawmonika,
    character=monika_chr,
    eyebrows="up",
    eyes="smug",
    nose="def",
    mouth="smile",
    arms="down",
    blush="full"
)

image monika 6tubsa_static = DynamicDisplayable(
    mas_drawmonika,
    character=monika_chr,
    eyebrows="up",
    eyes="smug",
    nose="def",
    mouth="smile",
    arms="down",
    blush="shade"
)

image monika 6wfw_static = DynamicDisplayable(
    mas_drawmonika,
    character=monika_chr,
    eyebrows="furrowed",
    eyes="wide",
    nose="def",
    mouth="wide",
    arms="down"
)

image monika 6wka_static = DynamicDisplayable(
    mas_drawmonika,
    character=monika_chr,
    eyebrows="knit",
    eyes="wide",
    nose="def",
    mouth="smile",
    arms="down"
)

image monika 6wub_static = DynamicDisplayable(
    mas_drawmonika,
    character=monika_chr,
    eyebrows="up",
    eyes="wide",
    nose="def",
    mouth="big",
    arms="down"
)

image monika 6wubfo_static = DynamicDisplayable(
    mas_drawmonika,
    character=monika_chr,
    eyebrows="up",
    eyes="wide",
    nose="def",
    mouth="gasp",
    arms="down",
    blush="full"
)

image monika 6wubsw_static = DynamicDisplayable(
    mas_drawmonika,
    character=monika_chr,
    eyebrows="up",
    eyes="wide",
    nose="def",
    mouth="wide",
    arms="down",
    blush="shade"
)

image monika 6wuo_static = DynamicDisplayable(
    mas_drawmonika,
    character=monika_chr,
    eyebrows="up",
    eyes="wide",
    nose="def",
    mouth="gasp",
    arms="down"
)

