############################ AUTO-GENERATED ###################################
## DO NOT EDIT THIS FILE                                                     ##
##                                                                           ##
## This was auto-generated by the the spritemaker tool                       ##
###############################################################################

image monika 4efx:
    block:
        "monika 4efx_static"
        block:
            choice:
                3
            choice:
                5
            choice:
                7
        "monika 4dfx_static"
        0.06
        repeat

image monika 4eka:
    block:
        "monika 4eka_static"
        block:
            choice:
                3
            choice:
                5
            choice:
                7
        "monika 4dka_static"
        0.06
        repeat

image monika 4ekb:
    block:
        "monika 4ekb_static"
        block:
            choice:
                3
            choice:
                5
            choice:
                7
        "monika 4dkb_static"
        0.06
        repeat

image monika 4ekbfa:
    block:
        "monika 4ekbfa_static"
        block:
            choice:
                3
            choice:
                5
            choice:
                7
        "monika 4dkbfa_static"
        0.06
        repeat

image monika 4ekbfb:
    block:
        "monika 4ekbfb_static"
        block:
            choice:
                3
            choice:
                5
            choice:
                7
        "monika 4dkbfb_static"
        0.06
        repeat

image monika 4ekbsa:
    block:
        "monika 4ekbsa_static"
        block:
            choice:
                3
            choice:
                5
            choice:
                7
        "monika 4dkbsa_static"
        0.06
        repeat

image monika 4ekc:
    block:
        "monika 4ekc_static"
        block:
            choice:
                3
            choice:
                5
            choice:
                7
        "monika 4dkc_static"
        0.06
        repeat

image monika 4ekd:
    block:
        "monika 4ekd_static"
        block:
            choice:
                3
            choice:
                5
            choice:
                7
        "monika 4dkd_static"
        0.06
        repeat

image monika 4eksdla:
    block:
        "monika 4eksdla_static"
        block:
            choice:
                3
            choice:
                5
            choice:
                7
        "monika 4dksdla_static"
        0.06
        repeat

image monika 4eksdlc:
    block:
        "monika 4eksdlc_static"
        block:
            choice:
                3
            choice:
                5
            choice:
                7
        "monika 4dksdlc_static"
        0.06
        repeat

image monika 4eksdld:
    block:
        "monika 4eksdld_static"
        block:
            choice:
                3
            choice:
                5
            choice:
                7
        "monika 4dksdld_static"
        0.06
        repeat

image monika 4ektdc:
    block:
        "monika 4ektdc_static"
        block:
            choice:
                3
            choice:
                5
            choice:
                7
        "monika 4dktdc_static"
        0.06
        repeat

image monika 4ektsc:
    block:
        "monika 4ektsc_static"
        block:
            choice:
                3
            choice:
                5
            choice:
                7
        "monika 4dktsc_static"
        0.06
        repeat

image monika 4esa:
    block:
        "monika 4esa_static"
        block:
            choice:
                3
            choice:
                5
            choice:
                7
        "monika 4dsa_static"
        0.06
        repeat

image monika 4esb:
    block:
        "monika 4esb_static"
        block:
            choice:
                3
            choice:
                5
            choice:
                7
        "monika 4dsb_static"
        0.06
        repeat

image monika 4esc:
    block:
        "monika 4esc_static"
        block:
            choice:
                3
            choice:
                5
            choice:
                7
        "monika 4dsc_static"
        0.06
        repeat

image monika 4esd:
    block:
        "monika 4esd_static"
        block:
            choice:
                3
            choice:
                5
            choice:
                7
        "monika 4dsd_static"
        0.06
        repeat

image monika 4eua:
    block:
        "monika 4eua_static"
        block:
            choice:
                3
            choice:
                5
            choice:
                7
        "monika 4dua_static"
        0.06
        repeat

image monika 4eub:
    block:
        "monika 4eub_static"
        block:
            choice:
                3
            choice:
                5
            choice:
                7
        "monika 4dub_static"
        0.06
        repeat

image monika 4euc:
    block:
        "monika 4euc_static"
        block:
            choice:
                3
            choice:
                5
            choice:
                7
        "monika 4duc_static"
        0.06
        repeat

image monika 4eud:
    block:
        "monika 4eud_static"
        block:
            choice:
                3
            choice:
                5
            choice:
                7
        "monika 4dud_static"
        0.06
        repeat

image monika 4euo:
    block:
        "monika 4euo_static"
        block:
            choice:
                3
            choice:
                5
            choice:
                7
        "monika 4duo_static"
        0.06
        repeat

image monika 4lfb:
    block:
        "monika 4lfb_static"
        block:
            choice:
                3
            choice:
                5
            choice:
                7
        "monika 4dfb_static"
        0.06
        repeat

image monika 4lfc:
    block:
        "monika 4lfc_static"
        block:
            choice:
                3
            choice:
                5
            choice:
                7
        "monika 4dfc_static"
        0.06
        repeat

image monika 4lfd:
    block:
        "monika 4lfd_static"
        block:
            choice:
                3
            choice:
                5
            choice:
                7
        "monika 4dfd_static"
        0.06
        repeat

image monika 4lftsc:
    block:
        "monika 4lftsc_static"
        block:
            choice:
                3
            choice:
                5
            choice:
                7
        "monika 4dftsc_static"
        0.06
        repeat

image monika 4lfu:
    block:
        "monika 4lfu_static"
        block:
            choice:
                3
            choice:
                5
            choice:
                7
        "monika 4dfu_static"
        0.06
        repeat

image monika 4lfw:
    block:
        "monika 4lfw_static"
        block:
            choice:
                3
            choice:
                5
            choice:
                7
        "monika 4dfw_static"
        0.06
        repeat

image monika 4lfx:
    block:
        "monika 4lfx_static"
        block:
            choice:
                3
            choice:
                5
            choice:
                7
        "monika 4dfx_static"
        0.06
        repeat

image monika 4lkbfb:
    block:
        "monika 4lkbfb_static"
        block:
            choice:
                3
            choice:
                5
            choice:
                7
        "monika 4dkbfb_static"
        0.06
        repeat

image monika 4lkbsa:
    block:
        "monika 4lkbsa_static"
        block:
            choice:
                3
            choice:
                5
            choice:
                7
        "monika 4dkbsa_static"
        0.06
        repeat

image monika 4lkbsc:
    block:
        "monika 4lkbsc_static"
        block:
            choice:
                3
            choice:
                5
            choice:
                7
        "monika 4dkbsc_static"
        0.06
        repeat

image monika 4lksdla:
    block:
        "monika 4lksdla_static"
        block:
            choice:
                3
            choice:
                5
            choice:
                7
        "monika 4dksdla_static"
        0.06
        repeat

image monika 4lksdlb:
    block:
        "monika 4lksdlb_static"
        block:
            choice:
                3
            choice:
                5
            choice:
                7
        "monika 4dksdlb_static"
        0.06
        repeat

image monika 4lksdlc:
    block:
        "monika 4lksdlc_static"
        block:
            choice:
                3
            choice:
                5
            choice:
                7
        "monika 4dksdlc_static"
        0.06
        repeat

image monika 4lksdld:
    block:
        "monika 4lksdld_static"
        block:
            choice:
                3
            choice:
                5
            choice:
                7
        "monika 4dksdld_static"
        0.06
        repeat

image monika 4lksdlw:
    block:
        "monika 4lksdlw_static"
        block:
            choice:
                3
            choice:
                5
            choice:
                7
        "monika 4dksdlw_static"
        0.06
        repeat

image monika 4lksdrb:
    block:
        "monika 4lksdrb_static"
        block:
            choice:
                3
            choice:
                5
            choice:
                7
        "monika 4dksdrb_static"
        0.06
        repeat

image monika 4lktsc:
    block:
        "monika 4lktsc_static"
        block:
            choice:
                3
            choice:
                5
            choice:
                7
        "monika 4dktsc_static"
        0.06
        repeat

image monika 4lsbsa:
    block:
        "monika 4lsbsa_static"
        block:
            choice:
                3
            choice:
                5
            choice:
                7
        "monika 4dsbsa_static"
        0.06
        repeat

image monika 4lsbssdrb:
    block:
        "monika 4lsbssdrb_static"
        block:
            choice:
                3
            choice:
                5
            choice:
                7
        "monika 4dsbssdrb_static"
        0.06
        repeat

image monika 4lsc:
    block:
        "monika 4lsc_static"
        block:
            choice:
                3
            choice:
                5
            choice:
                7
        "monika 4dsc_static"
        0.06
        repeat

image monika 4lssdrb:
    block:
        "monika 4lssdrb_static"
        block:
            choice:
                3
            choice:
                5
            choice:
                7
        "monika 4dssdrb_static"
        0.06
        repeat

image monika 4lssdrc:
    block:
        "monika 4lssdrc_static"
        block:
            choice:
                3
            choice:
                5
            choice:
                7
        "monika 4dssdrc_static"
        0.06
        repeat

image monika 4lubfb:
    block:
        "monika 4lubfb_static"
        block:
            choice:
                3
            choice:
                5
            choice:
                7
        "monika 4dubfb_static"
        0.06
        repeat

image monika 4lubsb:
    block:
        "monika 4lubsb_static"
        block:
            choice:
                3
            choice:
                5
            choice:
                7
        "monika 4dubsb_static"
        0.06
        repeat

image monika 4lud:
    block:
        "monika 4lud_static"
        block:
            choice:
                3
            choice:
                5
            choice:
                7
        "monika 4dud_static"
        0.06
        repeat

image monika 4rfb:
    block:
        "monika 4rfb_static"
        block:
            choice:
                3
            choice:
                5
            choice:
                7
        "monika 4dfb_static"
        0.06
        repeat

image monika 4rfc:
    block:
        "monika 4rfc_static"
        block:
            choice:
                3
            choice:
                5
            choice:
                7
        "monika 4dfc_static"
        0.06
        repeat

image monika 4rfd:
    block:
        "monika 4rfd_static"
        block:
            choice:
                3
            choice:
                5
            choice:
                7
        "monika 4dfd_static"
        0.06
        repeat

image monika 4rfu:
    block:
        "monika 4rfu_static"
        block:
            choice:
                3
            choice:
                5
            choice:
                7
        "monika 4dfu_static"
        0.06
        repeat

image monika 4rfw:
    block:
        "monika 4rfw_static"
        block:
            choice:
                3
            choice:
                5
            choice:
                7
        "monika 4dfw_static"
        0.06
        repeat

image monika 4rfx:
    block:
        "monika 4rfx_static"
        block:
            choice:
                3
            choice:
                5
            choice:
                7
        "monika 4dfx_static"
        0.06
        repeat

image monika 4rkbfb:
    block:
        "monika 4rkbfb_static"
        block:
            choice:
                3
            choice:
                5
            choice:
                7
        "monika 4dkbfb_static"
        0.06
        repeat

image monika 4rkc:
    block:
        "monika 4rkc_static"
        block:
            choice:
                3
            choice:
                5
            choice:
                7
        "monika 4dkc_static"
        0.06
        repeat

image monika 4rkd:
    block:
        "monika 4rkd_static"
        block:
            choice:
                3
            choice:
                5
            choice:
                7
        "monika 4dkd_static"
        0.06
        repeat

image monika 4rksdla:
    block:
        "monika 4rksdla_static"
        block:
            choice:
                3
            choice:
                5
            choice:
                7
        "monika 4dksdla_static"
        0.06
        repeat

image monika 4rksdlb:
    block:
        "monika 4rksdlb_static"
        block:
            choice:
                3
            choice:
                5
            choice:
                7
        "monika 4dksdlb_static"
        0.06
        repeat

image monika 4rksdlc:
    block:
        "monika 4rksdlc_static"
        block:
            choice:
                3
            choice:
                5
            choice:
                7
        "monika 4dksdlc_static"
        0.06
        repeat

image monika 4rksdld:
    block:
        "monika 4rksdld_static"
        block:
            choice:
                3
            choice:
                5
            choice:
                7
        "monika 4dksdld_static"
        0.06
        repeat

image monika 4rktpc:
    block:
        "monika 4rktpc_static"
        block:
            choice:
                3
            choice:
                5
            choice:
                7
        "monika 4dktpc_static"
        0.06
        repeat

image monika 4rktsc:
    block:
        "monika 4rktsc_static"
        block:
            choice:
                3
            choice:
                5
            choice:
                7
        "monika 4dktsc_static"
        0.06
        repeat

image monika 4rsc:
    block:
        "monika 4rsc_static"
        block:
            choice:
                3
            choice:
                5
            choice:
                7
        "monika 4dsc_static"
        0.06
        repeat

image monika 4rssdrb:
    block:
        "monika 4rssdrb_static"
        block:
            choice:
                3
            choice:
                5
            choice:
                7
        "monika 4dssdrb_static"
        0.06
        repeat

image monika 4rssdrc:
    block:
        "monika 4rssdrc_static"
        block:
            choice:
                3
            choice:
                5
            choice:
                7
        "monika 4dssdrc_static"
        0.06
        repeat

image monika 4sub:
    block:
        "monika 4sub_static"
        block:
            choice:
                3
            choice:
                5
            choice:
                7
        "monika 4dub_static"
        0.06
        repeat

image monika 4subfb:
    block:
        "monika 4subfb_static"
        block:
            choice:
                3
            choice:
                5
            choice:
                7
        "monika 4dubfb_static"
        0.06
        repeat

image monika 4subftsb:
    block:
        "monika 4subftsb_static"
        block:
            choice:
                3
            choice:
                5
            choice:
                7
        "monika 4dubftsb_static"
        0.06
        repeat

image monika 4sutsa:
    block:
        "monika 4sutsa_static"
        block:
            choice:
                3
            choice:
                5
            choice:
                7
        "monika 4dutsa_static"
        0.06
        repeat

image monika 4tfb:
    block:
        "monika 4tfb_static"
        block:
            choice:
                3
            choice:
                5
            choice:
                7
        "monika 4dfb_static"
        0.06
        repeat

image monika 4tfc:
    block:
        "monika 4tfc_static"
        block:
            choice:
                3
            choice:
                5
            choice:
                7
        "monika 4dfc_static"
        0.06
        repeat

image monika 4tfd:
    block:
        "monika 4tfd_static"
        block:
            choice:
                3
            choice:
                5
            choice:
                7
        "monika 4dfd_static"
        0.06
        repeat

image monika 4tfo:
    block:
        "monika 4tfo_static"
        block:
            choice:
                3
            choice:
                5
            choice:
                7
        "monika 4dfo_static"
        0.06
        repeat

image monika 4tfu:
    block:
        "monika 4tfu_static"
        block:
            choice:
                3
            choice:
                5
            choice:
                7
        "monika 4dfu_static"
        0.06
        repeat

image monika 4tfx:
    block:
        "monika 4tfx_static"
        block:
            choice:
                3
            choice:
                5
            choice:
                7
        "monika 4dfx_static"
        0.06
        repeat

image monika 4tkc:
    block:
        "monika 4tkc_static"
        block:
            choice:
                3
            choice:
                5
            choice:
                7
        "monika 4dkc_static"
        0.06
        repeat

image monika 4tkd:
    block:
        "monika 4tkd_static"
        block:
            choice:
                3
            choice:
                5
            choice:
                7
        "monika 4dkd_static"
        0.06
        repeat

image monika 4tku:
    block:
        "monika 4tku_static"
        block:
            choice:
                3
            choice:
                5
            choice:
                7
        "monika 4dku_static"
        0.06
        repeat

image monika 4tkx:
    block:
        "monika 4tkx_static"
        block:
            choice:
                3
            choice:
                5
            choice:
                7
        "monika 4dkx_static"
        0.06
        repeat

image monika 4tsb:
    block:
        "monika 4tsb_static"
        block:
            choice:
                3
            choice:
                5
            choice:
                7
        "monika 4dsb_static"
        0.06
        repeat

image monika 4tsbsa:
    block:
        "monika 4tsbsa_static"
        block:
            choice:
                3
            choice:
                5
            choice:
                7
        "monika 4dsbsa_static"
        0.06
        repeat

image monika 4tub:
    block:
        "monika 4tub_static"
        block:
            choice:
                3
            choice:
                5
            choice:
                7
        "monika 4dub_static"
        0.06
        repeat

image monika 4tubfb:
    block:
        "monika 4tubfb_static"
        block:
            choice:
                3
            choice:
                5
            choice:
                7
        "monika 4dubfb_static"
        0.06
        repeat

image monika 4wfw:
    block:
        "monika 4wfw_static"
        block:
            choice:
                3
            choice:
                5
            choice:
                7
        "monika 4dfw_static"
        0.06
        repeat

image monika 4wfx:
    block:
        "monika 4wfx_static"
        block:
            choice:
                3
            choice:
                5
            choice:
                7
        "monika 4dfx_static"
        0.06
        repeat

image monika 4wkbsc:
    block:
        "monika 4wkbsc_static"
        block:
            choice:
                3
            choice:
                5
            choice:
                7
        "monika 4dkbsc_static"
        0.06
        repeat

image monika 4wkc:
    block:
        "monika 4wkc_static"
        block:
            choice:
                3
            choice:
                5
            choice:
                7
        "monika 4dkc_static"
        0.06
        repeat

image monika 4wkd:
    block:
        "monika 4wkd_static"
        block:
            choice:
                3
            choice:
                5
            choice:
                7
        "monika 4dkd_static"
        0.06
        repeat

image monika 4wktsw:
    block:
        "monika 4wktsw_static"
        block:
            choice:
                3
            choice:
                5
            choice:
                7
        "monika 4dktsw_static"
        0.06
        repeat

image monika 4wua:
    block:
        "monika 4wua_static"
        block:
            choice:
                3
            choice:
                5
            choice:
                7
        "monika 4dua_static"
        0.06
        repeat

image monika 4wub:
    block:
        "monika 4wub_static"
        block:
            choice:
                3
            choice:
                5
            choice:
                7
        "monika 4dub_static"
        0.06
        repeat

image monika 4wubfb:
    block:
        "monika 4wubfb_static"
        block:
            choice:
                3
            choice:
                5
            choice:
                7
        "monika 4dubfb_static"
        0.06
        repeat

image monika 4wubfsdld:
    block:
        "monika 4wubfsdld_static"
        block:
            choice:
                3
            choice:
                5
            choice:
                7
        "monika 4dubfsdld_static"
        0.06
        repeat

image monika 4wubso:
    block:
        "monika 4wubso_static"
        block:
            choice:
                3
            choice:
                5
            choice:
                7
        "monika 4dubso_static"
        0.06
        repeat

image monika 4wubsw:
    block:
        "monika 4wubsw_static"
        block:
            choice:
                3
            choice:
                5
            choice:
                7
        "monika 4dubsw_static"
        0.06
        repeat

image monika 4wuc:
    block:
        "monika 4wuc_static"
        block:
            choice:
                3
            choice:
                5
            choice:
                7
        "monika 4duc_static"
        0.06
        repeat

image monika 4wud:
    block:
        "monika 4wud_static"
        block:
            choice:
                3
            choice:
                5
            choice:
                7
        "monika 4dud_static"
        0.06
        repeat

image monika 4wuo:
    block:
        "monika 4wuo_static"
        block:
            choice:
                3
            choice:
                5
            choice:
                7
        "monika 4duo_static"
        0.06
        repeat

image monika 4wuw:
    block:
        "monika 4wuw_static"
        block:
            choice:
                3
            choice:
                5
            choice:
                7
        "monika 4duw_static"
        0.06
        repeat

image monika 5efa:
    block:
        "monika 5efa_static"
        block:
            choice:
                3
            choice:
                5
            choice:
                7
        "monika 5dfa_static"
        0.06
        repeat

image monika 5eka:
    block:
        "monika 5eka_static"
        block:
            choice:
                3
            choice:
                5
            choice:
                7
        "monika 5dka_static"
        0.06
        repeat

image monika 5ekbfa:
    block:
        "monika 5ekbfa_static"
        block:
            choice:
                3
            choice:
                5
            choice:
                7
        "monika 5dkbfa_static"
        0.06
        repeat

image monika 5ekbfu:
    block:
        "monika 5ekbfu_static"
        block:
            choice:
                3
            choice:
                5
            choice:
                7
        "monika 5dkbfu_static"
        0.06
        repeat

image monika 5ekbla:
    block:
        "monika 5ekbla_static"
        block:
            choice:
                3
            choice:
                5
            choice:
                7
        "monika 5dkbla_static"
        0.06
        repeat

image monika 5ekbsa:
    block:
        "monika 5ekbsa_static"
        block:
            choice:
                3
            choice:
                5
            choice:
                7
        "monika 5dkbsa_static"
        0.06
        repeat

image monika 5ekbsu:
    block:
        "monika 5ekbsu_static"
        block:
            choice:
                3
            choice:
                5
            choice:
                7
        "monika 5dkbsu_static"
        0.06
        repeat

image monika 5esbfa:
    block:
        "monika 5esbfa_static"
        block:
            choice:
                3
            choice:
                5
            choice:
                7
        "monika 5dsbfa_static"
        0.06
        repeat

image monika 5esbfu:
    block:
        "monika 5esbfu_static"
        block:
            choice:
                3
            choice:
                5
            choice:
                7
        "monika 5dsbfu_static"
        0.06
        repeat

image monika 5esu:
    block:
        "monika 5esu_static"
        block:
            choice:
                3
            choice:
                5
            choice:
                7
        "monika 5dsu_static"
        0.06
        repeat

image monika 5eua:
    block:
        "monika 5eua_static"
        block:
            choice:
                3
            choice:
                5
            choice:
                7
        "monika 5dua_static"
        0.06
        repeat

image monika 5eub:
    block:
        "monika 5eub_static"
        block:
            choice:
                3
            choice:
                5
            choice:
                7
        "monika 5dub_static"
        0.06
        repeat

image monika 5eubfa:
    block:
        "monika 5eubfa_static"
        block:
            choice:
                3
            choice:
                5
            choice:
                7
        "monika 5dubfa_static"
        0.06
        repeat

image monika 5eubfb:
    block:
        "monika 5eubfb_static"
        block:
            choice:
                3
            choice:
                5
            choice:
                7
        "monika 5dubfb_static"
        0.06
        repeat

image monika 5eubfu:
    block:
        "monika 5eubfu_static"
        block:
            choice:
                3
            choice:
                5
            choice:
                7
        "monika 5dubfu_static"
        0.06
        repeat

image monika 5eubla:
    block:
        "monika 5eubla_static"
        block:
            choice:
                3
            choice:
                5
            choice:
                7
        "monika 5dubla_static"
        0.06
        repeat

image monika 5eubsa:
    block:
        "monika 5eubsa_static"
        block:
            choice:
                3
            choice:
                5
            choice:
                7
        "monika 5dubsa_static"
        0.06
        repeat

image monika 5euc:
    block:
        "monika 5euc_static"
        block:
            choice:
                3
            choice:
                5
            choice:
                7
        "monika 5duc_static"
        0.06
        repeat

image monika 5ksbfu:
    block:
        "monika 5ksbfu_static"
        1
        "monika 5esbfu"

image monika 5kua:
    block:
        "monika 5kua_static"
        1
        "monika 5eua"

image monika 5kubfu:
    block:
        "monika 5kubfu_static"
        1
        "monika 5eubfu"

image monika 5lfc:
    block:
        "monika 5lfc_static"
        block:
            choice:
                3
            choice:
                5
            choice:
                7
        "monika 5dfc_static"
        0.06
        repeat

image monika 5lkc:
    block:
        "monika 5lkc_static"
        block:
            choice:
                3
            choice:
                5
            choice:
                7
        "monika 5dkc_static"
        0.06
        repeat

image monika 5lsc:
    block:
        "monika 5lsc_static"
        block:
            choice:
                3
            choice:
                5
            choice:
                7
        "monika 5dsc_static"
        0.06
        repeat

image monika 5lubfb:
    block:
        "monika 5lubfb_static"
        block:
            choice:
                3
            choice:
                5
            choice:
                7
        "monika 5dubfb_static"
        0.06
        repeat

image monika 5lubfsdrb:
    block:
        "monika 5lubfsdrb_static"
        block:
            choice:
                3
            choice:
                5
            choice:
                7
        "monika 5dubfsdrb_static"
        0.06
        repeat

image monika 5lubfsdru:
    block:
        "monika 5lubfsdru_static"
        block:
            choice:
                3
            choice:
                5
            choice:
                7
        "monika 5dubfsdru_static"
        0.06
        repeat

image monika 5lubfu:
    block:
        "monika 5lubfu_static"
        block:
            choice:
                3
            choice:
                5
            choice:
                7
        "monika 5dubfu_static"
        0.06
        repeat

image monika 5lubsa:
    block:
        "monika 5lubsa_static"
        block:
            choice:
                3
            choice:
                5
            choice:
                7
        "monika 5dubsa_static"
        0.06
        repeat

image monika 5lusdrb:
    block:
        "monika 5lusdrb_static"
        block:
            choice:
                3
            choice:
                5
            choice:
                7
        "monika 5dusdrb_static"
        0.06
        repeat

image monika 5lusdru:
    block:
        "monika 5lusdru_static"
        block:
            choice:
                3
            choice:
                5
            choice:
                7
        "monika 5dusdru_static"
        0.06
        repeat

image monika 5luu:
    block:
        "monika 5luu_static"
        block:
            choice:
                3
            choice:
                5
            choice:
                7
        "monika 5duu_static"
        0.06
        repeat

image monika 5rfc:
    block:
        "monika 5rfc_static"
        block:
            choice:
                3
            choice:
                5
            choice:
                7
        "monika 5dfc_static"
        0.06
        repeat

image monika 5rkbla:
    block:
        "monika 5rkbla_static"
        block:
            choice:
                3
            choice:
                5
            choice:
                7
        "monika 5dkbla_static"
        0.06
        repeat

image monika 5rkbsu:
    block:
        "monika 5rkbsu_static"
        block:
            choice:
                3
            choice:
                5
            choice:
                7
        "monika 5dkbsu_static"
        0.06
        repeat

image monika 5rkc:
    block:
        "monika 5rkc_static"
        block:
            choice:
                3
            choice:
                5
            choice:
                7
        "monika 5dkc_static"
        0.06
        repeat

image monika 5rsc:
    block:
        "monika 5rsc_static"
        block:
            choice:
                3
            choice:
                5
            choice:
                7
        "monika 5dsc_static"
        0.06
        repeat

image monika 5rub:
    block:
        "monika 5rub_static"
        block:
            choice:
                3
            choice:
                5
            choice:
                7
        "monika 5dub_static"
        0.06
        repeat

image monika 5rubfb:
    block:
        "monika 5rubfb_static"
        block:
            choice:
                3
            choice:
                5
            choice:
                7
        "monika 5dubfb_static"
        0.06
        repeat

image monika 5rubfsdrb:
    block:
        "monika 5rubfsdrb_static"
        block:
            choice:
                3
            choice:
                5
            choice:
                7
        "monika 5dubfsdrb_static"
        0.06
        repeat

image monika 5rubfsdru:
    block:
        "monika 5rubfsdru_static"
        block:
            choice:
                3
            choice:
                5
            choice:
                7
        "monika 5dubfsdru_static"
        0.06
        repeat

image monika 5rubfu:
    block:
        "monika 5rubfu_static"
        block:
            choice:
                3
            choice:
                5
            choice:
                7
        "monika 5dubfu_static"
        0.06
        repeat

image monika 5rusdrb:
    block:
        "monika 5rusdrb_static"
        block:
            choice:
                3
            choice:
                5
            choice:
                7
        "monika 5dusdrb_static"
        0.06
        repeat

image monika 5rusdru:
    block:
        "monika 5rusdru_static"
        block:
            choice:
                3
            choice:
                5
            choice:
                7
        "monika 5dusdru_static"
        0.06
        repeat

image monika 5ruu:
    block:
        "monika 5ruu_static"
        block:
            choice:
                3
            choice:
                5
            choice:
                7
        "monika 5duu_static"
        0.06
        repeat

image monika 5sub:
    block:
        "monika 5sub_static"
        block:
            choice:
                3
            choice:
                5
            choice:
                7
        "monika 5dub_static"
        0.06
        repeat

image monika 5subsb:
    block:
        "monika 5subsb_static"
        block:
            choice:
                3
            choice:
                5
            choice:
                7
        "monika 5dubsb_static"
        0.06
        repeat

image monika 5tkblu:
    block:
        "monika 5tkblu_static"
        block:
            choice:
                3
            choice:
                5
            choice:
                7
        "monika 5dkblu_static"
        0.06
        repeat

image monika 5tsa:
    block:
        "monika 5tsa_static"
        block:
            choice:
                3
            choice:
                5
            choice:
                7
        "monika 5dsa_static"
        0.06
        repeat

image monika 5tsbfu:
    block:
        "monika 5tsbfu_static"
        block:
            choice:
                3
            choice:
                5
            choice:
                7
        "monika 5dsbfu_static"
        0.06
        repeat

image monika 5tsbsu:
    block:
        "monika 5tsbsu_static"
        block:
            choice:
                3
            choice:
                5
            choice:
                7
        "monika 5dsbsu_static"
        0.06
        repeat

image monika 5tsc:
    block:
        "monika 5tsc_static"
        block:
            choice:
                3
            choice:
                5
            choice:
                7
        "monika 5dsc_static"
        0.06
        repeat

image monika 5tsu:
    block:
        "monika 5tsu_static"
        block:
            choice:
                3
            choice:
                5
            choice:
                7
        "monika 5dsu_static"
        0.06
        repeat

image monika 5ttu:
    block:
        "monika 5ttu_static"
        block:
            choice:
                3
            choice:
                5
            choice:
                7
        "monika 5dtu_static"
        0.06
        repeat

image monika 5tubfb:
    block:
        "monika 5tubfb_static"
        block:
            choice:
                3
            choice:
                5
            choice:
                7
        "monika 5dubfb_static"
        0.06
        repeat

image monika 5tubfu:
    block:
        "monika 5tubfu_static"
        block:
            choice:
                3
            choice:
                5
            choice:
                7
        "monika 5dubfu_static"
        0.06
        repeat

image monika 5tuu:
    block:
        "monika 5tuu_static"
        block:
            choice:
                3
            choice:
                5
            choice:
                7
        "monika 5duu_static"
        0.06
        repeat

image monika 5wub:
    block:
        "monika 5wub_static"
        block:
            choice:
                3
            choice:
                5
            choice:
                7
        "monika 5dub_static"
        0.06
        repeat

image monika 5wubfw:
    block:
        "monika 5wubfw_static"
        block:
            choice:
                3
            choice:
                5
            choice:
                7
        "monika 5dubfw_static"
        0.06
        repeat

image monika 5wuw:
    block:
        "monika 5wuw_static"
        block:
            choice:
                3
            choice:
                5
            choice:
                7
        "monika 5duw_static"
        0.06
        repeat

image monika 6cfw:
    block:
        "monika 6cfw_static"
        block:
            choice:
                3
            choice:
                5
            choice:
                7
        "monika 6dfw_static"
        0.06
        repeat

image monika 6ckc:
    block:
        "monika 6ckc_static"
        block:
            choice:
                3
            choice:
                5
            choice:
                7
        "monika 6dkc_static"
        0.06
        repeat

image monika 6eftsc:
    block:
        "monika 6eftsc_static"
        block:
            choice:
                3
            choice:
                5
            choice:
                7
        "monika 6dftsc_static"
        0.06
        repeat

image monika 6eka:
    block:
        "monika 6eka_static"
        block:
            choice:
                3
            choice:
                5
            choice:
                7
        "monika 6dka_static"
        0.06
        repeat

image monika 6ekbfa:
    block:
        "monika 6ekbfa_static"
        block:
            choice:
                3
            choice:
                5
            choice:
                7
        "monika 6dkbfa_static"
        0.06
        repeat

image monika 6ekbfd:
    block:
        "monika 6ekbfd_static"
        block:
            choice:
                3
            choice:
                5
            choice:
                7
        "monika 6dkbfd_static"
        0.06
        repeat

image monika 6ekbftda:
    block:
        "monika 6ekbftda_static"
        block:
            choice:
                3
            choice:
                5
            choice:
                7
        "monika 6dkbftda_static"
        0.06
        repeat

image monika 6ekbftpa:
    block:
        "monika 6ekbftpa_static"
        block:
            choice:
                3
            choice:
                5
            choice:
                7
        "monika 6dkbftpa_static"
        0.06
        repeat

image monika 6ekbsa:
    block:
        "monika 6ekbsa_static"
        block:
            choice:
                3
            choice:
                5
            choice:
                7
        "monika 6dkbsa_static"
        0.06
        repeat

image monika 6ekbsu:
    block:
        "monika 6ekbsu_static"
        block:
            choice:
                3
            choice:
                5
            choice:
                7
        "monika 6dkbsu_static"
        0.06
        repeat

image monika 6ekc:
    block:
        "monika 6ekc_static"
        block:
            choice:
                3
            choice:
                5
            choice:
                7
        "monika 6dkc_static"
        0.06
        repeat

image monika 6ekd:
    block:
        "monika 6ekd_static"
        block:
            choice:
                3
            choice:
                5
            choice:
                7
        "monika 6dkd_static"
        0.06
        repeat

image monika 6eko:
    block:
        "monika 6eko_static"
        block:
            choice:
                3
            choice:
                5
            choice:
                7
        "monika 6dko_static"
        0.06
        repeat

image monika 6ekp:
    block:
        "monika 6ekp_static"
        block:
            choice:
                3
            choice:
                5
            choice:
                7
        "monika 6dkp_static"
        0.06
        repeat

image monika 6eksdla:
    block:
        "monika 6eksdla_static"
        block:
            choice:
                3
            choice:
                5
            choice:
                7
        "monika 6dksdla_static"
        0.06
        repeat

image monika 6ektda:
    block:
        "monika 6ektda_static"
        block:
            choice:
                3
            choice:
                5
            choice:
                7
        "monika 6dktda_static"
        0.06
        repeat

image monika 6ektdc:
    block:
        "monika 6ektdc_static"
        block:
            choice:
                3
            choice:
                5
            choice:
                7
        "monika 6dktdc_static"
        0.06
        repeat

image monika 6ektpa:
    block:
        "monika 6ektpa_static"
        block:
            choice:
                3
            choice:
                5
            choice:
                7
        "monika 6dktpa_static"
        0.06
        repeat

image monika 6ektpc:
    block:
        "monika 6ektpc_static"
        block:
            choice:
                3
            choice:
                5
            choice:
                7
        "monika 6dktpc_static"
        0.06
        repeat

image monika 6ektpd:
    block:
        "monika 6ektpd_static"
        block:
            choice:
                3
            choice:
                5
            choice:
                7
        "monika 6dktpd_static"
        0.06
        repeat

image monika 6ektsa:
    block:
        "monika 6ektsa_static"
        block:
            choice:
                3
            choice:
                5
            choice:
                7
        "monika 6dktsa_static"
        0.06
        repeat

image monika 6ektsc:
    block:
        "monika 6ektsc_static"
        block:
            choice:
                3
            choice:
                5
            choice:
                7
        "monika 6dktsc_static"
        0.06
        repeat

image monika 6ektud:
    block:
        "monika 6ektud_static"
        block:
            choice:
                3
            choice:
                5
            choice:
                7
        "monika 6dktud_static"
        0.06
        repeat

image monika 6esa:
    block:
        "monika 6esa_static"
        block:
            choice:
                3
            choice:
                5
            choice:
                7
        "monika 6dsa_static"
        0.06
        repeat

image monika 6esbfa:
    block:
        "monika 6esbfa_static"
        block:
            choice:
                3
            choice:
                5
            choice:
                7
        "monika 6dsbfa_static"
        0.06
        repeat

image monika 6eua:
    block:
        "monika 6eua_static"
        block:
            choice:
                3
            choice:
                5
            choice:
                7
        "monika 6dua_static"
        0.06
        repeat

image monika 6eub:
    block:
        "monika 6eub_static"
        block:
            choice:
                3
            choice:
                5
            choice:
                7
        "monika 6dub_static"
        0.06
        repeat

image monika 6eud:
    block:
        "monika 6eud_static"
        block:
            choice:
                3
            choice:
                5
            choice:
                7
        "monika 6dud_static"
        0.06
        repeat

image monika 6lftsc:
    block:
        "monika 6lftsc_static"
        block:
            choice:
                3
            choice:
                5
            choice:
                7
        "monika 6dftsc_static"
        0.06
        repeat

image monika 6lkc:
    block:
        "monika 6lkc_static"
        block:
            choice:
                3
            choice:
                5
            choice:
                7
        "monika 6dkc_static"
        0.06
        repeat

image monika 6lktdc:
    block:
        "monika 6lktdc_static"
        block:
            choice:
                3
            choice:
                5
            choice:
                7
        "monika 6dktdc_static"
        0.06
        repeat

image monika 6lktpc:
    block:
        "monika 6lktpc_static"
        block:
            choice:
                3
            choice:
                5
            choice:
                7
        "monika 6dktpc_static"
        0.06
        repeat

image monika 6lktsc:
    block:
        "monika 6lktsc_static"
        block:
            choice:
                3
            choice:
                5
            choice:
                7
        "monika 6dktsc_static"
        0.06
        repeat

image monika 6lsc:
    block:
        "monika 6lsc_static"
        block:
            choice:
                3
            choice:
                5
            choice:
                7
        "monika 6dsc_static"
        0.06
        repeat

image monika 6rka:
    block:
        "monika 6rka_static"
        block:
            choice:
                3
            choice:
                5
            choice:
                7
        "monika 6dka_static"
        0.06
        repeat

image monika 6rkbfa:
    block:
        "monika 6rkbfa_static"
        block:
            choice:
                3
            choice:
                5
            choice:
                7
        "monika 6dkbfa_static"
        0.06
        repeat

image monika 6rkbfd:
    block:
        "monika 6rkbfd_static"
        block:
            choice:
                3
            choice:
                5
            choice:
                7
        "monika 6dkbfd_static"
        0.06
        repeat

image monika 6rkc:
    block:
        "monika 6rkc_static"
        block:
            choice:
                3
            choice:
                5
            choice:
                7
        "monika 6dkc_static"
        0.06
        repeat

image monika 6rksdla:
    block:
        "monika 6rksdla_static"
        block:
            choice:
                3
            choice:
                5
            choice:
                7
        "monika 6dksdla_static"
        0.06
        repeat

image monika 6rksdlc:
    block:
        "monika 6rksdlc_static"
        block:
            choice:
                3
            choice:
                5
            choice:
                7
        "monika 6dksdlc_static"
        0.06
        repeat

image monika 6rktda:
    block:
        "monika 6rktda_static"
        block:
            choice:
                3
            choice:
                5
            choice:
                7
        "monika 6dktda_static"
        0.06
        repeat

image monika 6rktdc:
    block:
        "monika 6rktdc_static"
        block:
            choice:
                3
            choice:
                5
            choice:
                7
        "monika 6dktdc_static"
        0.06
        repeat

image monika 6rktsc:
    block:
        "monika 6rktsc_static"
        block:
            choice:
                3
            choice:
                5
            choice:
                7
        "monika 6dktsc_static"
        0.06
        repeat

image monika 6rktuc:
    block:
        "monika 6rktuc_static"
        block:
            choice:
                3
            choice:
                5
            choice:
                7
        "monika 6dktuc_static"
        0.06
        repeat

image monika 6ska:
    block:
        "monika 6ska_static"
        block:
            choice:
                3
            choice:
                5
            choice:
                7
        "monika 6dka_static"
        0.06
        repeat

image monika 6sua:
    block:
        "monika 6sua_static"
        block:
            choice:
                3
            choice:
                5
            choice:
                7
        "monika 6dua_static"
        0.06
        repeat

image monika 6sub:
    block:
        "monika 6sub_static"
        block:
            choice:
                3
            choice:
                5
            choice:
                7
        "monika 6dub_static"
        0.06
        repeat

image monika 6subsa:
    block:
        "monika 6subsa_static"
        block:
            choice:
                3
            choice:
                5
            choice:
                7
        "monika 6dubsa_static"
        0.06
        repeat

image monika 6suo:
    block:
        "monika 6suo_static"
        block:
            choice:
                3
            choice:
                5
            choice:
                7
        "monika 6duo_static"
        0.06
        repeat

image monika 6suu:
    block:
        "monika 6suu_static"
        block:
            choice:
                3
            choice:
                5
            choice:
                7
        "monika 6duu_static"
        0.06
        repeat

image monika 6tftpc:
    block:
        "monika 6tftpc_static"
        block:
            choice:
                3
            choice:
                5
            choice:
                7
        "monika 6dftpc_static"
        0.06
        repeat

image monika 6tkb:
    block:
        "monika 6tkb_static"
        block:
            choice:
                3
            choice:
                5
            choice:
                7
        "monika 6dkb_static"
        0.06
        repeat

image monika 6tkbfu:
    block:
        "monika 6tkbfu_static"
        block:
            choice:
                3
            choice:
                5
            choice:
                7
        "monika 6dkbfu_static"
        0.06
        repeat

image monika 6tsbfa:
    block:
        "monika 6tsbfa_static"
        block:
            choice:
                3
            choice:
                5
            choice:
                7
        "monika 6dsbfa_static"
        0.06
        repeat

image monika 6tsbsa:
    block:
        "monika 6tsbsa_static"
        block:
            choice:
                3
            choice:
                5
            choice:
                7
        "monika 6dsbsa_static"
        0.06
        repeat

image monika 6tst:
    block:
        "monika 6tst_static"
        block:
            choice:
                3
            choice:
                5
            choice:
                7
        "monika 6dst_static"
        0.06
        repeat

image monika 6tub:
    block:
        "monika 6tub_static"
        block:
            choice:
                3
            choice:
                5
            choice:
                7
        "monika 6dub_static"
        0.06
        repeat

image monika 6tubfa:
    block:
        "monika 6tubfa_static"
        block:
            choice:
                3
            choice:
                5
            choice:
                7
        "monika 6dubfa_static"
        0.06
        repeat

image monika 6tubsa:
    block:
        "monika 6tubsa_static"
        block:
            choice:
                3
            choice:
                5
            choice:
                7
        "monika 6dubsa_static"
        0.06
        repeat

image monika 6wfw:
    block:
        "monika 6wfw_static"
        block:
            choice:
                3
            choice:
                5
            choice:
                7
        "monika 6dfw_static"
        0.06
        repeat

image monika 6wka:
    block:
        "monika 6wka_static"
        block:
            choice:
                3
            choice:
                5
            choice:
                7
        "monika 6dka_static"
        0.06
        repeat

image monika 6wub:
    block:
        "monika 6wub_static"
        block:
            choice:
                3
            choice:
                5
            choice:
                7
        "monika 6dub_static"
        0.06
        repeat

image monika 6wubfo:
    block:
        "monika 6wubfo_static"
        block:
            choice:
                3
            choice:
                5
            choice:
                7
        "monika 6dubfo_static"
        0.06
        repeat

image monika 6wubsw:
    block:
        "monika 6wubsw_static"
        block:
            choice:
                3
            choice:
                5
            choice:
                7
        "monika 6dubsw_static"
        0.06
        repeat

image monika 6wud:
    block:
        "monika 6wud_static"
        block:
            choice:
                3
            choice:
                5
            choice:
                7
        "monika 6dud_static"
        0.06
        repeat

image monika 6wuo:
    block:
        "monika 6wuo_static"
        block:
            choice:
                3
            choice:
                5
            choice:
                7
        "monika 6duo_static"
        0.06
        repeat

image monika 7efc:
    block:
        "monika 7efc_static"
        block:
            choice:
                3
            choice:
                5
            choice:
                7
        "monika 7dfc_static"
        0.06
        repeat

image monika 7eka:
    block:
        "monika 7eka_static"
        block:
            choice:
                3
            choice:
                5
            choice:
                7
        "monika 7dka_static"
        0.06
        repeat

image monika 7ekc:
    block:
        "monika 7ekc_static"
        block:
            choice:
                3
            choice:
                5
            choice:
                7
        "monika 7dkc_static"
        0.06
        repeat

image monika 7ekd:
    block:
        "monika 7ekd_static"
        block:
            choice:
                3
            choice:
                5
            choice:
                7
        "monika 7dkd_static"
        0.06
        repeat

image monika 7eksdla:
    block:
        "monika 7eksdla_static"
        block:
            choice:
                3
            choice:
                5
            choice:
                7
        "monika 7dksdla_static"
        0.06
        repeat

image monika 7eksdlc:
    block:
        "monika 7eksdlc_static"
        block:
            choice:
                3
            choice:
                5
            choice:
                7
        "monika 7dksdlc_static"
        0.06
        repeat

image monika 7eksdld:
    block:
        "monika 7eksdld_static"
        block:
            choice:
                3
            choice:
                5
            choice:
                7
        "monika 7dksdld_static"
        0.06
        repeat

image monika 7eua:
    block:
        "monika 7eua_static"
        block:
            choice:
                3
            choice:
                5
            choice:
                7
        "monika 7dua_static"
        0.06
        repeat

image monika 7eub:
    block:
        "monika 7eub_static"
        block:
            choice:
                3
            choice:
                5
            choice:
                7
        "monika 7dub_static"
        0.06
        repeat

image monika 7eud:
    block:
        "monika 7eud_static"
        block:
            choice:
                3
            choice:
                5
            choice:
                7
        "monika 7dud_static"
        0.06
        repeat

image monika 7rkbfsdlb:
    block:
        "monika 7rkbfsdlb_static"
        block:
            choice:
                3
            choice:
                5
            choice:
                7
        "monika 7dkbfsdlb_static"
        0.06
        repeat

image monika 7rksdla:
    block:
        "monika 7rksdla_static"
        block:
            choice:
                3
            choice:
                5
            choice:
                7
        "monika 7dksdla_static"
        0.06
        repeat

image monika 7rksdlb:
    block:
        "monika 7rksdlb_static"
        block:
            choice:
                3
            choice:
                5
            choice:
                7
        "monika 7dksdlb_static"
        0.06
        repeat

image monika 7tubfu:
    block:
        "monika 7tubfu_static"
        block:
            choice:
                3
            choice:
                5
            choice:
                7
        "monika 7dubfu_static"
        0.06
        repeat

image monika 7wubsw:
    block:
        "monika 7wubsw_static"
        block:
            choice:
                3
            choice:
                5
            choice:
                7
        "monika 7dubsw_static"
        0.06
        repeat

