############################ AUTO-GENERATED ###################################
## DO NOT EDIT THIS FILE                                                     ##
##                                                                           ##
## This was auto-generated by the the spritemaker tool                       ##
###############################################################################

image monika 6dubsu_static = DynamicDisplayable(
    mas_drawmonika,
    character=monika_chr,
    eyebrows="up",
    eyes="closedsad",
    nose="def",
    mouth="smug",
    arms="down",
    blush="shade"
)

image monika 6dubsw_static = DynamicDisplayable(
    mas_drawmonika,
    character=monika_chr,
    eyebrows="up",
    eyes="closedsad",
    nose="def",
    mouth="wide",
    arms="down",
    blush="shade"
)

image monika 6dud_static = DynamicDisplayable(
    mas_drawmonika,
    character=monika_chr,
    eyebrows="up",
    eyes="closedsad",
    nose="def",
    mouth="small",
    arms="down"
)

image monika 6duo_static = DynamicDisplayable(
    mas_drawmonika,
    character=monika_chr,
    eyebrows="up",
    eyes="closedsad",
    nose="def",
    mouth="gasp",
    arms="down"
)

image monika 6duu_static = DynamicDisplayable(
    mas_drawmonika,
    character=monika_chr,
    eyebrows="up",
    eyes="closedsad",
    nose="def",
    mouth="smug",
    arms="down"
)

image monika 6eftsc_static = DynamicDisplayable(
    mas_drawmonika,
    character=monika_chr,
    eyebrows="furrowed",
    eyes="normal",
    nose="def",
    mouth="smirk",
    arms="down",
    tears="streaming"
)

image monika 6eka_static = DynamicDisplayable(
    mas_drawmonika,
    character=monika_chr,
    eyebrows="knit",
    eyes="normal",
    nose="def",
    mouth="smile",
    arms="down",
    head="e",
    left="1l",
    right="1r"
)

image monika 6ekbfa_static = DynamicDisplayable(
    mas_drawmonika,
    character=monika_chr,
    eyebrows="knit",
    eyes="normal",
    nose="def",
    mouth="smile",
    arms="down",
    head="e",
    left="1l",
    right="1r",
    blush="full"
)

image monika 6ekbfd_static = DynamicDisplayable(
    mas_drawmonika,
    character=monika_chr,
    eyebrows="knit",
    eyes="normal",
    nose="def",
    mouth="small",
    arms="down",
    head="g",
    left="1l",
    right="1r",
    blush="full"
)

image monika 6ekbsa_static = DynamicDisplayable(
    mas_drawmonika,
    character=monika_chr,
    eyebrows="knit",
    eyes="normal",
    nose="def",
    mouth="smile",
    arms="down",
    head="e",
    left="1l",
    right="1r",
    blush="shade"
)

image monika 6ekbsu_static = DynamicDisplayable(
    mas_drawmonika,
    character=monika_chr,
    eyebrows="knit",
    eyes="normal",
    nose="def",
    mouth="smug",
    arms="down",
    blush="shade"
)

image monika 6ekc_static = DynamicDisplayable(
    mas_drawmonika,
    character=monika_chr,
    eyebrows="knit",
    eyes="normal",
    nose="def",
    mouth="smirk",
    arms="down",
    head="f",
    left="1l",
    right="1r"
)

image monika 6ekd_static = DynamicDisplayable(
    mas_drawmonika,
    character=monika_chr,
    eyebrows="knit",
    eyes="normal",
    nose="def",
    mouth="small",
    arms="down",
    head="g",
    left="1l",
    right="1r"
)

image monika 6ekp_static = DynamicDisplayable(
    mas_drawmonika,
    character=monika_chr,
    eyebrows="knit",
    eyes="normal",
    nose="def",
    mouth="pout",
    arms="down"
)

image monika 6eksdla_static = DynamicDisplayable(
    mas_drawmonika,
    character=monika_chr,
    eyebrows="knit",
    eyes="normal",
    nose="def",
    mouth="smile",
    arms="down",
    head="e",
    left="1l",
    right="1r",
    sweat="def"
)

image monika 6ektda_static = DynamicDisplayable(
    mas_drawmonika,
    character=monika_chr,
    eyebrows="knit",
    eyes="normal",
    nose="def",
    mouth="smile",
    arms="down",
    head="e",
    left="1l",
    right="1r",
    tears="dried"
)

image monika 6ektdc_static = DynamicDisplayable(
    mas_drawmonika,
    character=monika_chr,
    eyebrows="knit",
    eyes="normal",
    nose="def",
    mouth="smirk",
    arms="down",
    head="f",
    left="1l",
    right="1r",
    tears="dried"
)

image monika 6ektpa_static = DynamicDisplayable(
    mas_drawmonika,
    character=monika_chr,
    eyebrows="knit",
    eyes="normal",
    nose="def",
    mouth="smile",
    arms="down",
    head="e",
    left="1l",
    right="1r",
    tears="pooled"
)

image monika 6ektpc_static = DynamicDisplayable(
    mas_drawmonika,
    character=monika_chr,
    eyebrows="knit",
    eyes="normal",
    nose="def",
    mouth="smirk",
    arms="down",
    head="f",
    left="1l",
    right="1r",
    tears="pooled"
)

image monika 6ektsa_static = DynamicDisplayable(
    mas_drawmonika,
    character=monika_chr,
    eyebrows="knit",
    eyes="normal",
    nose="def",
    mouth="smile",
    arms="down",
    head="e",
    left="1l",
    right="1r",
    tears="streaming"
)

image monika 6ektsc_static = DynamicDisplayable(
    mas_drawmonika,
    character=monika_chr,
    eyebrows="knit",
    eyes="normal",
    nose="def",
    mouth="smirk",
    arms="down",
    head="f",
    left="1l",
    right="1r",
    tears="streaming"
)

image monika 6ektud_static = DynamicDisplayable(
    mas_drawmonika,
    character=monika_chr,
    eyebrows="knit",
    eyes="normal",
    nose="def",
    mouth="small",
    arms="down",
    head="g",
    left="1l",
    right="1r",
    tears="up"
)

image monika 6esa_static = DynamicDisplayable(
    mas_drawmonika,
    character=monika_chr,
    eyebrows="mid",
    eyes="normal",
    nose="def",
    mouth="smile",
    arms="down"
)

image monika 6esbfa_static = DynamicDisplayable(
    mas_drawmonika,
    character=monika_chr,
    eyebrows="mid",
    eyes="normal",
    nose="def",
    mouth="smile",
    arms="down",
    blush="full"
)

image monika 6eua_static = DynamicDisplayable(
    mas_drawmonika,
    character=monika_chr,
    eyebrows="up",
    eyes="normal",
    nose="def",
    mouth="smile",
    arms="down",
    head="a",
    left="1l",
    right="1r"
)

image monika 6eud_static = DynamicDisplayable(
    mas_drawmonika,
    character=monika_chr,
    eyebrows="up",
    eyes="normal",
    nose="def",
    mouth="small",
    arms="down",
    head="d",
    left="1l",
    right="1r"
)

image monika 6hft_static = DynamicDisplayable(
    mas_drawmonika,
    character=monika_chr,
    eyebrows="furrowed",
    eyes="closedhappy",
    nose="def",
    mouth="triangle",
    arms="down"
)

image monika 6hkbfa_static = DynamicDisplayable(
    mas_drawmonika,
    character=monika_chr,
    eyebrows="knit",
    eyes="closedhappy",
    nose="def",
    mouth="smile",
    arms="down",
    blush="full"
)

image monika 6hkbsu_static = DynamicDisplayable(
    mas_drawmonika,
    character=monika_chr,
    eyebrows="knit",
    eyes="closedhappy",
    nose="def",
    mouth="smug",
    arms="down",
    blush="shade"
)

image monika 6hksdlb_static = DynamicDisplayable(
    mas_drawmonika,
    character=monika_chr,
    eyebrows="knit",
    eyes="closedhappy",
    nose="def",
    mouth="big",
    arms="down",
    head="l",
    left="1l",
    right="1r",
    sweat="def"
)

image monika 6hua_static = DynamicDisplayable(
    mas_drawmonika,
    character=monika_chr,
    eyebrows="up",
    eyes="closedhappy",
    nose="def",
    mouth="smile",
    arms="down",
    head="j",
    left="1l",
    right="1r"
)

image monika 6hub_static = DynamicDisplayable(
    mas_drawmonika,
    character=monika_chr,
    eyebrows="up",
    eyes="closedhappy",
    nose="def",
    mouth="big",
    arms="down",
    head="k",
    left="1l",
    right="1r"
)

image monika 6hubfa_static = DynamicDisplayable(
    mas_drawmonika,
    character=monika_chr,
    eyebrows="up",
    eyes="closedhappy",
    nose="def",
    mouth="smile",
    arms="down",
    head="j",
    left="1l",
    right="1r",
    blush="full"
)

image monika 6hubfb_static = DynamicDisplayable(
    mas_drawmonika,
    character=monika_chr,
    eyebrows="up",
    eyes="closedhappy",
    nose="def",
    mouth="big",
    arms="down",
    head="k",
    left="1l",
    right="1r",
    blush="full"
)

image monika 6lftsc_static = DynamicDisplayable(
    mas_drawmonika,
    character=monika_chr,
    eyebrows="furrowed",
    eyes="left",
    nose="def",
    mouth="smirk",
    arms="down",
    tears="streaming"
)

image monika 6lkc_static = DynamicDisplayable(
    mas_drawmonika,
    character=monika_chr,
    eyebrows="knit",
    eyes="left",
    nose="def",
    mouth="smirk",
    arms="down",
    head="o",
    left="1l",
    right="1r"
)

image monika 6lktdc_static = DynamicDisplayable(
    mas_drawmonika,
    character=monika_chr,
    eyebrows="knit",
    eyes="left",
    nose="def",
    mouth="smirk",
    arms="down",
    head="o",
    left="1l",
    right="1r",
    tears="dried"
)

image monika 6lktsc_static = DynamicDisplayable(
    mas_drawmonika,
    character=monika_chr,
    eyebrows="knit",
    eyes="left",
    nose="def",
    mouth="smirk",
    arms="down",
    head="o",
    left="1l",
    right="1r",
    tears="streaming"
)

image monika 6rka_static = DynamicDisplayable(
    mas_drawmonika,
    character=monika_chr,
    eyebrows="knit",
    eyes="right",
    nose="def",
    mouth="smile",
    arms="down"
)

image monika 6rkbfa_static = DynamicDisplayable(
    mas_drawmonika,
    character=monika_chr,
    eyebrows="knit",
    eyes="right",
    nose="def",
    mouth="smile",
    arms="down",
    blush="full"
)

image monika 6rkbfd_static = DynamicDisplayable(
    mas_drawmonika,
    character=monika_chr,
    eyebrows="knit",
    eyes="right",
    nose="def",
    mouth="small",
    arms="down",
    blush="full"
)

image monika 6rkc_static = DynamicDisplayable(
    mas_drawmonika,
    character=monika_chr,
    eyebrows="knit",
    eyes="right",
    nose="def",
    mouth="smirk",
    arms="down"
)

image monika 6rksdla_static = DynamicDisplayable(
    mas_drawmonika,
    character=monika_chr,
    eyebrows="knit",
    eyes="right",
    nose="def",
    mouth="smile",
    arms="down",
    sweat="def"
)

image monika 6rksdlc_static = DynamicDisplayable(
    mas_drawmonika,
    character=monika_chr,
    eyebrows="knit",
    eyes="right",
    nose="def",
    mouth="smirk",
    arms="down",
    sweat="def"
)

image monika 6rktda_static = DynamicDisplayable(
    mas_drawmonika,
    character=monika_chr,
    eyebrows="knit",
    eyes="right",
    nose="def",
    mouth="smile",
    arms="down",
    tears="dried"
)

image monika 6rktdc_static = DynamicDisplayable(
    mas_drawmonika,
    character=monika_chr,
    eyebrows="knit",
    eyes="right",
    nose="def",
    mouth="smirk",
    arms="down",
    tears="dried"
)

image monika 6rktsc_static = DynamicDisplayable(
    mas_drawmonika,
    character=monika_chr,
    eyebrows="knit",
    eyes="right",
    nose="def",
    mouth="smirk",
    arms="down",
    tears="streaming"
)

image monika 6rktuc_static = DynamicDisplayable(
    mas_drawmonika,
    character=monika_chr,
    eyebrows="knit",
    eyes="right",
    nose="def",
    mouth="smirk",
    arms="down",
    tears="up"
)

image monika 6ska_static = DynamicDisplayable(
    mas_drawmonika,
    character=monika_chr,
    eyebrows="knit",
    eyes="sparkle",
    nose="def",
    mouth="smile",
    arms="down"
)

image monika 6sua_static = DynamicDisplayable(
    mas_drawmonika,
    character=monika_chr,
    eyebrows="up",
    eyes="sparkle",
    nose="def",
    mouth="smile",
    arms="down"
)

image monika 6sub_static = DynamicDisplayable(
    mas_drawmonika,
    character=monika_chr,
    eyebrows="up",
    eyes="sparkle",
    nose="def",
    mouth="big",
    arms="down"
)

image monika 6suo_static = DynamicDisplayable(
    mas_drawmonika,
    character=monika_chr,
    eyebrows="up",
    eyes="sparkle",
    nose="def",
    mouth="gasp",
    arms="down"
)

image monika 6suu_static = DynamicDisplayable(
    mas_drawmonika,
    character=monika_chr,
    eyebrows="up",
    eyes="sparkle",
    nose="def",
    mouth="smug",
    arms="down"
)

image monika 6tftpc_static = DynamicDisplayable(
    mas_drawmonika,
    character=monika_chr,
    eyebrows="furrowed",
    eyes="smug",
    nose="def",
    mouth="smirk",
    arms="down",
    tears="pooled"
)

image monika 6tkb_static = DynamicDisplayable(
    mas_drawmonika,
    character=monika_chr,
    eyebrows="knit",
    eyes="smug",
    nose="def",
    mouth="big",
    arms="down"
)

image monika 6tkbfu_static = DynamicDisplayable(
    mas_drawmonika,
    character=monika_chr,
    eyebrows="knit",
    eyes="smug",
    nose="def",
    mouth="smug",
    arms="down",
    blush="full"
)

image monika 6tsbfa_static = DynamicDisplayable(
    mas_drawmonika,
    character=monika_chr,
    eyebrows="mid",
    eyes="smug",
    nose="def",
    mouth="smile",
    arms="down",
    blush="full"
)

image monika 6tsbsa_static = DynamicDisplayable(
    mas_drawmonika,
    character=monika_chr,
    eyebrows="mid",
    eyes="smug",
    nose="def",
    mouth="smile",
    arms="down",
    blush="shade"
)

image monika 6tst_static = DynamicDisplayable(
    mas_drawmonika,
    character=monika_chr,
    eyebrows="mid",
    eyes="smug",
    nose="def",
    mouth="triangle",
    arms="down"
)

image monika 6tub_static = DynamicDisplayable(
    mas_drawmonika,
    character=monika_chr,
    eyebrows="up",
    eyes="smug",
    nose="def",
    mouth="big",
    arms="down"
)

image monika 6tubfa_static = DynamicDisplayable(
    mas_drawmonika,
    character=monika_chr,
    eyebrows="up",
    eyes="smug",
    nose="def",
    mouth="smile",
    arms="down",
    blush="full"
)

image monika 6tubsa_static = DynamicDisplayable(
    mas_drawmonika,
    character=monika_chr,
    eyebrows="up",
    eyes="smug",
    nose="def",
    mouth="smile",
    arms="down",
    blush="shade"
)

image monika 6wfw_static = DynamicDisplayable(
    mas_drawmonika,
    character=monika_chr,
    eyebrows="furrowed",
    eyes="wide",
    nose="def",
    mouth="wide",
    arms="down"
)

image monika 6wka_static = DynamicDisplayable(
    mas_drawmonika,
    character=monika_chr,
    eyebrows="knit",
    eyes="wide",
    nose="def",
    mouth="smile",
    arms="down"
)

image monika 6wub_static = DynamicDisplayable(
    mas_drawmonika,
    character=monika_chr,
    eyebrows="up",
    eyes="wide",
    nose="def",
    mouth="big",
    arms="down"
)

image monika 6wubfo_static = DynamicDisplayable(
    mas_drawmonika,
    character=monika_chr,
    eyebrows="up",
    eyes="wide",
    nose="def",
    mouth="gasp",
    arms="down",
    blush="full"
)

image monika 6wubsw_static = DynamicDisplayable(
    mas_drawmonika,
    character=monika_chr,
    eyebrows="up",
    eyes="wide",
    nose="def",
    mouth="wide",
    arms="down",
    blush="shade"
)

image monika 6wud_static = DynamicDisplayable(
    mas_drawmonika,
    character=monika_chr,
    eyebrows="up",
    eyes="wide",
    nose="def",
    mouth="small",
    arms="down"
)

image monika 6wuo_static = DynamicDisplayable(
    mas_drawmonika,
    character=monika_chr,
    eyebrows="up",
    eyes="wide",
    nose="def",
    mouth="gasp",
    arms="down"
)

