############################ AUTO-GENERATED ###################################
## DO NOT EDIT THIS FILE                                                     ##
##                                                                           ##
## This was auto-generated by the the spritemaker tool                       ##
###############################################################################

image monika 4wubfb_static = DynamicDisplayable(
    mas_drawmonika_rk,
    character=monika_chr,
    eyebrows="up",
    eyes="wide",
    nose="def",
    mouth="big",
    arms="pointright",
    blush="full"
)

image monika 4wubfsdld_static = DynamicDisplayable(
    mas_drawmonika_rk,
    character=monika_chr,
    eyebrows="up",
    eyes="wide",
    nose="def",
    mouth="small",
    arms="pointright",
    blush="full",
    sweat="def"
)

image monika 4wubso_static = DynamicDisplayable(
    mas_drawmonika_rk,
    character=monika_chr,
    eyebrows="up",
    eyes="wide",
    nose="def",
    mouth="gasp",
    arms="pointright",
    blush="shade"
)

image monika 4wubsw_static = DynamicDisplayable(
    mas_drawmonika_rk,
    character=monika_chr,
    eyebrows="up",
    eyes="wide",
    nose="def",
    mouth="wide",
    arms="pointright",
    blush="shade"
)

image monika 4wuc_static = DynamicDisplayable(
    mas_drawmonika_rk,
    character=monika_chr,
    eyebrows="up",
    eyes="wide",
    nose="def",
    mouth="smirk",
    arms="pointright"
)

image monika 4wud_static = DynamicDisplayable(
    mas_drawmonika_rk,
    character=monika_chr,
    eyebrows="up",
    eyes="wide",
    nose="def",
    mouth="small",
    arms="pointright"
)

image monika 4wuo_static = DynamicDisplayable(
    mas_drawmonika_rk,
    character=monika_chr,
    eyebrows="up",
    eyes="wide",
    nose="def",
    mouth="gasp",
    arms="pointright"
)

image monika 4wuw_static = DynamicDisplayable(
    mas_drawmonika_rk,
    character=monika_chr,
    eyebrows="up",
    eyes="wide",
    nose="def",
    mouth="wide",
    arms="pointright"
)

image monika 5dfa_static = DynamicDisplayable(
    mas_drawmonika_rk,
    character=monika_chr,
    eyebrows="furrowed",
    eyes="closedsad",
    nose="def",
    mouth="smile",
    arms="def",
    lean="def",
    single="3a"
)

image monika 5dfc_static = DynamicDisplayable(
    mas_drawmonika_rk,
    character=monika_chr,
    eyebrows="furrowed",
    eyes="closedsad",
    nose="def",
    mouth="smirk",
    arms="def",
    lean="def",
    single="3b"
)

image monika 5dka_static = DynamicDisplayable(
    mas_drawmonika_rk,
    character=monika_chr,
    eyebrows="knit",
    eyes="closedsad",
    nose="def",
    mouth="smile",
    arms="def",
    lean="def",
    single="3a"
)

image monika 5dkbfa_static = DynamicDisplayable(
    mas_drawmonika_rk,
    character=monika_chr,
    eyebrows="knit",
    eyes="closedsad",
    nose="def",
    mouth="smile",
    arms="def",
    lean="def",
    single="3a",
    blush="full"
)

image monika 5dkbfb_static = DynamicDisplayable(
    mas_drawmonika_rk,
    character=monika_chr,
    eyebrows="knit",
    eyes="closedsad",
    nose="def",
    mouth="big",
    arms="def",
    lean="def",
    single="3b",
    blush="full"
)

image monika 5dkbfu_static = DynamicDisplayable(
    mas_drawmonika_rk,
    character=monika_chr,
    eyebrows="knit",
    eyes="closedsad",
    nose="def",
    mouth="smug",
    arms="def",
    lean="def",
    single="3a",
    blush="full"
)

image monika 5dkbla_static = DynamicDisplayable(
    mas_drawmonika_rk,
    character=monika_chr,
    eyebrows="knit",
    eyes="closedsad",
    nose="def",
    mouth="smile",
    arms="def",
    lean="def",
    single="3a",
    blush="lines"
)

image monika 5dkblu_static = DynamicDisplayable(
    mas_drawmonika_rk,
    character=monika_chr,
    eyebrows="knit",
    eyes="closedsad",
    nose="def",
    mouth="smug",
    arms="def",
    lean="def",
    single="3a",
    blush="lines"
)

image monika 5dkbsa_static = DynamicDisplayable(
    mas_drawmonika_rk,
    character=monika_chr,
    eyebrows="knit",
    eyes="closedsad",
    nose="def",
    mouth="smile",
    arms="def",
    lean="def",
    single="3a",
    blush="shade"
)

image monika 5dkbsu_static = DynamicDisplayable(
    mas_drawmonika_rk,
    character=monika_chr,
    eyebrows="knit",
    eyes="closedsad",
    nose="def",
    mouth="smug",
    arms="def",
    lean="def",
    single="3a",
    blush="shade"
)

image monika 5dkc_static = DynamicDisplayable(
    mas_drawmonika_rk,
    character=monika_chr,
    eyebrows="knit",
    eyes="closedsad",
    nose="def",
    mouth="smirk",
    arms="def",
    lean="def",
    single="3b"
)

image monika 5dsa_static = DynamicDisplayable(
    mas_drawmonika_rk,
    character=monika_chr,
    eyebrows="mid",
    eyes="closedsad",
    nose="def",
    mouth="smile",
    arms="def",
    lean="def",
    single="3a"
)

image monika 5dsbfa_static = DynamicDisplayable(
    mas_drawmonika_rk,
    character=monika_chr,
    eyebrows="mid",
    eyes="closedsad",
    nose="def",
    mouth="smile",
    arms="def",
    lean="def",
    single="3a",
    blush="full"
)

image monika 5dsbfu_static = DynamicDisplayable(
    mas_drawmonika_rk,
    character=monika_chr,
    eyebrows="mid",
    eyes="closedsad",
    nose="def",
    mouth="smug",
    arms="def",
    lean="def",
    single="3a",
    blush="full"
)

image monika 5dsbsu_static = DynamicDisplayable(
    mas_drawmonika_rk,
    character=monika_chr,
    eyebrows="mid",
    eyes="closedsad",
    nose="def",
    mouth="smug",
    arms="def",
    lean="def",
    single="3a",
    blush="shade"
)

image monika 5dsc_static = DynamicDisplayable(
    mas_drawmonika_rk,
    character=monika_chr,
    eyebrows="mid",
    eyes="closedsad",
    nose="def",
    mouth="smirk",
    arms="def",
    lean="def",
    single="3b"
)

image monika 5dsu_static = DynamicDisplayable(
    mas_drawmonika_rk,
    character=monika_chr,
    eyebrows="mid",
    eyes="closedsad",
    nose="def",
    mouth="smug",
    arms="def",
    lean="def",
    single="3a"
)

image monika 5dtu_static = DynamicDisplayable(
    mas_drawmonika_rk,
    character=monika_chr,
    eyebrows="think",
    eyes="closedsad",
    nose="def",
    mouth="smug",
    arms="def",
    lean="def",
    single="3a"
)

image monika 5dua_static = DynamicDisplayable(
    mas_drawmonika_rk,
    character=monika_chr,
    eyebrows="up",
    eyes="closedsad",
    nose="def",
    mouth="smile",
    arms="def",
    lean="def",
    single="3a"
)

image monika 5dub_static = DynamicDisplayable(
    mas_drawmonika_rk,
    character=monika_chr,
    eyebrows="up",
    eyes="closedsad",
    nose="def",
    mouth="big",
    arms="def",
    lean="def",
    single="3b"
)

image monika 5dubfa_static = DynamicDisplayable(
    mas_drawmonika_rk,
    character=monika_chr,
    eyebrows="up",
    eyes="closedsad",
    nose="def",
    mouth="smile",
    arms="def",
    lean="def",
    single="3a",
    blush="full"
)

image monika 5dubfb_static = DynamicDisplayable(
    mas_drawmonika_rk,
    character=monika_chr,
    eyebrows="up",
    eyes="closedsad",
    nose="def",
    mouth="big",
    arms="def",
    lean="def",
    single="3b",
    blush="full"
)

image monika 5dubfsdrb_static = DynamicDisplayable(
    mas_drawmonika_rk,
    character=monika_chr,
    eyebrows="up",
    eyes="closedsad",
    nose="def",
    mouth="big",
    arms="def",
    lean="def",
    single="3b",
    blush="full",
    sweat="right"
)

image monika 5dubfsdru_static = DynamicDisplayable(
    mas_drawmonika_rk,
    character=monika_chr,
    eyebrows="up",
    eyes="closedsad",
    nose="def",
    mouth="smug",
    arms="def",
    lean="def",
    single="3a",
    blush="full",
    sweat="right"
)

image monika 5dubfu_static = DynamicDisplayable(
    mas_drawmonika_rk,
    character=monika_chr,
    eyebrows="up",
    eyes="closedsad",
    nose="def",
    mouth="smug",
    arms="def",
    lean="def",
    single="3a",
    blush="full"
)

image monika 5dubfw_static = DynamicDisplayable(
    mas_drawmonika_rk,
    character=monika_chr,
    eyebrows="up",
    eyes="closedsad",
    nose="def",
    mouth="wide",
    arms="def",
    lean="def",
    single="3b",
    blush="full"
)

image monika 5dubla_static = DynamicDisplayable(
    mas_drawmonika_rk,
    character=monika_chr,
    eyebrows="up",
    eyes="closedsad",
    nose="def",
    mouth="smile",
    arms="def",
    lean="def",
    single="3a",
    blush="lines"
)

image monika 5dubsa_static = DynamicDisplayable(
    mas_drawmonika_rk,
    character=monika_chr,
    eyebrows="up",
    eyes="closedsad",
    nose="def",
    mouth="smile",
    arms="def",
    lean="def",
    single="3a",
    blush="shade"
)

image monika 5dubsb_static = DynamicDisplayable(
    mas_drawmonika_rk,
    character=monika_chr,
    eyebrows="up",
    eyes="closedsad",
    nose="def",
    mouth="big",
    arms="def",
    lean="def",
    single="3b",
    blush="shade"
)

image monika 5duc_static = DynamicDisplayable(
    mas_drawmonika_rk,
    character=monika_chr,
    eyebrows="up",
    eyes="closedsad",
    nose="def",
    mouth="smirk",
    arms="def",
    lean="def",
    single="3b"
)

image monika 5dusdrb_static = DynamicDisplayable(
    mas_drawmonika_rk,
    character=monika_chr,
    eyebrows="up",
    eyes="closedsad",
    nose="def",
    mouth="big",
    arms="def",
    lean="def",
    single="3b",
    sweat="right"
)

image monika 5dusdru_static = DynamicDisplayable(
    mas_drawmonika_rk,
    character=monika_chr,
    eyebrows="up",
    eyes="closedsad",
    nose="def",
    mouth="smug",
    arms="def",
    lean="def",
    single="3a",
    sweat="right"
)

image monika 5duu_static = DynamicDisplayable(
    mas_drawmonika_rk,
    character=monika_chr,
    eyebrows="up",
    eyes="closedsad",
    nose="def",
    mouth="smug",
    arms="def",
    lean="def",
    single="3a"
)

image monika 5duw_static = DynamicDisplayable(
    mas_drawmonika_rk,
    character=monika_chr,
    eyebrows="up",
    eyes="closedsad",
    nose="def",
    mouth="wide",
    arms="def",
    lean="def",
    single="3b"
)

image monika 5efa_static = DynamicDisplayable(
    mas_drawmonika_rk,
    character=monika_chr,
    eyebrows="furrowed",
    eyes="normal",
    nose="def",
    mouth="smile",
    arms="def",
    lean="def",
    single="3a"
)

image monika 5eka_static = DynamicDisplayable(
    mas_drawmonika_rk,
    character=monika_chr,
    eyebrows="knit",
    eyes="normal",
    nose="def",
    mouth="smile",
    arms="def",
    lean="def",
    single="3a"
)

image monika 5ekbfa_static = DynamicDisplayable(
    mas_drawmonika_rk,
    character=monika_chr,
    eyebrows="knit",
    eyes="normal",
    nose="def",
    mouth="smile",
    arms="def",
    lean="def",
    single="3a",
    blush="full"
)

image monika 5ekbfu_static = DynamicDisplayable(
    mas_drawmonika_rk,
    character=monika_chr,
    eyebrows="knit",
    eyes="normal",
    nose="def",
    mouth="smug",
    arms="def",
    lean="def",
    single="3a",
    blush="full"
)

image monika 5ekbla_static = DynamicDisplayable(
    mas_drawmonika_rk,
    character=monika_chr,
    eyebrows="knit",
    eyes="normal",
    nose="def",
    mouth="smile",
    arms="def",
    lean="def",
    single="3a",
    blush="lines"
)

image monika 5ekbsa_static = DynamicDisplayable(
    mas_drawmonika_rk,
    character=monika_chr,
    eyebrows="knit",
    eyes="normal",
    nose="def",
    mouth="smile",
    arms="def",
    lean="def",
    single="3a",
    blush="shade"
)

image monika 5ekbsu_static = DynamicDisplayable(
    mas_drawmonika_rk,
    character=monika_chr,
    eyebrows="knit",
    eyes="normal",
    nose="def",
    mouth="smug",
    arms="def",
    lean="def",
    single="3a",
    blush="shade"
)

image monika 5esbfa_static = DynamicDisplayable(
    mas_drawmonika_rk,
    character=monika_chr,
    eyebrows="mid",
    eyes="normal",
    nose="def",
    mouth="smile",
    arms="def",
    lean="def",
    single="3a",
    blush="full"
)

image monika 5esbfu_static = DynamicDisplayable(
    mas_drawmonika_rk,
    character=monika_chr,
    eyebrows="mid",
    eyes="normal",
    nose="def",
    mouth="smug",
    arms="def",
    lean="def",
    single="3a",
    blush="full"
)

image monika 5esu_static = DynamicDisplayable(
    mas_drawmonika_rk,
    character=monika_chr,
    eyebrows="mid",
    eyes="normal",
    nose="def",
    mouth="smug",
    arms="def",
    lean="def",
    single="3a"
)

image monika 5eua_static = DynamicDisplayable(
    mas_drawmonika_rk,
    character=monika_chr,
    eyebrows="up",
    eyes="normal",
    nose="def",
    mouth="smile",
    arms="def",
    lean="def",
    single="3a"
)

image monika 5eub_static = DynamicDisplayable(
    mas_drawmonika_rk,
    character=monika_chr,
    eyebrows="up",
    eyes="normal",
    nose="def",
    mouth="big",
    arms="def",
    lean="def",
    single="3b"
)

image monika 5eubfa_static = DynamicDisplayable(
    mas_drawmonika_rk,
    character=monika_chr,
    eyebrows="up",
    eyes="normal",
    nose="def",
    mouth="smile",
    arms="def",
    lean="def",
    single="3a",
    blush="full"
)

image monika 5eubfb_static = DynamicDisplayable(
    mas_drawmonika_rk,
    character=monika_chr,
    eyebrows="up",
    eyes="normal",
    nose="def",
    mouth="big",
    arms="def",
    lean="def",
    single="3b",
    blush="full"
)

image monika 5eubfu_static = DynamicDisplayable(
    mas_drawmonika_rk,
    character=monika_chr,
    eyebrows="up",
    eyes="normal",
    nose="def",
    mouth="smug",
    arms="def",
    lean="def",
    single="3a",
    blush="full"
)

image monika 5eubla_static = DynamicDisplayable(
    mas_drawmonika_rk,
    character=monika_chr,
    eyebrows="up",
    eyes="normal",
    nose="def",
    mouth="smile",
    arms="def",
    lean="def",
    single="3a",
    blush="lines"
)

image monika 5eubsa_static = DynamicDisplayable(
    mas_drawmonika_rk,
    character=monika_chr,
    eyebrows="up",
    eyes="normal",
    nose="def",
    mouth="smile",
    arms="def",
    lean="def",
    single="3a",
    blush="shade"
)

image monika 5euc_static = DynamicDisplayable(
    mas_drawmonika_rk,
    character=monika_chr,
    eyebrows="up",
    eyes="normal",
    nose="def",
    mouth="smirk",
    arms="def",
    lean="def",
    single="3b"
)

image monika 5hfb_static = DynamicDisplayable(
    mas_drawmonika_rk,
    character=monika_chr,
    eyebrows="furrowed",
    eyes="closedhappy",
    nose="def",
    mouth="big",
    arms="def",
    lean="def",
    single="3b"
)

image monika 5hkbfa_static = DynamicDisplayable(
    mas_drawmonika_rk,
    character=monika_chr,
    eyebrows="knit",
    eyes="closedhappy",
    nose="def",
    mouth="smile",
    arms="def",
    lean="def",
    single="3a",
    blush="full"
)

image monika 5hkbfb_static = DynamicDisplayable(
    mas_drawmonika_rk,
    character=monika_chr,
    eyebrows="knit",
    eyes="closedhappy",
    nose="def",
    mouth="big",
    arms="def",
    lean="def",
    single="3b",
    blush="full"
)

image monika 5hkbsa_static = DynamicDisplayable(
    mas_drawmonika_rk,
    character=monika_chr,
    eyebrows="knit",
    eyes="closedhappy",
    nose="def",
    mouth="smile",
    arms="def",
    lean="def",
    single="3a",
    blush="shade"
)

image monika 5hksdlb_static = DynamicDisplayable(
    mas_drawmonika_rk,
    character=monika_chr,
    eyebrows="knit",
    eyes="closedhappy",
    nose="def",
    mouth="big",
    arms="def",
    lean="def",
    single="3b",
    sweat="def"
)

image monika 5hua_static = DynamicDisplayable(
    mas_drawmonika_rk,
    character=monika_chr,
    eyebrows="up",
    eyes="closedhappy",
    nose="def",
    mouth="smile",
    arms="def",
    lean="def",
    single="3a"
)

image monika 5hub_static = DynamicDisplayable(
    mas_drawmonika_rk,
    character=monika_chr,
    eyebrows="up",
    eyes="closedhappy",
    nose="def",
    mouth="big",
    arms="def",
    lean="def",
    single="3b"
)

image monika 5hubfa_static = DynamicDisplayable(
    mas_drawmonika_rk,
    character=monika_chr,
    eyebrows="up",
    eyes="closedhappy",
    nose="def",
    mouth="smile",
    arms="def",
    lean="def",
    single="3a",
    blush="full"
)

image monika 5hubfb_static = DynamicDisplayable(
    mas_drawmonika_rk,
    character=monika_chr,
    eyebrows="up",
    eyes="closedhappy",
    nose="def",
    mouth="big",
    arms="def",
    lean="def",
    single="3b",
    blush="full"
)

image monika 5hubfu_static = DynamicDisplayable(
    mas_drawmonika_rk,
    character=monika_chr,
    eyebrows="up",
    eyes="closedhappy",
    nose="def",
    mouth="smug",
    arms="def",
    lean="def",
    single="3a",
    blush="full"
)

image monika 5hubsa_static = DynamicDisplayable(
    mas_drawmonika_rk,
    character=monika_chr,
    eyebrows="up",
    eyes="closedhappy",
    nose="def",
    mouth="smile",
    arms="def",
    lean="def",
    single="3a",
    blush="shade"
)

image monika 5hubsu_static = DynamicDisplayable(
    mas_drawmonika_rk,
    character=monika_chr,
    eyebrows="up",
    eyes="closedhappy",
    nose="def",
    mouth="smug",
    arms="def",
    lean="def",
    single="3a",
    blush="shade"
)

image monika 5ksbfu_static = DynamicDisplayable(
    mas_drawmonika_rk,
    character=monika_chr,
    eyebrows="mid",
    eyes="winkleft",
    nose="def",
    mouth="smug",
    arms="def",
    lean="def",
    single="3a",
    blush="full"
)

image monika 5kua_static = DynamicDisplayable(
    mas_drawmonika_rk,
    character=monika_chr,
    eyebrows="up",
    eyes="winkleft",
    nose="def",
    mouth="smile",
    arms="def",
    lean="def",
    single="3a"
)

image monika 5kubfu_static = DynamicDisplayable(
    mas_drawmonika_rk,
    character=monika_chr,
    eyebrows="up",
    eyes="winkleft",
    nose="def",
    mouth="smug",
    arms="def",
    lean="def",
    single="3a",
    blush="full"
)

image monika 5lfc_static = DynamicDisplayable(
    mas_drawmonika_rk,
    character=monika_chr,
    eyebrows="furrowed",
    eyes="left",
    nose="def",
    mouth="smirk",
    arms="def",
    lean="def",
    single="3b"
)

image monika 5lkc_static = DynamicDisplayable(
    mas_drawmonika_rk,
    character=monika_chr,
    eyebrows="knit",
    eyes="left",
    nose="def",
    mouth="smirk",
    arms="def",
    lean="def",
    single="3b"
)

image monika 5lsc_static = DynamicDisplayable(
    mas_drawmonika_rk,
    character=monika_chr,
    eyebrows="mid",
    eyes="left",
    nose="def",
    mouth="smirk",
    arms="def",
    lean="def",
    single="3b"
)

image monika 5lubfb_static = DynamicDisplayable(
    mas_drawmonika_rk,
    character=monika_chr,
    eyebrows="up",
    eyes="left",
    nose="def",
    mouth="big",
    arms="def",
    lean="def",
    single="3b",
    blush="full"
)

image monika 5lubfsdrb_static = DynamicDisplayable(
    mas_drawmonika_rk,
    character=monika_chr,
    eyebrows="up",
    eyes="left",
    nose="def",
    mouth="big",
    arms="def",
    lean="def",
    single="3b",
    blush="full",
    sweat="right"
)

image monika 5lubfsdru_static = DynamicDisplayable(
    mas_drawmonika_rk,
    character=monika_chr,
    eyebrows="up",
    eyes="left",
    nose="def",
    mouth="smug",
    arms="def",
    lean="def",
    single="3a",
    blush="full",
    sweat="right"
)

image monika 5lubfu_static = DynamicDisplayable(
    mas_drawmonika_rk,
    character=monika_chr,
    eyebrows="up",
    eyes="left",
    nose="def",
    mouth="smug",
    arms="def",
    lean="def",
    single="3a",
    blush="full"
)

image monika 5lubsa_static = DynamicDisplayable(
    mas_drawmonika_rk,
    character=monika_chr,
    eyebrows="up",
    eyes="left",
    nose="def",
    mouth="smile",
    arms="def",
    lean="def",
    single="3a",
    blush="shade"
)

image monika 5lusdrb_static = DynamicDisplayable(
    mas_drawmonika_rk,
    character=monika_chr,
    eyebrows="up",
    eyes="left",
    nose="def",
    mouth="big",
    arms="def",
    lean="def",
    single="3b",
    sweat="right"
)

image monika 5lusdru_static = DynamicDisplayable(
    mas_drawmonika_rk,
    character=monika_chr,
    eyebrows="up",
    eyes="left",
    nose="def",
    mouth="smug",
    arms="def",
    lean="def",
    single="3a",
    sweat="right"
)

image monika 5luu_static = DynamicDisplayable(
    mas_drawmonika_rk,
    character=monika_chr,
    eyebrows="up",
    eyes="left",
    nose="def",
    mouth="smug",
    arms="def",
    lean="def",
    single="3a"
)

image monika 5rfc_static = DynamicDisplayable(
    mas_drawmonika_rk,
    character=monika_chr,
    eyebrows="furrowed",
    eyes="right",
    nose="def",
    mouth="smirk",
    arms="def",
    lean="def",
    single="3b"
)

image monika 5rkbla_static = DynamicDisplayable(
    mas_drawmonika_rk,
    character=monika_chr,
    eyebrows="knit",
    eyes="right",
    nose="def",
    mouth="smile",
    arms="def",
    lean="def",
    single="3a",
    blush="lines"
)

image monika 5rkbsu_static = DynamicDisplayable(
    mas_drawmonika_rk,
    character=monika_chr,
    eyebrows="knit",
    eyes="right",
    nose="def",
    mouth="smug",
    arms="def",
    lean="def",
    single="3a",
    blush="shade"
)

image monika 5rkc_static = DynamicDisplayable(
    mas_drawmonika_rk,
    character=monika_chr,
    eyebrows="knit",
    eyes="right",
    nose="def",
    mouth="smirk",
    arms="def",
    lean="def",
    single="3b"
)

image monika 5rsc_static = DynamicDisplayable(
    mas_drawmonika_rk,
    character=monika_chr,
    eyebrows="mid",
    eyes="right",
    nose="def",
    mouth="smirk",
    arms="def",
    lean="def",
    single="3b"
)

image monika 5rub_static = DynamicDisplayable(
    mas_drawmonika_rk,
    character=monika_chr,
    eyebrows="up",
    eyes="right",
    nose="def",
    mouth="big",
    arms="def",
    lean="def",
    single="3b"
)

image monika 5rubfb_static = DynamicDisplayable(
    mas_drawmonika_rk,
    character=monika_chr,
    eyebrows="up",
    eyes="right",
    nose="def",
    mouth="big",
    arms="def",
    lean="def",
    single="3b",
    blush="full"
)

image monika 5rubfsdrb_static = DynamicDisplayable(
    mas_drawmonika_rk,
    character=monika_chr,
    eyebrows="up",
    eyes="right",
    nose="def",
    mouth="big",
    arms="def",
    lean="def",
    single="3b",
    blush="full",
    sweat="right"
)

image monika 5rubfsdru_static = DynamicDisplayable(
    mas_drawmonika_rk,
    character=monika_chr,
    eyebrows="up",
    eyes="right",
    nose="def",
    mouth="smug",
    arms="def",
    lean="def",
    single="3a",
    blush="full",
    sweat="right"
)

image monika 5rubfu_static = DynamicDisplayable(
    mas_drawmonika_rk,
    character=monika_chr,
    eyebrows="up",
    eyes="right",
    nose="def",
    mouth="smug",
    arms="def",
    lean="def",
    single="3a",
    blush="full"
)

image monika 5rusdrb_static = DynamicDisplayable(
    mas_drawmonika_rk,
    character=monika_chr,
    eyebrows="up",
    eyes="right",
    nose="def",
    mouth="big",
    arms="def",
    lean="def",
    single="3b",
    sweat="right"
)

image monika 5rusdru_static = DynamicDisplayable(
    mas_drawmonika_rk,
    character=monika_chr,
    eyebrows="up",
    eyes="right",
    nose="def",
    mouth="smug",
    arms="def",
    lean="def",
    single="3a",
    sweat="right"
)

image monika 5ruu_static = DynamicDisplayable(
    mas_drawmonika_rk,
    character=monika_chr,
    eyebrows="up",
    eyes="right",
    nose="def",
    mouth="smug",
    arms="def",
    lean="def",
    single="3a"
)

image monika 5sub_static = DynamicDisplayable(
    mas_drawmonika_rk,
    character=monika_chr,
    eyebrows="up",
    eyes="sparkle",
    nose="def",
    mouth="big",
    arms="def",
    lean="def",
    single="3b"
)

image monika 5subsb_static = DynamicDisplayable(
    mas_drawmonika_rk,
    character=monika_chr,
    eyebrows="up",
    eyes="sparkle",
    nose="def",
    mouth="big",
    arms="def",
    lean="def",
    single="3b",
    blush="shade"
)

image monika 5tkblu_static = DynamicDisplayable(
    mas_drawmonika_rk,
    character=monika_chr,
    eyebrows="knit",
    eyes="smug",
    nose="def",
    mouth="smug",
    arms="def",
    lean="def",
    single="3a",
    blush="lines"
)

image monika 5tsa_static = DynamicDisplayable(
    mas_drawmonika_rk,
    character=monika_chr,
    eyebrows="mid",
    eyes="smug",
    nose="def",
    mouth="smile",
    arms="def",
    lean="def",
    single="3a"
)

image monika 5tsbfu_static = DynamicDisplayable(
    mas_drawmonika_rk,
    character=monika_chr,
    eyebrows="mid",
    eyes="smug",
    nose="def",
    mouth="smug",
    arms="def",
    lean="def",
    single="3a",
    blush="full"
)

image monika 5tsbsu_static = DynamicDisplayable(
    mas_drawmonika_rk,
    character=monika_chr,
    eyebrows="mid",
    eyes="smug",
    nose="def",
    mouth="smug",
    arms="def",
    lean="def",
    single="3a",
    blush="shade"
)

image monika 5tsc_static = DynamicDisplayable(
    mas_drawmonika_rk,
    character=monika_chr,
    eyebrows="mid",
    eyes="smug",
    nose="def",
    mouth="smirk",
    arms="def",
    lean="def",
    single="3b"
)

image monika 5tsu_static = DynamicDisplayable(
    mas_drawmonika_rk,
    character=monika_chr,
    eyebrows="mid",
    eyes="smug",
    nose="def",
    mouth="smug",
    arms="def",
    lean="def",
    single="3a"
)

image monika 5ttu_static = DynamicDisplayable(
    mas_drawmonika_rk,
    character=monika_chr,
    eyebrows="think",
    eyes="smug",
    nose="def",
    mouth="smug",
    arms="def",
    lean="def",
    single="3a"
)

image monika 5tubfb_static = DynamicDisplayable(
    mas_drawmonika_rk,
    character=monika_chr,
    eyebrows="up",
    eyes="smug",
    nose="def",
    mouth="big",
    arms="def",
    lean="def",
    single="3b",
    blush="full"
)

image monika 5tubfu_static = DynamicDisplayable(
    mas_drawmonika_rk,
    character=monika_chr,
    eyebrows="up",
    eyes="smug",
    nose="def",
    mouth="smug",
    arms="def",
    lean="def",
    single="3a",
    blush="full"
)

image monika 5tuu_static = DynamicDisplayable(
    mas_drawmonika_rk,
    character=monika_chr,
    eyebrows="up",
    eyes="smug",
    nose="def",
    mouth="smug",
    arms="def",
    lean="def",
    single="3a"
)

image monika 5wub_static = DynamicDisplayable(
    mas_drawmonika_rk,
    character=monika_chr,
    eyebrows="up",
    eyes="wide",
    nose="def",
    mouth="big",
    arms="def",
    lean="def",
    single="3b"
)

image monika 5wubfw_static = DynamicDisplayable(
    mas_drawmonika_rk,
    character=monika_chr,
    eyebrows="up",
    eyes="wide",
    nose="def",
    mouth="wide",
    arms="def",
    lean="def",
    single="3b",
    blush="full"
)

image monika 5wuw_static = DynamicDisplayable(
    mas_drawmonika_rk,
    character=monika_chr,
    eyebrows="up",
    eyes="wide",
    nose="def",
    mouth="wide",
    arms="def",
    lean="def",
    single="3b"
)

image monika 6cfw_static = DynamicDisplayable(
    mas_drawmonika_rk,
    character=monika_chr,
    eyebrows="furrowed",
    eyes="crazy",
    nose="def",
    mouth="wide",
    arms="down"
)

image monika 6ckc_static = DynamicDisplayable(
    mas_drawmonika_rk,
    character=monika_chr,
    eyebrows="knit",
    eyes="crazy",
    nose="def",
    mouth="smirk",
    arms="down"
)

image monika 6dfc_static = DynamicDisplayable(
    mas_drawmonika_rk,
    character=monika_chr,
    eyebrows="furrowed",
    eyes="closedsad",
    nose="def",
    mouth="smirk",
    arms="down"
)

image monika 6dfd_static = DynamicDisplayable(
    mas_drawmonika_rk,
    character=monika_chr,
    eyebrows="furrowed",
    eyes="closedsad",
    nose="def",
    mouth="small",
    arms="down"
)

image monika 6dft_static = DynamicDisplayable(
    mas_drawmonika_rk,
    character=monika_chr,
    eyebrows="furrowed",
    eyes="closedsad",
    nose="def",
    mouth="triangle",
    arms="down"
)

image monika 6dftdc_static = DynamicDisplayable(
    mas_drawmonika_rk,
    character=monika_chr,
    eyebrows="furrowed",
    eyes="closedsad",
    nose="def",
    mouth="smirk",
    arms="down",
    tears="dried"
)

image monika 6dftdx_static = DynamicDisplayable(
    mas_drawmonika_rk,
    character=monika_chr,
    eyebrows="furrowed",
    eyes="closedsad",
    nose="def",
    mouth="angry",
    arms="down",
    tears="dried"
)

image monika 6dftpc_static = DynamicDisplayable(
    mas_drawmonika_rk,
    character=monika_chr,
    eyebrows="furrowed",
    eyes="closedsad",
    nose="def",
    mouth="smirk",
    arms="down",
    tears="pooled"
)

image monika 6dftsc_static = DynamicDisplayable(
    mas_drawmonika_rk,
    character=monika_chr,
    eyebrows="furrowed",
    eyes="closedsad",
    nose="def",
    mouth="smirk",
    arms="down",
    tears="streamingclosedsad"
)

image monika 6dfw_static = DynamicDisplayable(
    mas_drawmonika_rk,
    character=monika_chr,
    eyebrows="furrowed",
    eyes="closedsad",
    nose="def",
    mouth="wide",
    arms="down"
)

image monika 6dka_static = DynamicDisplayable(
    mas_drawmonika_rk,
    character=monika_chr,
    eyebrows="knit",
    eyes="closedsad",
    nose="def",
    mouth="smile",
    arms="down"
)

image monika 6dkb_static = DynamicDisplayable(
    mas_drawmonika_rk,
    character=monika_chr,
    eyebrows="knit",
    eyes="closedsad",
    nose="def",
    mouth="big",
    arms="down"
)

image monika 6dkbfa_static = DynamicDisplayable(
    mas_drawmonika_rk,
    character=monika_chr,
    eyebrows="knit",
    eyes="closedsad",
    nose="def",
    mouth="smile",
    arms="down",
    blush="full"
)

image monika 6dkbfd_static = DynamicDisplayable(
    mas_drawmonika_rk,
    character=monika_chr,
    eyebrows="knit",
    eyes="closedsad",
    nose="def",
    mouth="small",
    arms="down",
    blush="full"
)

image monika 6dkbftda_static = DynamicDisplayable(
    mas_drawmonika_rk,
    character=monika_chr,
    eyebrows="knit",
    eyes="closedsad",
    nose="def",
    mouth="smile",
    arms="down",
    blush="full",
    tears="dried"
)

image monika 6dkbftpa_static = DynamicDisplayable(
    mas_drawmonika_rk,
    character=monika_chr,
    eyebrows="knit",
    eyes="closedsad",
    nose="def",
    mouth="smile",
    arms="down",
    blush="full",
    tears="pooled"
)

image monika 6dkbfu_static = DynamicDisplayable(
    mas_drawmonika_rk,
    character=monika_chr,
    eyebrows="knit",
    eyes="closedsad",
    nose="def",
    mouth="smug",
    arms="down",
    blush="full"
)

image monika 6dkbltdu_static = DynamicDisplayable(
    mas_drawmonika_rk,
    character=monika_chr,
    eyebrows="knit",
    eyes="closedsad",
    nose="def",
    mouth="smug",
    arms="down",
    blush="lines",
    tears="dried"
)

image monika 6dkbsa_static = DynamicDisplayable(
    mas_drawmonika_rk,
    character=monika_chr,
    eyebrows="knit",
    eyes="closedsad",
    nose="def",
    mouth="smile",
    arms="down",
    blush="shade"
)

image monika 6dkbsu_static = DynamicDisplayable(
    mas_drawmonika_rk,
    character=monika_chr,
    eyebrows="knit",
    eyes="closedsad",
    nose="def",
    mouth="smug",
    arms="down",
    blush="shade"
)

image monika 6dkc_static = DynamicDisplayable(
    mas_drawmonika_rk,
    character=monika_chr,
    eyebrows="knit",
    eyes="closedsad",
    nose="def",
    mouth="smirk",
    arms="down"
)

image monika 6dkd_static = DynamicDisplayable(
    mas_drawmonika_rk,
    character=monika_chr,
    eyebrows="knit",
    eyes="closedsad",
    nose="def",
    mouth="small",
    arms="down"
)

image monika 6dko_static = DynamicDisplayable(
    mas_drawmonika_rk,
    character=monika_chr,
    eyebrows="knit",
    eyes="closedsad",
    nose="def",
    mouth="gasp",
    arms="down"
)

image monika 6dkp_static = DynamicDisplayable(
    mas_drawmonika_rk,
    character=monika_chr,
    eyebrows="knit",
    eyes="closedsad",
    nose="def",
    mouth="pout",
    arms="down"
)

image monika 6dksdla_static = DynamicDisplayable(
    mas_drawmonika_rk,
    character=monika_chr,
    eyebrows="knit",
    eyes="closedsad",
    nose="def",
    mouth="smile",
    arms="down",
    sweat="def"
)

image monika 6dksdlb_static = DynamicDisplayable(
    mas_drawmonika_rk,
    character=monika_chr,
    eyebrows="knit",
    eyes="closedsad",
    nose="def",
    mouth="big",
    arms="down",
    sweat="def"
)

image monika 6dksdlc_static = DynamicDisplayable(
    mas_drawmonika_rk,
    character=monika_chr,
    eyebrows="knit",
    eyes="closedsad",
    nose="def",
    mouth="smirk",
    arms="down",
    sweat="def"
)

image monika 6dktda_static = DynamicDisplayable(
    mas_drawmonika_rk,
    character=monika_chr,
    eyebrows="knit",
    eyes="closedsad",
    nose="def",
    mouth="smile",
    arms="down",
    tears="dried"
)

image monika 6dktdc_static = DynamicDisplayable(
    mas_drawmonika_rk,
    character=monika_chr,
    eyebrows="knit",
    eyes="closedsad",
    nose="def",
    mouth="smirk",
    arms="down",
    tears="dried"
)

image monika 6dktdu_static = DynamicDisplayable(
    mas_drawmonika_rk,
    character=monika_chr,
    eyebrows="knit",
    eyes="closedsad",
    nose="def",
    mouth="smug",
    arms="down",
    tears="dried"
)

image monika 6dktpa_static = DynamicDisplayable(
    mas_drawmonika_rk,
    character=monika_chr,
    eyebrows="knit",
    eyes="closedsad",
    nose="def",
    mouth="smile",
    arms="down",
    tears="pooled"
)

image monika 6dktpc_static = DynamicDisplayable(
    mas_drawmonika_rk,
    character=monika_chr,
    eyebrows="knit",
    eyes="closedsad",
    nose="def",
    mouth="smirk",
    arms="down",
    tears="pooled"
)

image monika 6dktpd_static = DynamicDisplayable(
    mas_drawmonika_rk,
    character=monika_chr,
    eyebrows="knit",
    eyes="closedsad",
    nose="def",
    mouth="small",
    arms="down",
    tears="pooled"
)

image monika 6dktpu_static = DynamicDisplayable(
    mas_drawmonika_rk,
    character=monika_chr,
    eyebrows="knit",
    eyes="closedsad",
    nose="def",
    mouth="smug",
    arms="down",
    tears="pooled"
)

image monika 6dktsa_static = DynamicDisplayable(
    mas_drawmonika_rk,
    character=monika_chr,
    eyebrows="knit",
    eyes="closedsad",
    nose="def",
    mouth="smile",
    arms="down",
    tears="streamingclosedsad"
)

image monika 6dktsc_static = DynamicDisplayable(
    mas_drawmonika_rk,
    character=monika_chr,
    eyebrows="knit",
    eyes="closedsad",
    nose="def",
    mouth="smirk",
    arms="down",
    tears="streamingclosedsad"
)

image monika 6dktua_static = DynamicDisplayable(
    mas_drawmonika_rk,
    character=monika_chr,
    eyebrows="knit",
    eyes="closedsad",
    nose="def",
    mouth="smile",
    arms="down",
    tears="upclosedsad"
)

image monika 6dktuc_static = DynamicDisplayable(
    mas_drawmonika_rk,
    character=monika_chr,
    eyebrows="knit",
    eyes="closedsad",
    nose="def",
    mouth="smirk",
    arms="down",
    tears="upclosedsad"
)

image monika 6dktud_static = DynamicDisplayable(
    mas_drawmonika_rk,
    character=monika_chr,
    eyebrows="knit",
    eyes="closedsad",
    nose="def",
    mouth="small",
    arms="down",
    tears="upclosedsad"
)

image monika 6dktuu_static = DynamicDisplayable(
    mas_drawmonika_rk,
    character=monika_chr,
    eyebrows="knit",
    eyes="closedsad",
    nose="def",
    mouth="smug",
    arms="down",
    tears="upclosedsad"
)

image monika 6dku_static = DynamicDisplayable(
    mas_drawmonika_rk,
    character=monika_chr,
    eyebrows="knit",
    eyes="closedsad",
    nose="def",
    mouth="smug",
    arms="down"
)

image monika 6dsa_static = DynamicDisplayable(
    mas_drawmonika_rk,
    character=monika_chr,
    eyebrows="mid",
    eyes="closedsad",
    nose="def",
    mouth="smile",
    arms="down"
)

image monika 6dsbfa_static = DynamicDisplayable(
    mas_drawmonika_rk,
    character=monika_chr,
    eyebrows="mid",
    eyes="closedsad",
    nose="def",
    mouth="smile",
    arms="down",
    blush="full"
)

image monika 6dsbsa_static = DynamicDisplayable(
    mas_drawmonika_rk,
    character=monika_chr,
    eyebrows="mid",
    eyes="closedsad",
    nose="def",
    mouth="smile",
    arms="down",
    blush="shade"
)

image monika 6dsc_static = DynamicDisplayable(
    mas_drawmonika_rk,
    character=monika_chr,
    eyebrows="mid",
    eyes="closedsad",
    nose="def",
    mouth="smirk",
    arms="down",
    head="q",
    left="1l",
    right="1r"
)

image monika 6dsd_static = DynamicDisplayable(
    mas_drawmonika_rk,
    character=monika_chr,
    eyebrows="mid",
    eyes="closedsad",
    nose="def",
    mouth="small",
    arms="down",
    head="r",
    left="1l",
    right="1r"
)

image monika 6dst_static = DynamicDisplayable(
    mas_drawmonika_rk,
    character=monika_chr,
    eyebrows="mid",
    eyes="closedsad",
    nose="def",
    mouth="triangle",
    arms="down"
)

image monika 6dstdc_static = DynamicDisplayable(
    mas_drawmonika_rk,
    character=monika_chr,
    eyebrows="mid",
    eyes="closedsad",
    nose="def",
    mouth="smirk",
    arms="down",
    head="q",
    left="1l",
    right="1r",
    tears="dried"
)

image monika 6dstsc_static = DynamicDisplayable(
    mas_drawmonika_rk,
    character=monika_chr,
    eyebrows="mid",
    eyes="closedsad",
    nose="def",
    mouth="smirk",
    arms="down",
    head="q",
    left="1l",
    right="1r",
    tears="streamingclosedsad"
)

image monika 6dua_static = DynamicDisplayable(
    mas_drawmonika_rk,
    character=monika_chr,
    eyebrows="up",
    eyes="closedsad",
    nose="def",
    mouth="smile",
    arms="down"
)

image monika 6dub_static = DynamicDisplayable(
    mas_drawmonika_rk,
    character=monika_chr,
    eyebrows="up",
    eyes="closedsad",
    nose="def",
    mouth="big",
    arms="down"
)

image monika 6dubfa_static = DynamicDisplayable(
    mas_drawmonika_rk,
    character=monika_chr,
    eyebrows="up",
    eyes="closedsad",
    nose="def",
    mouth="smile",
    arms="down",
    blush="full"
)

image monika 6dubfb_static = DynamicDisplayable(
    mas_drawmonika_rk,
    character=monika_chr,
    eyebrows="up",
    eyes="closedsad",
    nose="def",
    mouth="big",
    arms="down",
    blush="full"
)

image monika 6dubfd_static = DynamicDisplayable(
    mas_drawmonika_rk,
    character=monika_chr,
    eyebrows="up",
    eyes="closedsad",
    nose="def",
    mouth="small",
    arms="down",
    blush="full"
)

image monika 6dubfo_static = DynamicDisplayable(
    mas_drawmonika_rk,
    character=monika_chr,
    eyebrows="up",
    eyes="closedsad",
    nose="def",
    mouth="gasp",
    arms="down",
    blush="full"
)

image monika 6dubsa_static = DynamicDisplayable(
    mas_drawmonika_rk,
    character=monika_chr,
    eyebrows="up",
    eyes="closedsad",
    nose="def",
    mouth="smile",
    arms="down",
    blush="shade"
)

image monika 6dubsc_static = DynamicDisplayable(
    mas_drawmonika_rk,
    character=monika_chr,
    eyebrows="up",
    eyes="closedsad",
    nose="def",
    mouth="smirk",
    arms="down",
    blush="shade"
)

image monika 6dubsu_static = DynamicDisplayable(
    mas_drawmonika_rk,
    character=monika_chr,
    eyebrows="up",
    eyes="closedsad",
    nose="def",
    mouth="smug",
    arms="down",
    blush="shade"
)

image monika 6dubsw_static = DynamicDisplayable(
    mas_drawmonika_rk,
    character=monika_chr,
    eyebrows="up",
    eyes="closedsad",
    nose="def",
    mouth="wide",
    arms="down",
    blush="shade"
)

image monika 6dud_static = DynamicDisplayable(
    mas_drawmonika_rk,
    character=monika_chr,
    eyebrows="up",
    eyes="closedsad",
    nose="def",
    mouth="small",
    arms="down"
)

image monika 6duo_static = DynamicDisplayable(
    mas_drawmonika_rk,
    character=monika_chr,
    eyebrows="up",
    eyes="closedsad",
    nose="def",
    mouth="gasp",
    arms="down"
)

image monika 6duu_static = DynamicDisplayable(
    mas_drawmonika_rk,
    character=monika_chr,
    eyebrows="up",
    eyes="closedsad",
    nose="def",
    mouth="smug",
    arms="down"
)

image monika 6eftsc_static = DynamicDisplayable(
    mas_drawmonika_rk,
    character=monika_chr,
    eyebrows="furrowed",
    eyes="normal",
    nose="def",
    mouth="smirk",
    arms="down",
    tears="streaming"
)

image monika 6eka_static = DynamicDisplayable(
    mas_drawmonika_rk,
    character=monika_chr,
    eyebrows="knit",
    eyes="normal",
    nose="def",
    mouth="smile",
    arms="down",
    head="e",
    left="1l",
    right="1r"
)

image monika 6ekbfa_static = DynamicDisplayable(
    mas_drawmonika_rk,
    character=monika_chr,
    eyebrows="knit",
    eyes="normal",
    nose="def",
    mouth="smile",
    arms="down",
    head="e",
    left="1l",
    right="1r",
    blush="full"
)

image monika 6ekbfd_static = DynamicDisplayable(
    mas_drawmonika_rk,
    character=monika_chr,
    eyebrows="knit",
    eyes="normal",
    nose="def",
    mouth="small",
    arms="down",
    head="g",
    left="1l",
    right="1r",
    blush="full"
)

image monika 6ekbftda_static = DynamicDisplayable(
    mas_drawmonika_rk,
    character=monika_chr,
    eyebrows="knit",
    eyes="normal",
    nose="def",
    mouth="smile",
    arms="down",
    head="e",
    left="1l",
    right="1r",
    blush="full",
    tears="dried"
)

image monika 6ekbftpa_static = DynamicDisplayable(
    mas_drawmonika_rk,
    character=monika_chr,
    eyebrows="knit",
    eyes="normal",
    nose="def",
    mouth="smile",
    arms="down",
    head="e",
    left="1l",
    right="1r",
    blush="full",
    tears="pooled"
)

image monika 6ekbsa_static = DynamicDisplayable(
    mas_drawmonika_rk,
    character=monika_chr,
    eyebrows="knit",
    eyes="normal",
    nose="def",
    mouth="smile",
    arms="down",
    head="e",
    left="1l",
    right="1r",
    blush="shade"
)

image monika 6ekbsu_static = DynamicDisplayable(
    mas_drawmonika_rk,
    character=monika_chr,
    eyebrows="knit",
    eyes="normal",
    nose="def",
    mouth="smug",
    arms="down",
    blush="shade"
)

image monika 6ekc_static = DynamicDisplayable(
    mas_drawmonika_rk,
    character=monika_chr,
    eyebrows="knit",
    eyes="normal",
    nose="def",
    mouth="smirk",
    arms="down",
    head="f",
    left="1l",
    right="1r"
)

image monika 6ekd_static = DynamicDisplayable(
    mas_drawmonika_rk,
    character=monika_chr,
    eyebrows="knit",
    eyes="normal",
    nose="def",
    mouth="small",
    arms="down",
    head="g",
    left="1l",
    right="1r"
)

image monika 6eko_static = DynamicDisplayable(
    mas_drawmonika_rk,
    character=monika_chr,
    eyebrows="knit",
    eyes="normal",
    nose="def",
    mouth="gasp",
    arms="down"
)

image monika 6ekp_static = DynamicDisplayable(
    mas_drawmonika_rk,
    character=monika_chr,
    eyebrows="knit",
    eyes="normal",
    nose="def",
    mouth="pout",
    arms="down"
)

image monika 6eksdla_static = DynamicDisplayable(
    mas_drawmonika_rk,
    character=monika_chr,
    eyebrows="knit",
    eyes="normal",
    nose="def",
    mouth="smile",
    arms="down",
    head="e",
    left="1l",
    right="1r",
    sweat="def"
)

image monika 6ektda_static = DynamicDisplayable(
    mas_drawmonika_rk,
    character=monika_chr,
    eyebrows="knit",
    eyes="normal",
    nose="def",
    mouth="smile",
    arms="down",
    head="e",
    left="1l",
    right="1r",
    tears="dried"
)

image monika 6ektdc_static = DynamicDisplayable(
    mas_drawmonika_rk,
    character=monika_chr,
    eyebrows="knit",
    eyes="normal",
    nose="def",
    mouth="smirk",
    arms="down",
    head="f",
    left="1l",
    right="1r",
    tears="dried"
)

image monika 6ektpa_static = DynamicDisplayable(
    mas_drawmonika_rk,
    character=monika_chr,
    eyebrows="knit",
    eyes="normal",
    nose="def",
    mouth="smile",
    arms="down",
    head="e",
    left="1l",
    right="1r",
    tears="pooled"
)

image monika 6ektpc_static = DynamicDisplayable(
    mas_drawmonika_rk,
    character=monika_chr,
    eyebrows="knit",
    eyes="normal",
    nose="def",
    mouth="smirk",
    arms="down",
    head="f",
    left="1l",
    right="1r",
    tears="pooled"
)

image monika 6ektpd_static = DynamicDisplayable(
    mas_drawmonika_rk,
    character=monika_chr,
    eyebrows="knit",
    eyes="normal",
    nose="def",
    mouth="small",
    arms="down",
    head="g",
    left="1l",
    right="1r",
    tears="pooled"
)

image monika 6ektsa_static = DynamicDisplayable(
    mas_drawmonika_rk,
    character=monika_chr,
    eyebrows="knit",
    eyes="normal",
    nose="def",
    mouth="smile",
    arms="down",
    head="e",
    left="1l",
    right="1r",
    tears="streaming"
)

image monika 6ektsc_static = DynamicDisplayable(
    mas_drawmonika_rk,
    character=monika_chr,
    eyebrows="knit",
    eyes="normal",
    nose="def",
    mouth="smirk",
    arms="down",
    head="f",
    left="1l",
    right="1r",
    tears="streaming"
)

image monika 6ektud_static = DynamicDisplayable(
    mas_drawmonika_rk,
    character=monika_chr,
    eyebrows="knit",
    eyes="normal",
    nose="def",
    mouth="small",
    arms="down",
    head="g",
    left="1l",
    right="1r",
    tears="up"
)

image monika 6esa_static = DynamicDisplayable(
    mas_drawmonika_rk,
    character=monika_chr,
    eyebrows="mid",
    eyes="normal",
    nose="def",
    mouth="smile",
    arms="down"
)

image monika 6esbfa_static = DynamicDisplayable(
    mas_drawmonika_rk,
    character=monika_chr,
    eyebrows="mid",
    eyes="normal",
    nose="def",
    mouth="smile",
    arms="down",
    blush="full"
)

image monika 6eua_static = DynamicDisplayable(
    mas_drawmonika_rk,
    character=monika_chr,
    eyebrows="up",
    eyes="normal",
    nose="def",
    mouth="smile",
    arms="down",
    head="a",
    left="1l",
    right="1r"
)

image monika 6eub_static = DynamicDisplayable(
    mas_drawmonika_rk,
    character=monika_chr,
    eyebrows="up",
    eyes="normal",
    nose="def",
    mouth="big",
    arms="down",
    head="b",
    left="1l",
    right="1r"
)

image monika 6eud_static = DynamicDisplayable(
    mas_drawmonika_rk,
    character=monika_chr,
    eyebrows="up",
    eyes="normal",
    nose="def",
    mouth="small",
    arms="down",
    head="d",
    left="1l",
    right="1r"
)

image monika 6hft_static = DynamicDisplayable(
    mas_drawmonika_rk,
    character=monika_chr,
    eyebrows="furrowed",
    eyes="closedhappy",
    nose="def",
    mouth="triangle",
    arms="down"
)

image monika 6hkbfa_static = DynamicDisplayable(
    mas_drawmonika_rk,
    character=monika_chr,
    eyebrows="knit",
    eyes="closedhappy",
    nose="def",
    mouth="smile",
    arms="down",
    blush="full"
)

image monika 6hkbsu_static = DynamicDisplayable(
    mas_drawmonika_rk,
    character=monika_chr,
    eyebrows="knit",
    eyes="closedhappy",
    nose="def",
    mouth="smug",
    arms="down",
    blush="shade"
)

image monika 6hksdlb_static = DynamicDisplayable(
    mas_drawmonika_rk,
    character=monika_chr,
    eyebrows="knit",
    eyes="closedhappy",
    nose="def",
    mouth="big",
    arms="down",
    head="l",
    left="1l",
    right="1r",
    sweat="def"
)

image monika 6hua_static = DynamicDisplayable(
    mas_drawmonika_rk,
    character=monika_chr,
    eyebrows="up",
    eyes="closedhappy",
    nose="def",
    mouth="smile",
    arms="down",
    head="j",
    left="1l",
    right="1r"
)

image monika 6hub_static = DynamicDisplayable(
    mas_drawmonika_rk,
    character=monika_chr,
    eyebrows="up",
    eyes="closedhappy",
    nose="def",
    mouth="big",
    arms="down",
    head="k",
    left="1l",
    right="1r"
)

image monika 6hubfa_static = DynamicDisplayable(
    mas_drawmonika_rk,
    character=monika_chr,
    eyebrows="up",
    eyes="closedhappy",
    nose="def",
    mouth="smile",
    arms="down",
    head="j",
    left="1l",
    right="1r",
    blush="full"
)

image monika 6hubfb_static = DynamicDisplayable(
    mas_drawmonika_rk,
    character=monika_chr,
    eyebrows="up",
    eyes="closedhappy",
    nose="def",
    mouth="big",
    arms="down",
    head="k",
    left="1l",
    right="1r",
    blush="full"
)

image monika 6hud_static = DynamicDisplayable(
    mas_drawmonika_rk,
    character=monika_chr,
    eyebrows="up",
    eyes="closedhappy",
    nose="def",
    mouth="small",
    arms="down"
)

image monika 6lftsc_static = DynamicDisplayable(
    mas_drawmonika_rk,
    character=monika_chr,
    eyebrows="furrowed",
    eyes="left",
    nose="def",
    mouth="smirk",
    arms="down",
    tears="streaming"
)

image monika 6lkc_static = DynamicDisplayable(
    mas_drawmonika_rk,
    character=monika_chr,
    eyebrows="knit",
    eyes="left",
    nose="def",
    mouth="smirk",
    arms="down",
    head="o",
    left="1l",
    right="1r"
)

image monika 6lktdc_static = DynamicDisplayable(
    mas_drawmonika_rk,
    character=monika_chr,
    eyebrows="knit",
    eyes="left",
    nose="def",
    mouth="smirk",
    arms="down",
    head="o",
    left="1l",
    right="1r",
    tears="dried"
)

image monika 6lktpc_static = DynamicDisplayable(
    mas_drawmonika_rk,
    character=monika_chr,
    eyebrows="knit",
    eyes="left",
    nose="def",
    mouth="smirk",
    arms="down",
    head="o",
    left="1l",
    right="1r",
    tears="pooled"
)

image monika 6lktsc_static = DynamicDisplayable(
    mas_drawmonika_rk,
    character=monika_chr,
    eyebrows="knit",
    eyes="left",
    nose="def",
    mouth="smirk",
    arms="down",
    head="o",
    left="1l",
    right="1r",
    tears="streaming"
)

image monika 6lsc_static = DynamicDisplayable(
    mas_drawmonika_rk,
    character=monika_chr,
    eyebrows="mid",
    eyes="left",
    nose="def",
    mouth="smirk",
    arms="down"
)

image monika 6rka_static = DynamicDisplayable(
    mas_drawmonika_rk,
    character=monika_chr,
    eyebrows="knit",
    eyes="right",
    nose="def",
    mouth="smile",
    arms="down"
)

image monika 6rkbfa_static = DynamicDisplayable(
    mas_drawmonika_rk,
    character=monika_chr,
    eyebrows="knit",
    eyes="right",
    nose="def",
    mouth="smile",
    arms="down",
    blush="full"
)

image monika 6rkbfd_static = DynamicDisplayable(
    mas_drawmonika_rk,
    character=monika_chr,
    eyebrows="knit",
    eyes="right",
    nose="def",
    mouth="small",
    arms="down",
    blush="full"
)

image monika 6rkc_static = DynamicDisplayable(
    mas_drawmonika_rk,
    character=monika_chr,
    eyebrows="knit",
    eyes="right",
    nose="def",
    mouth="smirk",
    arms="down"
)

image monika 6rksdla_static = DynamicDisplayable(
    mas_drawmonika_rk,
    character=monika_chr,
    eyebrows="knit",
    eyes="right",
    nose="def",
    mouth="smile",
    arms="down",
    sweat="def"
)

image monika 6rksdlc_static = DynamicDisplayable(
    mas_drawmonika_rk,
    character=monika_chr,
    eyebrows="knit",
    eyes="right",
    nose="def",
    mouth="smirk",
    arms="down",
    sweat="def"
)

image monika 6rktda_static = DynamicDisplayable(
    mas_drawmonika_rk,
    character=monika_chr,
    eyebrows="knit",
    eyes="right",
    nose="def",
    mouth="smile",
    arms="down",
    tears="dried"
)

image monika 6rktdc_static = DynamicDisplayable(
    mas_drawmonika_rk,
    character=monika_chr,
    eyebrows="knit",
    eyes="right",
    nose="def",
    mouth="smirk",
    arms="down",
    tears="dried"
)

image monika 6rktsc_static = DynamicDisplayable(
    mas_drawmonika_rk,
    character=monika_chr,
    eyebrows="knit",
    eyes="right",
    nose="def",
    mouth="smirk",
    arms="down",
    tears="streaming"
)

image monika 6rktuc_static = DynamicDisplayable(
    mas_drawmonika_rk,
    character=monika_chr,
    eyebrows="knit",
    eyes="right",
    nose="def",
    mouth="smirk",
    arms="down",
    tears="up"
)

image monika 6ska_static = DynamicDisplayable(
    mas_drawmonika_rk,
    character=monika_chr,
    eyebrows="knit",
    eyes="sparkle",
    nose="def",
    mouth="smile",
    arms="down"
)

image monika 6sua_static = DynamicDisplayable(
    mas_drawmonika_rk,
    character=monika_chr,
    eyebrows="up",
    eyes="sparkle",
    nose="def",
    mouth="smile",
    arms="down"
)

image monika 6sub_static = DynamicDisplayable(
    mas_drawmonika_rk,
    character=monika_chr,
    eyebrows="up",
    eyes="sparkle",
    nose="def",
    mouth="big",
    arms="down"
)

image monika 6subsa_static = DynamicDisplayable(
    mas_drawmonika_rk,
    character=monika_chr,
    eyebrows="up",
    eyes="sparkle",
    nose="def",
    mouth="smile",
    arms="down",
    blush="shade"
)

image monika 6suo_static = DynamicDisplayable(
    mas_drawmonika_rk,
    character=monika_chr,
    eyebrows="up",
    eyes="sparkle",
    nose="def",
    mouth="gasp",
    arms="down"
)

image monika 6suu_static = DynamicDisplayable(
    mas_drawmonika_rk,
    character=monika_chr,
    eyebrows="up",
    eyes="sparkle",
    nose="def",
    mouth="smug",
    arms="down"
)

image monika 6tftpc_static = DynamicDisplayable(
    mas_drawmonika_rk,
    character=monika_chr,
    eyebrows="furrowed",
    eyes="smug",
    nose="def",
    mouth="smirk",
    arms="down",
    tears="pooled"
)

image monika 6tkb_static = DynamicDisplayable(
    mas_drawmonika_rk,
    character=monika_chr,
    eyebrows="knit",
    eyes="smug",
    nose="def",
    mouth="big",
    arms="down"
)

image monika 6tkbfu_static = DynamicDisplayable(
    mas_drawmonika_rk,
    character=monika_chr,
    eyebrows="knit",
    eyes="smug",
    nose="def",
    mouth="smug",
    arms="down",
    blush="full"
)

image monika 6tsbfa_static = DynamicDisplayable(
    mas_drawmonika_rk,
    character=monika_chr,
    eyebrows="mid",
    eyes="smug",
    nose="def",
    mouth="smile",
    arms="down",
    blush="full"
)

image monika 6tsbsa_static = DynamicDisplayable(
    mas_drawmonika_rk,
    character=monika_chr,
    eyebrows="mid",
    eyes="smug",
    nose="def",
    mouth="smile",
    arms="down",
    blush="shade"
)

image monika 6tst_static = DynamicDisplayable(
    mas_drawmonika_rk,
    character=monika_chr,
    eyebrows="mid",
    eyes="smug",
    nose="def",
    mouth="triangle",
    arms="down"
)

image monika 6tub_static = DynamicDisplayable(
    mas_drawmonika_rk,
    character=monika_chr,
    eyebrows="up",
    eyes="smug",
    nose="def",
    mouth="big",
    arms="down"
)

image monika 6tubfa_static = DynamicDisplayable(
    mas_drawmonika_rk,
    character=monika_chr,
    eyebrows="up",
    eyes="smug",
    nose="def",
    mouth="smile",
    arms="down",
    blush="full"
)

image monika 6tubsa_static = DynamicDisplayable(
    mas_drawmonika_rk,
    character=monika_chr,
    eyebrows="up",
    eyes="smug",
    nose="def",
    mouth="smile",
    arms="down",
    blush="shade"
)

image monika 6wfw_static = DynamicDisplayable(
    mas_drawmonika_rk,
    character=monika_chr,
    eyebrows="furrowed",
    eyes="wide",
    nose="def",
    mouth="wide",
    arms="down"
)

image monika 6wka_static = DynamicDisplayable(
    mas_drawmonika_rk,
    character=monika_chr,
    eyebrows="knit",
    eyes="wide",
    nose="def",
    mouth="smile",
    arms="down"
)

image monika 6wub_static = DynamicDisplayable(
    mas_drawmonika_rk,
    character=monika_chr,
    eyebrows="up",
    eyes="wide",
    nose="def",
    mouth="big",
    arms="down"
)

image monika 6wubfo_static = DynamicDisplayable(
    mas_drawmonika_rk,
    character=monika_chr,
    eyebrows="up",
    eyes="wide",
    nose="def",
    mouth="gasp",
    arms="down",
    blush="full"
)

image monika 6wubsw_static = DynamicDisplayable(
    mas_drawmonika_rk,
    character=monika_chr,
    eyebrows="up",
    eyes="wide",
    nose="def",
    mouth="wide",
    arms="down",
    blush="shade"
)

image monika 6wud_static = DynamicDisplayable(
    mas_drawmonika_rk,
    character=monika_chr,
    eyebrows="up",
    eyes="wide",
    nose="def",
    mouth="small",
    arms="down"
)

image monika 6wuo_static = DynamicDisplayable(
    mas_drawmonika_rk,
    character=monika_chr,
    eyebrows="up",
    eyes="wide",
    nose="def",
    mouth="gasp",
    arms="down"
)

image monika 7dfc_static = DynamicDisplayable(
    mas_drawmonika_rk,
    character=monika_chr,
    eyebrows="furrowed",
    eyes="closedsad",
    nose="def",
    mouth="smirk",
    arms="downleftpointright"
)

image monika 7dka_static = DynamicDisplayable(
    mas_drawmonika_rk,
    character=monika_chr,
    eyebrows="knit",
    eyes="closedsad",
    nose="def",
    mouth="smile",
    arms="downleftpointright"
)

image monika 7dkbfsdlb_static = DynamicDisplayable(
    mas_drawmonika_rk,
    character=monika_chr,
    eyebrows="knit",
    eyes="closedsad",
    nose="def",
    mouth="big",
    arms="downleftpointright",
    blush="full",
    sweat="def"
)

image monika 7dkc_static = DynamicDisplayable(
    mas_drawmonika_rk,
    character=monika_chr,
    eyebrows="knit",
    eyes="closedsad",
    nose="def",
    mouth="smirk",
    arms="downleftpointright"
)

image monika 7dkd_static = DynamicDisplayable(
    mas_drawmonika_rk,
    character=monika_chr,
    eyebrows="knit",
    eyes="closedsad",
    nose="def",
    mouth="small",
    arms="downleftpointright"
)

image monika 7dksdla_static = DynamicDisplayable(
    mas_drawmonika_rk,
    character=monika_chr,
    eyebrows="knit",
    eyes="closedsad",
    nose="def",
    mouth="smile",
    arms="downleftpointright",
    sweat="def"
)

image monika 7dksdlb_static = DynamicDisplayable(
    mas_drawmonika_rk,
    character=monika_chr,
    eyebrows="knit",
    eyes="closedsad",
    nose="def",
    mouth="big",
    arms="downleftpointright",
    sweat="def"
)

image monika 7dksdlc_static = DynamicDisplayable(
    mas_drawmonika_rk,
    character=monika_chr,
    eyebrows="knit",
    eyes="closedsad",
    nose="def",
    mouth="smirk",
    arms="downleftpointright",
    sweat="def"
)

image monika 7dksdld_static = DynamicDisplayable(
    mas_drawmonika_rk,
    character=monika_chr,
    eyebrows="knit",
    eyes="closedsad",
    nose="def",
    mouth="small",
    arms="downleftpointright",
    sweat="def"
)

image monika 7dsd_static = DynamicDisplayable(
    mas_drawmonika_rk,
    character=monika_chr,
    eyebrows="mid",
    eyes="closedsad",
    nose="def",
    mouth="small",
    arms="downleftpointright",
    head="r",
    left="1l",
    right="2r"
)

image monika 7dua_static = DynamicDisplayable(
    mas_drawmonika_rk,
    character=monika_chr,
    eyebrows="up",
    eyes="closedsad",
    nose="def",
    mouth="smile",
    arms="downleftpointright"
)

image monika 7dub_static = DynamicDisplayable(
    mas_drawmonika_rk,
    character=monika_chr,
    eyebrows="up",
    eyes="closedsad",
    nose="def",
    mouth="big",
    arms="downleftpointright"
)

image monika 7dubfu_static = DynamicDisplayable(
    mas_drawmonika_rk,
    character=monika_chr,
    eyebrows="up",
    eyes="closedsad",
    nose="def",
    mouth="smug",
    arms="downleftpointright",
    blush="full"
)

image monika 7dubsw_static = DynamicDisplayable(
    mas_drawmonika_rk,
    character=monika_chr,
    eyebrows="up",
    eyes="closedsad",
    nose="def",
    mouth="wide",
    arms="downleftpointright",
    blush="shade"
)

image monika 7dud_static = DynamicDisplayable(
    mas_drawmonika_rk,
    character=monika_chr,
    eyebrows="up",
    eyes="closedsad",
    nose="def",
    mouth="small",
    arms="downleftpointright"
)

image monika 7efc_static = DynamicDisplayable(
    mas_drawmonika_rk,
    character=monika_chr,
    eyebrows="furrowed",
    eyes="normal",
    nose="def",
    mouth="smirk",
    arms="downleftpointright"
)

image monika 7eka_static = DynamicDisplayable(
    mas_drawmonika_rk,
    character=monika_chr,
    eyebrows="knit",
    eyes="normal",
    nose="def",
    mouth="smile",
    arms="downleftpointright",
    head="e",
    left="1l",
    right="2r"
)

image monika 7ekc_static = DynamicDisplayable(
    mas_drawmonika_rk,
    character=monika_chr,
    eyebrows="knit",
    eyes="normal",
    nose="def",
    mouth="smirk",
    arms="downleftpointright",
    head="f",
    left="1l",
    right="2r"
)

image monika 7ekd_static = DynamicDisplayable(
    mas_drawmonika_rk,
    character=monika_chr,
    eyebrows="knit",
    eyes="normal",
    nose="def",
    mouth="small",
    arms="downleftpointright",
    head="g",
    left="1l",
    right="2r"
)

image monika 7eksdla_static = DynamicDisplayable(
    mas_drawmonika_rk,
    character=monika_chr,
    eyebrows="knit",
    eyes="normal",
    nose="def",
    mouth="smile",
    arms="downleftpointright",
    head="e",
    left="1l",
    right="2r",
    sweat="def"
)

image monika 7eksdlc_static = DynamicDisplayable(
    mas_drawmonika_rk,
    character=monika_chr,
    eyebrows="knit",
    eyes="normal",
    nose="def",
    mouth="smirk",
    arms="downleftpointright",
    head="f",
    left="1l",
    right="2r",
    sweat="def"
)

image monika 7eksdld_static = DynamicDisplayable(
    mas_drawmonika_rk,
    character=monika_chr,
    eyebrows="knit",
    eyes="normal",
    nose="def",
    mouth="small",
    arms="downleftpointright",
    head="g",
    left="1l",
    right="2r",
    sweat="def"
)

image monika 7eua_static = DynamicDisplayable(
    mas_drawmonika_rk,
    character=monika_chr,
    eyebrows="up",
    eyes="normal",
    nose="def",
    mouth="smile",
    arms="downleftpointright",
    head="a",
    left="1l",
    right="2r"
)

image monika 7eub_static = DynamicDisplayable(
    mas_drawmonika_rk,
    character=monika_chr,
    eyebrows="up",
    eyes="normal",
    nose="def",
    mouth="big",
    arms="downleftpointright",
    head="b",
    left="1l",
    right="2r"
)

image monika 7eud_static = DynamicDisplayable(
    mas_drawmonika_rk,
    character=monika_chr,
    eyebrows="up",
    eyes="normal",
    nose="def",
    mouth="small",
    arms="downleftpointright",
    head="d",
    left="1l",
    right="2r"
)

image monika 7hub_static = DynamicDisplayable(
    mas_drawmonika_rk,
    character=monika_chr,
    eyebrows="up",
    eyes="closedhappy",
    nose="def",
    mouth="big",
    arms="downleftpointright",
    head="k",
    left="1l",
    right="2r"
)

image monika 7hubfb_static = DynamicDisplayable(
    mas_drawmonika_rk,
    character=monika_chr,
    eyebrows="up",
    eyes="closedhappy",
    nose="def",
    mouth="big",
    arms="downleftpointright",
    head="k",
    left="1l",
    right="2r",
    blush="full"
)

image monika 7hubfu_static = DynamicDisplayable(
    mas_drawmonika_rk,
    character=monika_chr,
    eyebrows="up",
    eyes="closedhappy",
    nose="def",
    mouth="smug",
    arms="downleftpointright",
    blush="full"
)

image monika 7rkbfsdlb_static = DynamicDisplayable(
    mas_drawmonika_rk,
    character=monika_chr,
    eyebrows="knit",
    eyes="right",
    nose="def",
    mouth="big",
    arms="downleftpointright",
    blush="full",
    sweat="def"
)

image monika 7rksdla_static = DynamicDisplayable(
    mas_drawmonika_rk,
    character=monika_chr,
    eyebrows="knit",
    eyes="right",
    nose="def",
    mouth="smile",
    arms="downleftpointright",
    sweat="def"
)

image monika 7rksdlb_static = DynamicDisplayable(
    mas_drawmonika_rk,
    character=monika_chr,
    eyebrows="knit",
    eyes="right",
    nose="def",
    mouth="big",
    arms="downleftpointright",
    sweat="def"
)

image monika 7tubfu_static = DynamicDisplayable(
    mas_drawmonika_rk,
    character=monika_chr,
    eyebrows="up",
    eyes="smug",
    nose="def",
    mouth="smug",
    arms="downleftpointright",
    blush="full"
)

image monika 7wubsw_static = DynamicDisplayable(
    mas_drawmonika_rk,
    character=monika_chr,
    eyebrows="up",
    eyes="wide",
    nose="def",
    mouth="wide",
    arms="downleftpointright",
    blush="shade"
)

