# python rewrite of Multi's ATLifier
# https://github.com/multimokia/MAS-ATLifier/blob/SpriteChartMaintainer/ATLifier/Program.cs
#
#


def run()


# auto gen strings
__ZZ_AG_HEADER = """
################################# AUTO-GENERATED ##############################
## DO NOT EDIT THIS FILE                                                     ##
##                                                                           ##
## This was auto-generated by the atlgen tool                                ##
###############################################################################
#
# This is module designed for creating blinking versions of sprites.
#
"""

# TESTING
__ZZ_AG_BLOCK = """
image monika {0}{
"""
