## module with a function that pull sprites out of the sprite-chart

import os

SPRITE_PATH = "../Monika After Story/game/sprite-chart.rpy"
SAVE_PATH = "zzzz_spritelist"
SAVE_PATH_D = "zzzz_spritedict"
SAVE_PATH_IO = "../Monika After Story/game/zzzz_sprite_opt.rpy"

IMG_START = "image monika"
IMG_OUT = '"monika {0}"'

def is_sprite_line(line):
    """
    Checks if the given line is a sprite line

    NOTE: a sprite line is a line that starts with "image monika"
    
    NOTE: does not strip the given line.

    IN:
        line - line to check

    RETURNS:
        True if the given line is a sprite line, False otherwise.
    """
    return line.startswith(IMG_START)


def pull_sprite_code(line):
    """
    Pulls the sprite code from the given line.
    This checks if the given line is a sprite line before pulling the code.

    IN:
        line - line to pull sprite code

    RETURNS: the sprite code we got, if not a sprite code, we return None
    """
    if is_sprite_line(line):
        return line.split(" ")[2]

    return None


def pull_sprite_list(as_dict=False):
    """
    Goes through the sprite chart and generates a list of all the known sprite
    codes.

    NOTE:
        This does not really do any filtering, so if sprite-chart has excess
        images, they will be reflected here.

    IN:
        as_dict - if True, this will return a dict with the known sprite codes
            as keys. The values will be 0.

    RETURNS:
        list of known sprite codes, or dict if as_dict is True
    """
    sprite_list = list()

    with open(os.path.normcase(SPRITE_PATH), "r") as sprite_file:
        for line in sprite_file:
            code = pull_sprite_code(line)
            
            if code:
                sprite_list.append(code)

    if as_dict:
        # do we want a dict instead?
        sprite_dict = dict()
        
        for sprite in sprite_list:
            sprite_dict[sprite] = 0

        return sprite_dict

    # otherwise we want the lsit
    return sprite_list


def write_spritecodes(sprites):
    """
    Writes out a sprite file that just contains each sprite code out,
    one sprite code per line

    IN:
        sprites - list of sprite codes to write out.
    """
    with open(os.path.normcase(SAVE_PATH), "w") as outfile:
        for line in sprites:
            outfile.write(line + "\n")


def write_spritestats(sprites):
    """
    Writes out a sprite file that just contains each sprite code with its 
    value, one sprite code per line

    IN:
        sprites - dict of sprite codes to write out
    """
    with open(os.path.normcase(SAVE_PATH_D), "w") as outfile:
        for code in sprites:
            outfile.write("{0}: {1}\n".format(code, sprites[code]))


def write_zz_sprite_opt(sprites):
    """
    Writes out a sprite file that can be used in renpy to optimize sprites
    using image prediction.

    IN:
        sprites - list of sprite codes to write out.
    """
    with open(os.path.normcase(SAVE_PATH_IO), "w") as outfile:
        outfile.write(__ZZ_SP_OPT_HEADER)

        # make a list of the "monika code" so we can join them later
        code_list = [
            IMG_OUT.format(code)
            for code in sprites
        ]

        outfile.write(",\n        ".join(code_list))
        
        outfile.write(__ZZ_SP_OPT_FOOTER)



#### strings for formatting:
__ZZ_SP_OPT_HEADER = """
############################ AUTO-GENERATED ###################################
## DO NOT EDIT THIS FILE                                                     ##
##                                                                           ##
## This was auto-generated by the spritepuller tool                          ##
###############################################################################
#
# This is a module designed for optimizing sprites by predicting them.
# NOTE: memory usage increases massively when this is used.
#   USE AT YOUR OWN RISK
#

init 2020 python:
    image_list = [
        """

__ZZ_SP_OPT_FOOTER = """
    ]
    renpy.start_predict(*image_list)
"""

